#!/usr/bin/perl
# generated by TPerl::Parser because it does not exist 
# Wed Apr 18 22:30:39 2007
# config2.pl should be hand edited for future quick hacks and overwrites etc.
$login_page = '/cgi-mr/pwikit_login.pl?id=<%id%>&password=<%password%>';

$BTN_NEXT = " NEXT >> ";
$allow_restart=1;
$BTN_REFUSED = "NEXT (skips checking)";
$BTN_BACK = " << BACK ";
$show_back_button = 1;
@jump_index = (
		'q1.q5',
		'q6.q10',
		'q11.q13',
		'LAST.LAST',
		);

1;
