bless({
  _SID           => "MAP001",
  _TritonRoot    => "/home/vhosts/pwidev/triton",
  _config_subdir => "config",
  _data_subdir   => "web",
  _doc_root      => undef,
  _doc_subdir    => "doc",
  _final_subdir  => "final",
  _html_subdir   => "html",
  _masks         => {},
  _options       => {
                      block_size       => 5,
                      custom_footer    => "<center><img src=\"/themes/ekit/ekit.daa.png\" alt=\"Discipline, Accountability, Achievement\" ></center>",
                      focus_off        => 1,
                      mailto           => "ctwebb\@mapconsulting.com",
                      mike             => 1,
                      no_copy          => 1,
                      no_progress_bar  => 1,
                      one_at_a_time    => 0,
                      optional_written => 0,
                      qbanner          => "<table border=0 cellpadding=0 cellspacing=0 class=\"bannertable\"><tr><TD class=\"bannerlogo\">&nbsp;<TD width=\"50px\" >&nbsp;<tr><TD class=\"bluebar\"> &nbsp;&nbsp; Participant's Questionnaire<TH class=\"bluebarq\">Q1</table>",
                      qscale           => "<P><%q_label%>",
                      survey_name      => "Participant's Questionnaire",
                      thankyou_url     => "thanks.htm",
                      theme            => "ekit",
                      window_title     => "MAP001 - Participant's Questionnaire",
                    },
  _questions     => [
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _code       => [
                                         "duedate=duedate",
                                         "id=id",
                                         "token=token",
                                         "login_page=login_page",
                                         "warning=warning",
                                         "ws_details=ws_details",
                                         "qbanner=qbanner",
                                         "qscale=qscale",
                                       ],
                        _dataInfo   => [],
                        _label      => "AA",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "",
                        _qnum       => 1,
                        _qtype      => 20,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q1",
                                           var => "Q1",
                                           var_label => "-<%qbanner%><%qscale%> Please describe your leadership/management strengths as a manager.",
                                         },
                                       ],
                        _label      => 1,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "<%qbanner%><%qscale%> Please describe your leadership/management strengths as a manager.",
                        _qnum       => 2,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q2",
                                           var => "Q2",
                                           var_label => "-Every leader/manager has opportunities for growth and improvement. What are the management <BR>and/or leadership skills in which you could improve?",
                                         },
                                       ],
                        _label      => 2,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "Every leader/manager has opportunities for growth and improvement. What are the management <BR>and/or leadership skills in which you could improve?",
                        _qnum       => 3,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q3",
                                           var => "Q3",
                                           var_label => "-What are your personal career goals in the organization?",
                                         },
                                       ],
                        _label      => 3,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "What are your personal career goals in the organization?",
                        _qnum       => 4,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q4",
                                           var => "Q4",
                                           var_label => "-What are the one-year measurable goals (\$, #, %, etc.) in your area of responsibility?",
                                         },
                                       ],
                        _label      => 4,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "What are the one-year measurable goals (\$, #, %, etc.) in your area of responsibility?",
                        _qnum       => 5,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q5",
                                           var => "Q5",
                                           var_label => "-What are your short-term measurable department goals (\$, #, %, etc.) that can be achieved within the <BR>next 30 to 45 days?",
                                         },
                                       ],
                        _label      => 5,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "What are your short-term measurable department goals (\$, #, %, etc.) that can be achieved within the <BR>next 30 to 45 days?",
                        _qnum       => 6,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q6",
                                           var => "Q6",
                                           var_label => "-<%qbanner%><%qscale%> What do you believe are the significant challenges you must resolve in order to achieve the above goals?",
                                         },
                                       ],
                        _label      => 6,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "<%qbanner%><%qscale%> What do you believe are the significant challenges you must resolve in order to achieve the above goals?",
                        _qnum       => 7,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q7",
                                           var => "Q7",
                                           var_label => "-What are your main COMMUNICATING challenges (e.g., style, effectiveness, frequency, internal, <BR>external, etc.)?",
                                         },
                                       ],
                        _label      => 7,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "What are your main COMMUNICATING challenges (e.g., style, effectiveness, frequency, internal, <BR>external, etc.)?",
                        _qnum       => 8,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q8",
                                           var => "Q8",
                                           var_label => "-What are your main PLANNING challenges (e.g., no formal planning, unclear goals, projects, etc.)?",
                                         },
                                       ],
                        _label      => 8,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "What are your main PLANNING challenges (e.g., no formal planning, unclear goals, projects, etc.)?",
                        _qnum       => 9,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q9",
                                           var => "Q9",
                                           var_label => "-What are your main ORGANIZING challenges (e.g., personal organization, availability of supplies, <BR>equipment, financial resources, time, organizational structure, etc.)?",
                                         },
                                       ],
                        _label      => 9,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "What are your main ORGANIZING challenges (e.g., personal organization, availability of supplies, <BR>equipment, financial resources, time, organizational structure, etc.)?",
                        _qnum       => 10,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q10",
                                           var => "Q10",
                                           var_label => "-What are your main STAFFING challenges (e.g., recruiting, selecting the right people, training, <br>development, retaining, etc.)?",
                                         },
                                       ],
                        _label      => 10,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "What are your main STAFFING challenges (e.g., recruiting, selecting the right people, training, <br>development, retaining, etc.)?",
                        _qnum       => 11,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q11",
                                           var => "Q11",
                                           var_label => "-<%qbanner%><%qscale%> What are your main CONTROLLING challenges (e.g., accountability, follow-through, taking <br>corrective action, cost and inventory control, productivity, quality, etc.)?",
                                         },
                                       ],
                        _label      => 11,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "<%qbanner%><%qscale%> What are your main CONTROLLING challenges (e.g., accountability, follow-through, taking <br>corrective action, cost and inventory control, productivity, quality, etc.)?",
                        _qnum       => 12,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q12",
                                           var => "Q12",
                                           var_label => "-What are your main LEADING challenges (e.g., clear vision, motivation, teamwork, initiating action, <br>innovation, commitment to team goals, etc.)?",
                                         },
                                       ],
                        _label      => 12,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "What are your main LEADING challenges (e.g., clear vision, motivation, teamwork, initiating action, <br>innovation, commitment to team goals, etc.)?",
                        _qnum       => 13,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q13",
                                           var => "Q13",
                                           var_label => "-What do you expect to gain from this management process? <BR>How will you know when those expectations have been met?",
                                         },
                                       ],
                        _label      => 13,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "What do you expect to gain from this management process? <BR>How will you know when those expectations have been met?",
                        _qnum       => 14,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _code       => [
                                         "my \$dcount = &count_data;",
                                         "&debug(\"Datacount = \$dcount\");",
                                         "if (\$dcount>0) {\$q_no = goto_qlab(\"LAST\") - 1;}",
                                         "if (\$dcount==0) {&db_conn;&db_set_status(\$survey_id,\$resp{id},\$resp{token},0,0)}",
                                       ],
                        _dataInfo   => [],
                        _label      => "CHECK",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "Check if we have enough data to allow submission of form",
                        _qnum       => 15,
                        _qtype      => 27,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames    => [],
                        _attributes    => [],
                        _dataInfo      => [
                                            {
                                              "pos" => 0,
                                              rkey => "ext_BACK2",
                                              type => "hidden",
                                              var => "BACK2",
                                              var_label => "See external page \"nodata.htm\"",
                                            },
                                          ],
                        _external_info => {
                                            names    => [undef, "BACK2"],
                                            options  => {
                                                          "" => {
                                                                alt => "HOME",
                                                                onclick => "document.location='/cgi-mr/pwikit_login.pl?id=<%id%>&password=<%token%>'",
                                                                tabindex => -1,
                                                                type => "BUTTON",
                                                                value => " HOME ",
                                                              },
                                                          BACK2 => { name => "BACK2", type => "hidden" },
                                                        },
                                            "values" => { "" => [" HOME ", " GO BACK "] },
                                          },
                        _label         => "NODATA",
                        _opt           => { external => "nodata.htm", instr => "", scale => 0 },
                        _prompt        => "See external page \"nodata.htm\"",
                        _qnum          => 16,
                        _qtype         => 7,
                        _scores        => [],
                        _setvalues     => [],
                        _skips         => [],
                        _vars          => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames    => [],
                        _attributes    => [],
                        _dataInfo      => [
                                            {
                                              "pos" => 0,
                                              rkey => "ext_finish",
                                              type => "hidden",
                                              var => "finish",
                                              var_label => "This is implemented as an external",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_q_labs",
                                              var => "q_labs",
                                              var_label => "This is implemented as an external",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_BACK2",
                                              type => "hidden",
                                              var => "BACK2",
                                              var_label => "This is implemented as an external",
                                            },
                                          ],
                        _external_info => {
                                            names    => ["finish", "q_labs", undef, "BACK2"],
                                            options  => {
                                                          "" => {
                                                                onclick => "document.q.finish.value='';",
                                                                type    => "SUBMIT",
                                                                value   => " SUBMIT ",
                                                              },
                                                          BACK2 => { name => "BACK2", type => "hidden" },
                                                          finish => { name => "finish", type => "hidden" },
                                                          q_labs => {},
                                                        },
                                            "values" => { "" => [" SUBMIT ", "NOT YET", " GO BACK "] },
                                          },
                        _label         => "LAST",
                        _opt           => { external => "last.htm", instr => "", scale => 0 },
                        _prompt        => "This is implemented as an external",
                        _qnum          => 17,
                        _qtype         => 7,
                        _scores        => [],
                        _setvalues     => [],
                        _skips         => [],
                        _vars          => [],
                      }, "TPerl::Survey::Question"),
                    ],
}, "TPerl::Survey")
