#!/usr/bin/perl
## $Id: xlate.msg.pl,v 1.3 2011-09-14 13:33:56 triton Exp  GENERATED FILE: DO NOT EDIT ! See /cgi-adm/xlate.msg.pl to edit/update
#
# CONTAINS LANGUAGE STRINGS FOR ERROR MESSAGES
#
our %sysmsg = (
	BTN_BACK => qq{Terug},
	BTN_DK => qq{Weet ik niet},
	BTN_NEXT => qq{Volgende},
	BTN_REFUSED => qq{Geweigerd},
	BTN_SUBMITTING => qq{Bezig met indienen... },
	ERRSTR_E10a => qq{U hebt zowel %s als %s geselecteerd&acirc;&#128;&brvbar; Maak een keuze a.u.b.!},
	ERRSTR_E11a => qq{U moet niet meer dan %d artikelen selecteren},
	ERRSTR_E11b => qq{U moet niet meer dan &eacute;&eacute;n artikel selecteren},
	ERRSTR_E12a => qq{Selecteer a.u.b. &eacute;&eacute;n van de artikelen uit de lijst},
	ERRSTR_E13a => qq{Selecteer a.u.b. &eacute;&eacute;n uit de uitklaplijst},
	ERRSTR_E14a => qq{Percentages moeten samen 100 zijn (u hebt nu %d%)},
	ERRSTR_E15a => qq{Vul a.u.b. alle antwoorden voor [%s] in},
	ERRSTR_E15b => qq{Selecteer a.u.b. recentheidscode voor %s},
	ERRSTR_E15c => qq{Selecteer a.u.b. minstens %d antwoorden},
	ERRSTR_E15d => qq{Selecteer a.u.b. minstens %d antwoorden voor %s},
	ERRSTR_E16a => qq{Fout: maak &eacute;&eacute;n keuze uit elke rij},
	ERRSTR_E17a => qq{Maak een selectie uit bovenstaande lijst},
	ERRSTR_E18a => qq{Foutmelding: kies voor elke plaats in uw voorkeursvolgorde een ander getal},
	ERRSTR_E19a => qq{Fout: u hebt dezelfde beoordeling aan meerdere artikelen gegeven},
	ERRSTR_E1a => qq{We zouden het erg op prijs stellen als u hier iets kunt invullen},
	ERRSTR_E20a => qq{Fout: u kunt niet twee keer hetzelfde kiezen},
	ERRSTR_E21a => qq{Ongeldig vraagtype - neem a.u.b. contact op met Support},
	ERRSTR_E22a => qq{U hebt &#39;anders&#39; geselecteerd, vertel a.u.b. wat dit inhoudt},
	ERRSTR_E22b => qq{U hebt &#39;anders&#39; geselecteerd, vertel a.u.b. wat dit inhoudt},
	ERRSTR_E22c => qq{U hebt &#39;anders&#39; geselecteerd, vertel a.u.b. wat dit inhoudt voor %s},
	ERRSTR_E22d => qq{U heeft iets, maar niet te selecteren &#39;ander&#39;, dan kunt u corrigeren},
	ERRSTR_E22e => qq{U gaf &#39;andere&#39;, geef het a.u.b. (of de reactie te wissen)},
	ERRSTR_E22f => qq{U hebt opgegeven van de &#39;ander&#39;, dan kunt u rate het (of de reactie te wissen)},
	ERRSTR_E23a => qq{Vul a.u.b . minstens %d antwoorden in},
	ERRSTR_E23b => qq{Vul a.u.b. minstens &eacute;&eacute;n antwoord in},
	ERRSTR_E24 => qq{Wellicht binnen 12 maanden - a.u.b. vragen...},
	ERRSTR_E25 => qq{Fout: respondent is pas},
	ERRSTR_E26 => qq{Selecteer minstens &eacute;&eacute;n voor %s},
	ERRSTR_E27a => qq{Dit geboortejaar (},
	ERRSTR_E27b => qq{) lijkt niet mogelijk voor iemand van},
	ERRSTR_E27c => qq{jaar oud!\n Misschien moet het},
	ERRSTR_E27d => qq{ zijn?},
	ERRSTR_E28 => qq{Sorry, het klopt niet om tegelijkertijd te WEIGEREN en NIET TE WETEN},
	ERRSTR_E29 => qq{Gelieve Sleep alle items over naar &#39;Uw selectie&#39; box},
	ERRSTR_E29a => qq{Gelieve Sleep},
	ERRSTR_E29b => qq{items over naar &#39;Uw selectie&#39; box},
	ERRSTR_E2a => qq{Graag alle antwoorden invullen},
	ERRSTR_E2b => qq{Graag minstens %d antwoord(en) invullen},
	ERRSTR_E30a => qq{U moet schlects },
	ERRSTR_E30b => qq{items in de &#39;Uw selectie&#39; box},
	ERRSTR_E3a => qq{Het antwoord %s is geen getal},
	ERRSTR_E4a => qq{Het antwoord %d is te laag, het zou minimaal %d moeten zijn},
	ERRSTR_E5a => qq{Het antwoord %d is te hoog, het zou maximaal %d moeten zijn},
	ERRSTR_E6a => qq{Sorry, dit antwoord klopt niet (het getal zou hoger dan of gelijk aan %d moeten zijn)},
	ERRSTR_E7a => qq{U moet minstens %d artikelen selecteren},
	ERRSTR_E7b => qq{U moet minstens %d of de %s optie selecteren},
	ERRSTR_E8a => qq{Sorry, dit antwoord klopt niet (het antwoord zou lager dan of gelijk aan %d moeten zijn)},
	ERRSTR_E9a => qq{Sorry, deze getallen moeten samen %d zijn (u hebt %d)},
	ERRSTR_I1 => qq{VUL EEN HEEL GETAL IN},
	ERRSTR_I2 => qq{SELECTEER ZO VEEL MOGELIJK OPTIES},
	ERRSTR_I3 => qq{SELECTEER SLECHTS &Eacute;&Eacute;N OPTIE},
	ERRSTR_I30 => qq{SLEEP DE AANWIJZER LANGS DE SCHAALVERDELING OM UW BEOORDELING AAN TE GEVEN},
	ERRSTR_I4 => qq{TYP A.U.B. UW REACTIE},
	ERRSTR_I5 => qq{VUL PERCENTAGES IN, MOET IN TOTAAL 100% ZIJN},
	ERRSTR_I6 => qq{VUL BEDRAG IN HELE DOLLARS IN},
	ERRSTR_I7 => qq{ONGELDIG VRAAGTYPE},
	ERRSTR_I8 => qq{SELECTEER &Eacute;&Eacute;N OPTIE PER RIJ},
	ERRSTR_I9 => qq{SELECTEER &Eacute;&Eacute;N ARTIKEL IN ELKE KOLOM VOOR ELKE RIJ},
	TXT_AGE => qq{Leeftijd},
	TXT_AGE_ONS => qq{Leeftijd},
	TXT_AGE_REC => qq{Leeftijd},
	TXT_AVAIL => qq{beschikbare selecties},
	TXT_COUNT => qq{Getal},
	TXT_DAY => qq{Dag},
	TXT_HOWLONG => qq{Hoe lang geleden},
	TXT_ITEM => qq{Artikel},
	TXT_JS1 => qq{We hebben een probleem!},
	TXT_JS2 => qq{Uw browser ondersteunt geen JavaScript hebt ingeschakeld. Dit is een probleem, omdat het onderzoek maakt gebruik van geavanceerde HTML-functies die vereisen dat Javascript wordt ingeschakeld.},
	TXT_JS3 => qq{Hoe op te lossen},
	TXT_JS4 => qq{U kunt gebruik maken van een andere browser die Javascript heeft ingeschakeld, of krijgen instructies over hoe je het kunt hier:},
	TXT_JS5 => qq{Hoe weet ik wanneer ik dit opgelost?},
	TXT_JS6 => qq{Als je eenmaal hebt aangezet het op, kom terug naar deze pagina en vernieuwen het. Als dit foutbericht niet verschijnt, is het probleem opgelost.},
	TXT_MONTH => qq{Maand},
	TXT_NOTES => qq{Opmerkingen:},
	TXT_NOTHING => qq{Niets},
	TXT_OTHER_SPEC => qq{Anders (specificeer:)},
	TXT_QS => qq{Vragen},
	TXT_TICK => qq{Aanvinken},
	TXT_YEAR => qq{Jaar},
	TXT_YOURS => qq{Uw selectie},
);
# Default Prompts
#
@def_instr = 	(
		"Invalid question type - please contact support",
		"($sysmsg{ERRSTR_I1})",				# Number
		"($sysmsg{ERRSTR_I2})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I4})",
		"($sysmsg{ERRSTR_I5})",
		"",
		"",
		"($sysmsg{ERRSTR_I6})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I7})",
		"($sysmsg{ERRSTR_I3})",
		"",
		"($sysmsg{ERRSTR_I8})",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",										# Spares are defensive
		"($sysmsg{ERRSTR_I30})",
	);

#
# Even if you have to edit this file, please leave this soldier on the last line
#
1;
