#!/usr/bin/perl
## $Id: xlate.msg.pl,v 1.3 2011-09-14 13:33:56 triton Exp  GENERATED FILE: DO NOT EDIT ! See /cgi-adm/xlate.msg.pl to edit/update
#
# CONTAINS LANGUAGE STRINGS FOR ERROR MESSAGES
#
our %sysmsg = (
	BTN_BACK => qq{Balik },
	BTN_DK => qq{Tidak tahu},
	BTN_NEXT => qq{Berikutnya},
	BTN_REFUSED => qq{Menolak},
	BTN_SUBMITTING => qq{Mengajukan...},
	ERRSTR_E10a => qq{Anda telah memilih %s dan juga %s&acirc;&#128;&brvbar;  Tolong putuskan pemikiran anda!},
	ERRSTR_E11a => qq{Anda sebaiknya memilih jangan lebih dari %d butir-butir},
	ERRSTR_E11b => qq{Anda sebaiknya memilih jangan lebih dari satu butir},
	ERRSTR_E12a => qq{Tolong pilih salah satu butir dari daftar},
	ERRSTR_E13a => qq{Tolong pilih satu dari daftar menu ke bawah},
	ERRSTR_E14a => qq{Persentasi-persentasi harus terjumlah ke 100 (anda dapat %d% sampai sekarang)},
	ERRSTR_E15a => qq{Tolong selesaikan semua jawaban untuk [%s]},
	ERRSTR_E15b => qq{Silahkan pilih kode kebaruan untuk %s},
	ERRSTR_E15c => qq{Tolong pilih paling sedikit s%d jawaban-jawaban},
	ERRSTR_E15d => qq{Tolong pilih paling sedikit %d jawaban-jawaban untuk %s},
	ERRSTR_E16a => qq{Salah: tolong buat satu pilihan dari setiap baris},
	ERRSTR_E17a => qq{Tolong pilih dari daftar di atas},
	ERRSTR_E18a => qq{Salah: Tolong pilih angka yang berbeda untuk setiap tempat yang menggambarkan urutan pilihan anda.},
	ERRSTR_E19a => qq{Salah: anda telah memberikan nilai sama kepada beberapa butir},
	ERRSTR_E1a => qq{Kami akan sangat menghargai apabila anda dapat mengatakan sesuatu di sini },
	ERRSTR_E20a => qq{Salah: anda tidak boleh memilih yang sama dua kali},
	ERRSTR_E21a => qq{Pertanyaan tidak legit - silahkan hubungi bantuan},
	ERRSTR_E22a => qq{Anda memilih &#39;yang lain&#39;, tolong beritahukan saya apakah yang lain itu},
	ERRSTR_E22b => qq{Anda memilih &#39;yang lain&#39;, tolong beritahukan saya apakah yang lain itu},
	ERRSTR_E22c => qq{Anda memilih &#39;yang lain&#39;, tolong beritahukan saya apakah yang lain itu %s},
	ERRSTR_E22d => qq{Anda memilih &#39;yang lain&#39;, tolong beritahukan saya apakah yang lain itu},
	ERRSTR_E22e => qq{Anda memilih &#39;yang lain&#39;, tolong beritahukan saya apakah yang lain itu},
	ERRSTR_E22f => qq{Anda memilih &#39;yang lain&#39;, tolong beritahukan saya apakah yang lain itu},
	ERRSTR_E23a => qq{Tolong isi paling sedikit %d jawaban-jawaban},
	ERRSTR_E23b => qq{Tolong isi paling sedikit satu jawaban},
	ERRSTR_E24 => qq{Kemungkinan dalam waktu 12 bulan - silahkan tanya},
	ERRSTR_E25 => qq{Salah: Penjawab adalah hanya },
	ERRSTR_E26 => qq{Tolong pilih paling sedikit satu untuk %s},
	ERRSTR_E27a => qq{Tahun kelahiran ini (},
	ERRSTR_E27b => qq{) kelihatannya tidak mungkin untuk suatu },
	ERRSTR_E27c => qq{ umur ! Mungkin seharusnya },
	ERRSTR_E27d => qq{?},
	ERRSTR_E28 => qq{Maaf, tidak masuk akal untuk MENOLAK dan TIDAK TAHU pada saat yang sama},
	ERRSTR_E29 => qq{Tolong tarik semua barang ke seberang ke kotak &#39;Pilihan-pilihan anda&#39;},
	ERRSTR_E29a => qq{Tolong tarik },
	ERRSTR_E29b => qq{barang-barang di seberang kotak &#39;Pilihan-pilihan anda&#39;},
	ERRSTR_E2a => qq{Tolong isi dengan jawaban seluruhnya},
	ERRSTR_E2b => qq{Tolong isi dengan paling sedikit %d jawaban(-jawaban)},
	ERRSTR_E30a => qq{Anda seharusnya hanya mempunyai },
	ERRSTR_E30b => qq{barang-barang di kotak &#39;Pilihan-pilihan anda&#39;},
	ERRSTR_E3a => qq{Jawaban %s adalah bukan suatu angka},
	ERRSTR_E4a => qq{Jawaban %d adalah terlalu rendah, seharusnya paling sedikit %d},
	ERRSTR_E5a => qq{Jawaban %d adalah terlalu tinggi, seharusnya tidak lebih dari %d},
	ERRSTR_E6a => qq{Maaf, jawaban ini tidak masuk akal (angka seharusnya lebih besar atau sama dengan %d)},
	ERRSTR_E7a => qq{Anda harus memilih paling sedikit %d butir},
	ERRSTR_E7b => qq{Anda harus memilih paling sedikit %d atau pilih butir %s},
	ERRSTR_E8a => qq{Maaf, jawaban ini tidak masuk akal (angka seharusnya lebih kecil atau sama dengan %d)},
	ERRSTR_E9a => qq{Maaf, angka-angka ini harus mencapai total %d (anda dapat %d)},
	ERRSTR_I1 => qq{MASUKKAN ANGKA SEUTUHNYA},
	ERRSTR_I2 => qq{PILIH SEBANYAK MUNGKIN YANG TERAPLIKASI},
	ERRSTR_I3 => qq{PILIH SATU SAJA},
	ERRSTR_I30 => qq{TARIK PANAH SEPANJANG JANGKA UNTUK MENDAPATKAN NILAI ANDA},
	ERRSTR_I4 => qq{TOLONG KETIK JAWABAN ANDA},
	ERRSTR_I5 => qq{MASUKKAN PERSENTASI-PERSENTASI, HARUS BERJUMLAH TOTAL 100%},
	ERRSTR_I6 => qq{MASUKKAN ANGKA DALAM DOLLAR SEUTUHNYA},
	ERRSTR_I7 => qq{JENIS PERTANYAAN TIDAK LEGIT},
	ERRSTR_I8 => qq{PILIH SATU BUTIR SETIAP BARIS},
	ERRSTR_I9 => qq{PILIH SATU BUTIR DALAM SETIAP KOLUM UNTUK SETIAP BARIS},
	TXT_AGE => qq{Umur},
	TXT_AGE_ONS => qq{Umur onset},
	TXT_AGE_REC => qq{Umur resesi},
	TXT_AVAIL => qq{Pilihan-pilihan yang tersedia},
	TXT_COUNT => qq{Hitung},
	TXT_DAY => qq{Hari},
	TXT_HOWLONG => qq{Berapa waktu lalu},
	TXT_ITEM => qq{Butir},
	TXT_JS1 => qq{Kita punya masalah!},
	TXT_JS2 => qq{Browser Anda tidak memiliki javascript diaktifkan. Ini adalah masalah karena survei menggunakan fitur HTML canggih yang membutuhkan Javascript untuk dihidupkan.},
	TXT_JS3 => qq{Bagaimana untuk memperbaikinya},
	TXT_JS4 => qq{Anda bisa menggunakan browser yang berbeda yang memiliki Javascript, atau mendapatkan petunjuk tentang cara untuk menyalakannya di sini:},
	TXT_JS5 => qq{Bagaimana saya tahu ketika saya telah tetap itu?},
	TXT_JS6 => qq{Setelah Anda menyalakannya, kembali ke halaman ini dan refresh. Jika pesan kesalahan ini tidak muncul, masalahnya adalah tetap.},
	TXT_MONTH => qq{Bulan},
	TXT_NOTES => qq{Catatan:},
	TXT_NOTHING => qq{Tidak ada},
	TXT_OTHER_SPEC => qq{Lainnya (sebutkan:)},
	TXT_QS => qq{Pertanyaan-pertanyaan},
	TXT_TICK => qq{Cantumkan},
	TXT_YEAR => qq{Tahun},
	TXT_YOURS => qq{Pilihan-pilihan anda},
);
# Default Prompts
#
@def_instr = 	(
		"Invalid question type - please contact support",
		"($sysmsg{ERRSTR_I1})",				# Number
		"($sysmsg{ERRSTR_I2})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I4})",
		"($sysmsg{ERRSTR_I5})",
		"",
		"",
		"($sysmsg{ERRSTR_I6})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I7})",
		"($sysmsg{ERRSTR_I3})",
		"",
		"($sysmsg{ERRSTR_I8})",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",										# Spares are defensive
		"($sysmsg{ERRSTR_I30})",
	);

#
# Even if you have to edit this file, please leave this soldier on the last line
#
1;
