#!/usr/bin/perl
## $Id: xlate.msg.pl,v 1.3 2011-09-14 13:33:56 triton Exp  GENERATED FILE: DO NOT EDIT ! See /cgi-adm/xlate.msg.pl to edit/update
#
# CONTAINS LANGUAGE STRINGS FOR ERROR MESSAGES
#
our %sysmsg = (
	BTN_BACK => qq{Balik},
	BTN_DK => qq{Tidak tahu},
	BTN_NEXT => qq{Berikut},
	BTN_REFUSED => qq{Enggan},
	BTN_SUBMITTING => qq{Penyerahan...},
	ERRSTR_E10a => qq{Anda telah memilih %s serta juga %s&acirc;&#128;&brvbar; Sila pilih satu daripadanya sahaja!},
	ERRSTR_E11a => qq{Anda tidak harus pilih lebih daripada %d perkara},
	ERRSTR_E11b => qq{Anda tidak harus pilih lebih daripada satu perkara},
	ERRSTR_E12a => qq{Sila pilih satu daripada perkara-perkara dalam senarai ini},
	ERRSTR_E13a => qq{Sila pilih satu daripada senarai tarik turun ini},
	ERRSTR_E14a => qq{Jumlah peratus mesti 100 (jumlah anda setakat ini adalah %d)},
	ERRSTR_E15a => qq{Sila lengkapkan semua jawapan bagi %s]},
	ERRSTR_E15b => qq{Sila pilih recency code bagi %s},
	ERRSTR_E15c => qq{Sila pilih sekurang-kurangnya %d jawapan},
	ERRSTR_E15d => qq{Sila pilih sekurang-kurangnya %d jawapan untuk %s},
	ERRSTR_E16a => qq{Ralat: sila pilih satu daripada setiap barisan},
	ERRSTR_E17a => qq{Sila buat satu pilihan daripada senarai di atas},
	ERRSTR_E18a => qq{Ralat: Sila pilih nombor yang berlainan bagi setiap tempat untuk menunjukkan keutamaan anda.},
	ERRSTR_E19a => qq{Ralat: anda telah memberikan ranking yang sama kepada pelbagai perkara},
	ERRSTR_E1a => qq{Kami harap dapat kiranya anda menyatakan sesuatu di sini  },
	ERRSTR_E20a => qq{Ralat: anda tidak boleh pilih yang sama dua kali},
	ERRSTR_E21a => qq{Jenis soalan tidak sah - sila hubungi sokongan},
	ERRSTR_E22a => qq{Anda memilih &quot;lain&quot;, sila beritahu saya apa perkara lain itu},
	ERRSTR_E22b => qq{Anda memilih &quot;lain&quot;, sila beritahu saya apa perkara lain itu},
	ERRSTR_E22c => qq{Anda memilih &quot;lain&quot;, sila beritahu saya apa perkara lain itu %s},
	ERRSTR_E22d => qq{Anda memilih &quot;lain&quot;, sila beritahu saya apa perkara lain itu},
	ERRSTR_E22e => qq{Anda memilih &quot;lain&quot;, sila beritahu saya apa perkara lain itu},
	ERRSTR_E22f => qq{Anda memilih &quot;lain&quot;, sila beritahu saya apa perkara lain itu},
	ERRSTR_E23a => qq{Sila isikan sekurang-kurangnya %d jawapan},
	ERRSTR_E23b => qq{Sila isikan sekurang-kurangnya satu jawapan},
	ERRSTR_E24 => qq{Kalau boleh sebelum 12 bulan &acirc;&#128;&#147; sila tanya...},
	ERRSTR_E25 => qq{Ralat: Responden adalah hanya  },
	ERRSTR_E26 => qq{Sila pilih sekurang-kurangnya satu untuk %s},
	ERRSTR_E27a => qq{Tahun lahir ini (},
	ERRSTR_E27b => qq{) adalah tidak mungkin bagi seorang yang berumur },
	ERRSTR_E27c => qq{  tahun !\n Mungkin seharusnya  },
	ERRSTR_E27d => qq{?},
	ERRSTR_E28 => qq{Saya minta maaf, ia tidak masuk akal untuk SAMPAH dan TIDAK TAHU pada masa yang sama},
	ERRSTR_E29 => qq{Sila seret semua item ke kotak &#39;Pilihan anda&#39; di sebelah},
	ERRSTR_E29a => qq{Sila seret},
	ERRSTR_E29b => qq{item ke kotak &#39;Pilihan anda&#39; di sebelah},
	ERRSTR_E2a => qq{Sila isikan semua jawapan},
	ERRSTR_E2b => qq{Sila isikan sekurang-kurangnya %d jawapan},
	ERRSTR_E30a => qq{Anda hanya harus mempunyai},
	ERRSTR_E30b => qq{item dalam kotak &#39;Pilihan anda&#39;},
	ERRSTR_E3a => qq{Jawapan %s adalah bukan nombor},
	ERRSTR_E4a => qq{Jawapan %d adalah terlalu rendah, ia harus sekurang-kurangnya %d},
	ERRSTR_E5a => qq{Jawapan %d adalah terlalu tinggi, ia harus tidak lebih daripada %d},
	ERRSTR_E6a => qq{Maaf, jawapan ini tidak dapat difahami (nombor ini harus lebih besar daripada atau sama dengan %d)},
	ERRSTR_E7a => qq{Anda mesti pilih sekurang-kurangnya %d perkara},
	ERRSTR_E7b => qq{Anda mesti pilih sekurang-kurangnya %d atau pilih opsyen %s},
	ERRSTR_E8a => qq{Maaf, jawapan ini tidak dapat difahami (nombor ini harus kurang daripada atau sama dengan %d)},
	ERRSTR_E9a => qq{Maaf, jumlah nombor-nombor ini mesti %d (jumlah anda adalah %d)},
	ERRSTR_I1 => qq{MASUKKAN NOMBOR BULAT},
	ERRSTR_I2 => qq{PILIH SEBANYAK MANA YANG BERKENAAN},
	ERRSTR_I3 => qq{PILIH SATU SAHAJA},
	ERRSTR_I30 => qq{SERET PENUNJUK MELALUI SKALA UNTUK MEMBERIKAN PENGADARAN ANDA},
	ERRSTR_I4 => qq{SILA TAIP JAWAPAN ANDA},
	ERRSTR_I5 => qq{MASUKKAN PERATUS, JUMLAH MESTI 100%},
	ERRSTR_I6 => qq{MASUKKAN JUMLAH DALAM DOLAR BULAT},
	ERRSTR_I7 => qq{JENIS SOALAN TIDAK SAH},
	ERRSTR_I8 => qq{PILIH SATU PERKARA PER BARISAN},
	ERRSTR_I9 => qq{PILIH SATU PERKARA DALAM SETIAP KOLUM BAGI SETIAP BARISAN},
	TXT_AGE => qq{Umur},
	TXT_AGE_ONS => qq{permulaan Umur},
	TXT_AGE_REC => qq{kemelesetan Umur},
	TXT_AVAIL => qq{Pilihan yang terdapat},
	TXT_COUNT => qq{Bilangan},
	TXT_DAY => qq{Hari},
	TXT_HOWLONG => qq{Sudah berapa lama},
	TXT_ITEM => qq{Perkara},
	TXT_JS1 => qq{Kita ada masalah!},
	TXT_JS2 => qq{Pelayar anda tidak mempunyai javascript,. Ini menjadi masalah kerana kajian itu menggunakan ciri-ciri maju HTML yang memerlukan Javascript dihidupkan.},
	TXT_JS3 => qq{Bagaimana untuk menetapkan},
	TXT_JS4 => qq{Anda boleh menggunakan pelayar yang lain yang telah Javascript, atau mendapat arahan bagaimana untuk menghidupkannya di sini:},
	TXT_JS5 => qq{Bagaimanakah saya tahu apabila saya tetap?},
	TXT_JS6 => qq{Sebaik sahaja anda menghidupkan, kembali ke halaman ini dan menyegarkan. Jika mesej ralat ini tidak muncul, masalah itu tetap.},
	TXT_MONTH => qq{Bulan},
	TXT_NOTES => qq{Nota:},
	TXT_NOTHING => qq{Tiada},
	TXT_OTHER_SPEC => qq{Lain (nyatakan:)},
	TXT_QS => qq{Q&#39;s},
	TXT_TICK => qq{Tanda rait},
	TXT_YEAR => qq{Tahun},
	TXT_YOURS => qq{Pilihan anda},
);
# Default Prompts
#
@def_instr = 	(
		"Invalid question type - please contact support",
		"($sysmsg{ERRSTR_I1})",				# Number
		"($sysmsg{ERRSTR_I2})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I4})",
		"($sysmsg{ERRSTR_I5})",
		"",
		"",
		"($sysmsg{ERRSTR_I6})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I7})",
		"($sysmsg{ERRSTR_I3})",
		"",
		"($sysmsg{ERRSTR_I8})",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",										# Spares are defensive
		"($sysmsg{ERRSTR_I30})",
	);

#
# Even if you have to edit this file, please leave this soldier on the last line
#
1;
