#!/usr/bin/perl
## $Id: strings-sw.pl,v 1.7 2011-09-09 10:55:14 triton Exp $
#
# GENERATED FILE: DO NOT EDIT ! See /cgi-adm/xlate.msg.pl to edit/update
#
# CONTAINS LANGUAGE STRINGS FOR ERROR MESSAGES
#
our %sysmsg = (
	BTN_BACK => qq{Tillbaka},
	BTN_DK => qq{Vet ej},
	BTN_NEXT => qq{N&auml;sta},
	BTN_REFUSED => qq{Avb&ouml;jde},
	BTN_SUBMITTING => qq{Skickar...},
	ERRSTR_E10a => qq{Du har valt b&aring;de %s och %s... Var sn&auml;ll och best&auml;m dig!},
	ERRSTR_E11a => qq{Du b&ouml;r inte v&auml;lja fler &auml;n %d artiklar},
	ERRSTR_E11b => qq{Du b&ouml;r inte v&auml;lja fler &auml;n en artikel},
	ERRSTR_E12a => qq{Var god v&auml;lj en av artiklarna i listan},
	ERRSTR_E13a => qq{Var god v&auml;lj en fr&aring;n listrutan},
	ERRSTR_E14a => qq{Procenttalen m&aring;ste uppg&aring; till 100 (du har %d% hittills)},
	ERRSTR_E15a => qq{Var v&auml;nlig fyll i alla svar f&ouml;r [%s]},
	ERRSTR_E15b => qq{Var v&auml;nlig v&auml;lj R-kod f&ouml;r %s},
	ERRSTR_E15c => qq{Var v&auml;nlig v&auml;lj &aring;tminstone %d svar},
	ERRSTR_E15d => qq{Var v&auml;nlig v&auml;lj &aring;tminstone %d svar f&ouml;r %s},
	ERRSTR_E16a => qq{Fel: Var god g&ouml;r ett val fr&aring;n varje rad},
	ERRSTR_E17a => qq{Var god v&auml;lj fr&aring;n listan ovan},
	ERRSTR_E18a => qq{Felmeddelande: V&auml;nligen v&auml;lj olika siffror f&ouml;r varje plats som visar den ordning ni f&ouml;redrar.},
	ERRSTR_E19a => qq{Fel: Du har givit flera artiklar samma rangordning},
	ERRSTR_E1a => qq{Vi skulle verkligen uppskatta om du kunde l&auml;mna n&aring;gra kommentarer h&auml;r},
	ERRSTR_E20a => qq{Fel: Du f&aring;r inte v&auml;lja samma sak tv&aring; g&aring;nger},
	ERRSTR_E21a => qq{Ogiltig fr&aring;ga V&auml;nligen kontakta supportavdelningen},
	ERRSTR_E22a => qq{Du valde &#39;&ouml;vrigt&#39;. V&auml;nligen ange vad det inneb&auml;r},
	ERRSTR_E22b => qq{Du valde &#39;&ouml;vrigt&#39;. V&auml;nligen ange vad det inneb&auml;r},
	ERRSTR_E22c => qq{You selected &#39;other&#39;, please tell me what the other thing is for %s},
	ERRSTR_E22d => qq{You entered something, but did not select &#39;other&#39;, please correct it},
	ERRSTR_E22e => qq{You rated &#39;other&#39;, please specify it (or erase the response)},
	ERRSTR_E22f => qq{You specified the &#39;other&#39;, please rate it (or erase the response)},
	ERRSTR_E23a => qq{Var god fyll i &aring;tminstone %d svar},
	ERRSTR_E23b => qq{Var god fyll i &aring;tminstone ett svar},
	ERRSTR_E24 => qq{Antagligen inom 12 m&aring;nader var god fr&aring;ga...},
	ERRSTR_E25 => qq{Fel: Respondent &auml;r bara},
	ERRSTR_E26 => qq{Var v&auml;nlig v&auml;lj &aring;tminstone ett f&ouml;r %s},
	ERRSTR_E27a => qq{Detta f&ouml;delsedatum ( },
	ERRSTR_E27b => qq{) verkar osannolikt f&ouml;r en },
	ERRSTR_E27c => qq{ -&aring;ring!\n Kanske ska det vara},
	ERRSTR_E27d => qq{ ?},
	ERRSTR_E28 => qq{Det &auml;r tyv&auml;rr ologiskt att v&auml;lja V&Auml;GRAR och VET EJ p&aring; samma g&aring;ng},
	ERRSTR_E29 => qq{V&auml;nligen dra alla remsorna &ouml;ver till &#39;Era urval-rutan&#39;	},
	ERRSTR_E29a => qq{V&auml;nligen dra},
	ERRSTR_E29b => qq{remsorna &ouml;ver till &#39;Era urval-rutan&#39;},
	ERRSTR_E2a => qq{Var god fyll i alla svar},
	ERRSTR_E2b => qq{Var god fyll i &aring;tminstone %d svar},
	ERRSTR_E30a => qq{Ni borde endast ha },
	ERRSTR_E30b => qq{remsor i &#39;Era urval-rutan&#39; },
	ERRSTR_E3a => qq{Svaret %s &auml;r inte ett nummer},
	ERRSTR_E4a => qq{Svaret %d &auml;r f&ouml;r l&aring;gt. Det b&ouml;r vara &aring;tminstone %d},
	ERRSTR_E5a => qq{Svaret %d &auml;r f&ouml;r h&ouml;gt. Det b&ouml;r inte vara h&ouml;gre &auml;n %d},
	ERRSTR_E6a => qq{Detta svar &auml;r tyv&auml;rr obegripligt (numret b&ouml;r vara st&ouml;rre &auml;n eller lika med %d)},
	ERRSTR_E7a => qq{Du m&aring;ste v&auml;lja &aring;tminstone %d artiklar},
	ERRSTR_E7b => qq{Du m&aring;ste v&auml;lja &aring;tminstone %d eller v&auml;lja alternativet %s},
	ERRSTR_E8a => qq{Detta svar &auml;r tyv&auml;rr obegripligt (numret b&ouml;r vara mindre &auml;n eller lika med %d)},
	ERRSTR_E9a => qq{F&ouml;rs&ouml;k igen. Dessa nummer m&aring;ste ge %d sammanlagt (du har %d)},
	ERRSTR_I1 => qq{ANGE ETT HELT TAL},
	ERRSTR_I2 => qq{V&Auml;LJ S&Aring; M&Aring;NGA SOM &Auml;R RELEVANTA},
	ERRSTR_I3 => qq{V&Auml;LJ ENDAST EN},
	ERRSTR_I30 => qq{DRA MARK&Ouml;REN L&Auml;NGS SKALAN F&Ouml;R ATT GE DIN UTV&Auml;RDERING},
	ERRSTR_I4 => qq{VAR GOD SKRIV IN DITT SVAR},
	ERRSTR_I5 => qq{ANGE PROCENTTAL, M&Aring;STE BLI 100% SAMMANLAGT},
	ERRSTR_I6 => qq{ANGE SUMMAN I HELA DOLLAR},
	ERRSTR_I7 => qq{OGILTIG FR&Aring;GA},
	ERRSTR_I8 => qq{V&Auml;LJ EN ARTIKEL PER RAD},
	ERRSTR_I9 => qq{V&Auml;LJ EN ARTIKEL I VARJE SPALT F&Ouml;R VARJE RAD},
	TXT_AGE => qq{&Aring;lder},
	TXT_AGE_ONS => qq{&Aring;lder b&ouml;rjan},
	TXT_AGE_REC => qq{&Aring;lder slut},
	TXT_AVAIL => qq{Mina urval},
	TXT_COUNT => qq{Hur m&aring;nga?},
	TXT_DAY => qq{Dag},
	TXT_HOWLONG => qq{Hur l&auml;nge sedan},
	TXT_ITEM => qq{Item},
	TXT_MONTH => qq{M&aring;nad},
	TXT_NOTES => qq{Anteckningar:},
	TXT_NOTHING => qq{Inget},
	TXT_OTHER_SPEC => qq{&Ouml;vrigt (specificera:)},
	TXT_QS => qq{Qs},
	TXT_TICK => qq{Tick},
	TXT_YEAR => qq{&Aring;r},
	TXT_YOURS => qq{Tillg&auml;ngliga urval},
);
# Default Prompts
#
@def_instr = 	(
		"Invalid question type - please contact support",
		"($sysmsg{ERRSTR_I1})",				# Number
		"($sysmsg{ERRSTR_I2})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I4})",
		"($sysmsg{ERRSTR_I5})",
		"",
		"",
		"($sysmsg{ERRSTR_I6})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I7})",
		"($sysmsg{ERRSTR_I3})",
		"",
		"($sysmsg{ERRSTR_I8})",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",										# Spares are defensive
		"($sysmsg{ERRSTR_I30})",
	);

#
# Even if you have to edit this file, please leave this soldier on the last line
#
1;
