#!/usr/bin/perl
## $Id: xlate.msg.pl,v 1.3 2011-09-14 13:33:56 triton Exp  GENERATED FILE: DO NOT EDIT ! See /cgi-adm/xlate.msg.pl to edit/update
#
# CONTAINS LANGUAGE STRINGS FOR ERROR MESSAGES
#
our %sysmsg = (
	BTN_BACK => qq{Zur&uuml;ck},
	BTN_DK => qq{Wei&szlig; nicht},
	BTN_NEXT => qq{Weiter},
	BTN_REFUSED => qq{Abgelehnt},
	BTN_SUBMITTING => qq{Senden...},
	ERRSTR_E10a => qq{Sie haben %s sowie %s gew&auml;hlt. Bitte w&auml;hlen Sie nur einen Punkt aus.},
	ERRSTR_E11a => qq{Sie k&ouml;nnen maximal %d Punkte w&auml;hlen.},
	ERRSTR_E11b => qq{Sie k&ouml;nnen maximal einen Punkt w&auml;hlen.},
	ERRSTR_E12a => qq{Bitte w&auml;hlen Sie einen Punkt in dieser Liste.},
	ERRSTR_E13a => qq{Bitte w&auml;hlen Sie einen Punkt aus dem Pull-Down-Men&uuml;.},
	ERRSTR_E14a => qq{Prozents&auml;tze m&uuml;ssen 100% ergeben (Sie haben %d% bis jetzt)},
	ERRSTR_E15a => qq{Bitte f&uuml;llen Sie alle Antworten aus f&uuml;r [%s]},
	ERRSTR_E15b => qq{Bitte w&auml;hlen Sie den Letztkauf-Code f&uuml;r %s},
	ERRSTR_E15c => qq{Bitte w&auml;hlen Sie mindestens %d Antworten aus},
	ERRSTR_E15d => qq{Bitte w&auml;hlen Sie mindestens %d Antworten f&uuml;r %s aus},
	ERRSTR_E16a => qq{Fehler: bitte w&auml;hlen Sie einen Punkt aus jeder Reihe.},
	ERRSTR_E17a => qq{Bitte w&auml;hlen Sie aus oben stehender Liste.},
	ERRSTR_E18a => qq{Fehler: Bitte w&auml;hlen Sie f&uuml;r jeden Einkaufsort eine andere Zahl, die die Reihenfolge Ihrer Pr&auml;ferenzen widerspiegelt.},
	ERRSTR_E19a => qq{Fehler: Sie haben das gleiche Ranking f&uuml;r verschiedene Punkte angegeben.},
	ERRSTR_E1a => qq{Wir w&uuml;rden es sehr sch&auml;tzen, wenn Sie hier Ihre Kommentare niederschreiben.},
	ERRSTR_E20a => qq{Fehler: Sie k&ouml;nnen nicht einen Punkt doppelt w&auml;hlen.},
	ERRSTR_E21a => qq{Ung&uuml;ltige Frage &#150; bitte kontaktieren Sie den Support.},
	ERRSTR_E22a => qq{Sie haben &#39;anders&#39; gew&auml;hlen, bitte welche schreiben.},
	ERRSTR_E22b => qq{Sie haben &#39;Andere&#39; ausgew&auml;hlt, bitte geben Sie an, worum es sich dabei handelt},
	ERRSTR_E22c => qq{Sie haben &#39;Andere&#39; ausgew&auml;hlt, bitte geben Sie f&uuml;r %s an, worum es sich dabei handelt},
	ERRSTR_E22d => qq{Sie haben eine Eingabe gemacht, ohne &#39;Andere&#39; auszuw&auml;hlen. Bitte tun Sie dies jetzt},
	ERRSTR_E22e => qq{Sie haben der Antwort &#39;Andere&#39; einen Wert zugewiesen, bitte geben Sie an, worum es sich dabei handelt (oder l&ouml;schen Sie die Antwort)},
	ERRSTR_E22f => qq{Sie haben unter &#39;Andere&#39; eine Antwort angegeben, bitte ordnen Sie ihr einen Wert zu (oder l&ouml;schen Sie sie)},
	ERRSTR_E23a => qq{Bitte f&uuml;llen Sie mindestens %d Antworten aus.},
	ERRSTR_E23b => qq{Bitte geben Sie mindestens eine Antwort an},
	ERRSTR_E24 => qq{M&ouml;glicherweise innerhalb von zw&ouml;lf Monaten, bitte fragen Sie ...},
	ERRSTR_E25 => qq{Fehler: Der Befragte ist erst },
	ERRSTR_E26 => qq{Bitte w&auml;hlen Sie mindestens eine Antwortm&ouml;glichkeit f&uuml;r %s aus},
	ERRSTR_E27a => qq{Dieses Geburtsdatum (},
	ERRSTR_E27b => qq{) ist f&uuml;r einen },
	ERRSTR_E27c => qq{ -J&auml;hrigen unm&ouml;glich!\n Vielleicht sollte es wie folgt lauten: },
	ERRSTR_E27d => qq{?},
	ERRSTR_E28 => qq{Es tut mir leid, macht es keinen Sinn, zu verweigern und NICHT zur gleichen Zeit WISSEN},
	ERRSTR_E29 => qq{Bitte ziehen Sie alle Punkte in die Box &#39;Ihre Auswahl&#39;.},
	ERRSTR_E29a => qq{Bitte ziehen Sie},
	ERRSTR_E29b => qq{Punkte in die Box &#39;Ihre Auswahl&#39;. },
	ERRSTR_E2a => qq{Bitte f&uuml;llen Sie alle Antworten aus.},
	ERRSTR_E2b => qq{Bitte geben Sie mindestens %d Antwort(en)},
	ERRSTR_E30a => qq{In der Box &#39;Ihre Auswahl&#39; sollten },
	ERRSTR_E30b => qq{sich nur befinden.},
	ERRSTR_E3a => qq{Die Antwort &#39;%s&#39; ist keine Zahl},
	ERRSTR_E4a => qq{Die Antwort %d ist zu niedrig, sie sollte mindestens %d betragen},
	ERRSTR_E5a => qq{Die Antwort %d ist zu hoch, sie sollte h&ouml;chstens %d betragen},
	ERRSTR_E6a => qq{Vorsicht, diese Antwort macht keinen Sinn (die Antwort sollte gr&ouml;&szlig;er/gleich %d sein)},
	ERRSTR_E7a => qq{Sie k&ouml;nnen mindestens %d Punkte w&auml;hlen.},
	ERRSTR_E7b => qq{Sie k&ouml;nnen mindestens %d oder die %s Punkte w&auml;hlen.},
	ERRSTR_E8a => qq{Vorsicht, diese Antwort macht keinen Sinn (Antwort sollte kleiner/gleich %d sein)},
	ERRSTR_E9a => qq{Vorsicht, diese Zahlen m&uuml;ssen eine Summe von %d ergeben (Sie haben %d)},
	ERRSTR_I1 => qq{GEBEN SIE EINE GANZE ZAHL EIN.},
	ERRSTR_I2 => qq{W&Auml;HLEN SIE SO VIELE PUNKTE, WIE ZUTREFFEN},
	ERRSTR_I3 => qq{W&Auml;HLEN SIE NUR EINEN PUNKT},
	ERRSTR_I30 => qq{SCHLEPPEN SIE DEN ZEIGER ENTLANG DER SKALA, UM IHRE BEWERTUNG ZUR VERF&Uuml;GUNG ZU STELLEN},
	ERRSTR_I4 => qq{BITTE GEBEN SIE IHRE ANTWORT EIN.},
	ERRSTR_I5 => qq{GEBEN SIE PROZENTZAHLEN EIN, DIE SUMME MUSS 100% BETRAGEN.},
	ERRSTR_I6 => qq{GEBEN SIE DEN BETRAG IN GANZEN ZAHLEN IN DOLLAR / DM / EURO EIN.},
	ERRSTR_I7 => qq{UNG&Uuml;LTIGE FRAGE},
	ERRSTR_I8 => qq{W&Auml;HLEN SIE EINEN PUNKT PRO REIHE},
	ERRSTR_I9 => qq{W&Auml;HLEN SIE EIN EINZELTEIL IN JEDER SPALTE F&Uuml;R JEDE REIHE VOR},
	TXT_AGE => qq{Alter},
	TXT_AGE_ONS => qq{Manifestationsalter},
	TXT_AGE_REC => qq{Alter der Rezession},
	TXT_AVAIL => qq{Auswahlm&ouml;glichkeiten},
	TXT_COUNT => qq{Z&auml;hl},
	TXT_DAY => qq{Tag},
	TXT_HOWLONG => qq{Wie lang geleden},
	TXT_ITEM => qq{Sache},
	TXT_JS1 => qq{Wir haben ein Problem!},
	TXT_JS2 => qq{Ihr Browser unterst&uuml;tzt kein Javascript aktiviert haben. Dies ist ein Problem, weil die Umfrage nutzt fortschrittliche Funktionen, die HTML Javascript eingeschaltet sein m&uuml;ssen.},
	TXT_JS3 => qq{Wie man es beheben},
	TXT_JS4 => qq{Sie k&ouml;nnen entweder einen anderen Browser, der Javascript aktiviert hat, oder sich Anleitungen, um es einzuschalten hier:},
	TXT_JS5 => qq{Woher wei&szlig; ich, wenn ich es behoben haben?},
	TXT_JS6 => qq{Sobald Sie haben es sich schon, komm zur&uuml;ck zu dieser Seite und aktualisieren sie. Wenn diese Fehlermeldung nicht angezeigt wird, ist das Problem behoben.},
	TXT_MONTH => qq{Monat},
	TXT_NOTES => qq{Anmerkungen	:},
	TXT_NOTHING => qq{Keine},
	TXT_OTHER_SPEC => qq{Anderen (bitte spezifieren:)},
	TXT_QS => qq{Q&#39;s},
	TXT_TICK => qq{Zecke},
	TXT_YEAR => qq{Jahr},
	TXT_YOURS => qq{Ihre Auswahl},
);
# Default Prompts
#
@def_instr = 	(
		"Invalid question type - please contact support",
		"($sysmsg{ERRSTR_I1})",				# Number
		"($sysmsg{ERRSTR_I2})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I4})",
		"($sysmsg{ERRSTR_I5})",
		"",
		"",
		"($sysmsg{ERRSTR_I6})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I7})",
		"($sysmsg{ERRSTR_I3})",
		"",
		"($sysmsg{ERRSTR_I8})",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",										# Spares are defensive
		"($sysmsg{ERRSTR_I30})",
	);

#
# Even if you have to edit this file, please leave this soldier on the last line
#
1;
