#!/usr/bin/perl
## $Id: strings-pt.pl,v 1.5 2011-09-09 10:54:54 triton Exp $
#
# GENERATED FILE: DO NOT EDIT ! See /cgi-adm/xlate.msg.pl to edit/update
#
# CONTAINS LANGUAGE STRINGS FOR ERROR MESSAGES
#
our %sysmsg = (
	BTN_BACK => qq{Voltar},
	BTN_DK => qq{N&atilde;o sei},
	BTN_NEXT => qq{Pr&oacute;ximo},
	BTN_REFUSED => qq{Recusado},
	BTN_SUBMITTING => qq{Apresentando},
	ERRSTR_E10a => qq{Voc&ecirc; selecionou tanto %s como %s...Decida-se!},
	ERRSTR_E11a => qq{Voc&ecirc; n&atilde;o deve selecionar mais de %d itens},
	ERRSTR_E11b => qq{N&atilde;o n&atilde;o deve selecionar mais de um item},
	ERRSTR_E12a => qq{Favor selecionar um dos itens da lista},
	ERRSTR_E13a => qq{Favor selecionar um da lista suspensa},
	ERRSTR_E14a => qq{As soma das percentagens deve ser 100 (voc&ecirc; tem %d% at&eacute; agora)},
	ERRSTR_E15a => qq{Favor dar respostas completas para [%s]},
	ERRSTR_E15b => qq{Favor selecionar c&oacute;digo de frequ&ecirc;ncia para %s},
	ERRSTR_E15c => qq{Favor selecionar pelo menos %d respostas},
	ERRSTR_E15d => qq{Favor selecionar pelo menos %d respostas para %s},
	ERRSTR_E16a => qq{Erro: escolha um item de cada linha},
	ERRSTR_E17a => qq{Favor selecionar da lista acima},
	ERRSTR_E18a => qq{Error: Please choose a different number for each place that reflects your order of preference.},
	ERRSTR_E19a => qq{Erro: voc&ecirc; classificou itens m&uacute;ltiplos da mesma maneira},
	ERRSTR_E1a => qq{Gostar&iacute;amos que dissesse algo aqui},
	ERRSTR_E20a => qq{Erro: n&atilde;o pode escolher o mesmo duas vezes},
	ERRSTR_E21a => qq{Tipo inv&aacute;lido de pergunta - contatar o suporte},
	ERRSTR_E22a => qq{Voc&ecirc; selecionou &quot;outro&quot;, diga qual &eacute; o outro},
	ERRSTR_E22b => qq{Voc&ecirc; selecionou &quot;outro&quot;, diga qual &eacute; o outro},
	ERRSTR_E22c => qq{You selected &#39;other&#39;, please tell me what the other thing is for %s},
	ERRSTR_E22d => qq{You entered something, but did not select &#39;other&#39;, please correct it},
	ERRSTR_E22e => qq{You rated &#39;other&#39;, please specify it (or erase the response)},
	ERRSTR_E22f => qq{You specified the &#39;other&#39;, please rate it (or erase the response)},
	ERRSTR_E23a => qq{Favor preencher pelos menos %d das respostas},
	ERRSTR_E23b => qq{Favor preencher pelos menos uma resposta},
	ERRSTR_E24 => qq{	Possivelmente em 12 meses - favor perguntar. . .},
	ERRSTR_E25 => qq{	Erro: Respondente &eacute; &uacute;nico},
	ERRSTR_E26 => qq{	Favor escolher pelo menos uma para %s},
	ERRSTR_E27a => qq{Este ano de nascimento ( },
	ERRSTR_E27b => qq{) n&atilde;o parece poss&iacute;vel para algu&eacute;m},
	ERRSTR_E27c => qq{de um ano \n Talvez seja },
	ERRSTR_E27d => qq{?},
	ERRSTR_E28 => qq{N&atilde;o faz sentido selecionar RECUSAR e N&Atilde;O SEI ao mesmo tempo},
	ERRSTR_E29 => qq{Favor arrastar todos os itens para a caixa das &#39;Suas sele&ccedil;&otilde;es&#39;},
	ERRSTR_E29a => qq{Favor arrastar os itens de},
	ERRSTR_E29b => qq{para a caixa das &#39;Suas sele&ccedil;&otilde;es&#39;},
	ERRSTR_E2a => qq{Preencha com todas as respostas},
	ERRSTR_E2b => qq{Favor preencher pelos menos % das respostas},
	ERRSTR_E30a => qq{Voc&ecirc; dever&aacute; ter apenas itens},
	ERRSTR_E30b => qq{na caixa das &#39;Suas sele&ccedil;&otilde;es&#39;.},
	ERRSTR_E3a => qq{A resposta %s n&atilde;o &eacute; um n&uacute;mero},
	ERRSTR_E4a => qq{A resposta %d &eacute; muito baixa, deveria ser pelo menos %d},
	ERRSTR_E5a => qq{A resposta %d &eacute; muito alta, n&atilde;o deveria ser mais que %d},
	ERRSTR_E6a => qq{Desculpe, esta resposta n&atilde;o faz sentido (o n&uacute;mero deve ser maior que, ou igual a %d)},
	ERRSTR_E7a => qq{Voc&ecirc; deve selecionar pelo menos %d itens},
	ERRSTR_E7b => qq{Voc&ecirc; deve selecionar pelos menos %d ou a op&ccedil;&atilde;o %s},
	ERRSTR_E8a => qq{Desculpe, esta resposta n&atilde;o faz sentido (o n&uacute;mero deve ser menor que, ou igual a %d)},
	ERRSTR_E9a => qq{A soma destes n&uacute;meros deve ser %d (voc&ecirc; tem %d)},
	ERRSTR_I1 => qq{ENTRE COM UM N&Uacute;MERO REDONDO},
	ERRSTR_I2 => qq{SELECIONE TODOS QUE SE APLIQUEM},
	ERRSTR_I3 => qq{SELECIONE SOMENTE UM},
	ERRSTR_I30 => qq{ARRASTE O INDICADOR PELA ESCALA PARA CLASSIFICAR},
	ERRSTR_I4 => qq{FAVOR DIGITAR SUA RESPOSTA},
	ERRSTR_I5 => qq{ENTRE COM AS PERCENTAGENS, O TOTAL DEVE SER 100%},
	ERRSTR_I6 => qq{ENTRE COM A QUANTIA EM D&Oacute;LARES REDONDOS},
	ERRSTR_I7 => qq{TIPO INV&Aacute;LIDO DE PERGUNTA},
	ERRSTR_I8 => qq{SELECIONE UM ITEM POR LINHA},
	ERRSTR_I9 => qq{SELECIONE UM ITEM EM CADA COLUNA PARA CADA LINHA},
	TXT_AGE => qq{Idade},
	TXT_AGE_ONS => qq{Idade},
	TXT_AGE_REC => qq{Idade},
	TXT_AVAIL => qq{Sele&ccedil;&otilde;es dispon&iacute;veis},
	TXT_COUNT => qq{Contar},
	TXT_DAY => qq{Dia},
	TXT_HOWLONG => qq{H&aacute; quanto tempo},
	TXT_ITEM => qq{Item},
	TXT_MONTH => qq{M&ecirc;s},
	TXT_NOTES => qq{Notas:},
	TXT_NOTHING => qq{Nada},
	TXT_OTHER_SPEC => qq{Outro (especique:)},
	TXT_QS => qq{P&#39;s},
	TXT_TICK => qq{Marcar:},
	TXT_YEAR => qq{Ano},
	TXT_YOURS => qq{Suas sele&ccedil;&otilde;es},
);
# Default Prompts
#
@def_instr = 	(
		"Invalid question type - please contact support",
		"($sysmsg{ERRSTR_I1})",				# Number
		"($sysmsg{ERRSTR_I2})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I4})",
		"($sysmsg{ERRSTR_I5})",
		"",
		"",
		"($sysmsg{ERRSTR_I6})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I7})",
		"($sysmsg{ERRSTR_I3})",
		"",
		"($sysmsg{ERRSTR_I8})",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",										# Spares are defensive
		"($sysmsg{ERRSTR_I30})",
	);

#
# Even if you have to edit this file, please leave this soldier on the last line
#
1;
