#!/usr/bin/perl
## $Id: xlate.msg.pl,v 1.3 2011-09-14 13:33:56 triton Exp  GENERATED FILE: DO NOT EDIT ! See /cgi-adm/xlate.msg.pl to edit/update
#
# CONTAINS LANGUAGE STRINGS FOR ERROR MESSAGES
#
our %sysmsg = (
	BTN_BACK => qq{Indietro},
	BTN_DK => qq{Non so},
	BTN_NEXT => qq{Avanti},
	BTN_REFUSED => qq{Ha rifiutato},
	BTN_SUBMITTING => qq{Invio...},
	ERRSTR_E10a => qq{Hai selezionato altri articoli insieme ad %s. Cambia la risposta},
	ERRSTR_E11a => qq{Non puoi selezionare pi&ugrave; di %d voci},
	ERRSTR_E11b => qq{&Egrave; necessario selezionare un solo elemento},
	ERRSTR_E12a => qq{Seleziona una delle voci nella lista},
	ERRSTR_E13a => qq{Seleziona una delle voci della lista qui sotto},
	ERRSTR_E14a => qq{Le percentuali devono raggiungere il 100 (hai %d%)},
	ERRSTR_E15a => qq{Rispondi alle domande per [%s]},
	ERRSTR_E15b => qq{Si prega di selezionare il codice attualit&agrave; per %s},
	ERRSTR_E15c => qq{Si prega di selezionare almeno %d risposte},
	ERRSTR_E15d => qq{Si prega di selezionare almeno %d risposte alla domanda su %s},
	ERRSTR_E16a => qq{Errore: scegli una voce da ogni riga},
	ERRSTR_E17a => qq{Scegli una voce dalla lista qui sopra},
	ERRSTR_E18a => qq{Errore: scegliere un numero diverso per ciascuna posizione, in modo da rispecchiare l&#39;ordine di preferenza},
	ERRSTR_E19a => qq{Errore: hai messo pi&ugrave; voci nella stessa riga},
	ERRSTR_E1a => qq{Scrivi qualcosa qui},
	ERRSTR_E20a => qq{Errore: non puoi scegliere la stessa voce due volte},
	ERRSTR_E21a => qq{(Tipo di) domanda non valida - contatta il supporto tecnico},
	ERRSTR_E22a => qq{Hai selezionato &#39;altro&#39;, mi dica quello che l&#39;altra cosa &egrave;},
	ERRSTR_E22b => qq{Hai selezionato &#39;altro&#39;, mi dica quello che l&#39;altra cosa &egrave;},
	ERRSTR_E22c => qq{Hai selezionato &#39;altro&#39;, mi dica quello che l&#39;altra cosa &egrave; per %s},
	ERRSTR_E22d => qq{Hai inserito qualcosa, ma non avete selezionato &#39;altri&#39;, si prega di correggere},
	ERRSTR_E22e => qq{Hai votato &#39;altro&#39;, si prega di specificarlo (o cancellare la risposta)},
	ERRSTR_E22f => qq{&Egrave; stato specificato il &#39;altri&#39;, si prega di votarla (o cancellare la risposta)},
	ERRSTR_E23a => qq{Si prega di inserire almeno %d risposte},
	ERRSTR_E23b => qq{Si prega di compilare almeno una risposta},
	ERRSTR_E24 => qq{Possibilmente entro 12 mesi - si prega di chiedere ...},
	ERRSTR_E25 => qq{Resistente &egrave; a soli },
	ERRSTR_E26 => qq{Seleziona almeno una per %s},
	ERRSTR_E27a => qq{Questo anno di nascita (},
	ERRSTR_E27b => qq{) non sembra possibile per un anno },
	ERRSTR_E27c => qq{vecchio. Forse dovrebbe essere},
	ERRSTR_E27d => qq{?},
	ERRSTR_E28 => qq{Mi dispiace, non ha senso RIFIUTARE e NON SANNO al tempo stesso},
	ERRSTR_E29 => qq{Trascinare tutte le voci dall&#39;altra parte, nel riquadro &#39;Le sue selezioni&#39;},
	ERRSTR_E29a => qq{Trascinare },
	ERRSTR_E29b => qq{voci dall&#39;altra parte, nel riquadro &#39;Le sue selezioni&#39;},
	ERRSTR_E2a => qq{Compila tutte le risposte},
	ERRSTR_E2b => qq{Si prega di compilare almeno 4 risposta (s)},
	ERRSTR_E30a => qq{Nel riquadro &#39;Le sue selezioni&#39;},
	ERRSTR_E30b => qq{devono esserci solo voci},
	ERRSTR_E3a => qq{La risposta %s non &egrave; un numero},
	ERRSTR_E4a => qq{La risposta %d &egrave; troppo corta, deve di essere almeno %d},
	ERRSTR_E5a => qq{La risposta %d &egrave; troppo lunga, non deve superare %d},
	ERRSTR_E6a => qq{Questa risposta non ha senso (il numero deve essere maggiore o uguale a %d)},
	ERRSTR_E7a => qq{Deve selezionare almeno %s voce},
	ERRSTR_E7b => qq{&Egrave; necessario selezionare almeno %d o selezionare il &#39;%s&#39; opzione},
	ERRSTR_E8a => qq{Questa risposta non ha senso (il numero deve essere maggiore o uguale a %d)},
	ERRSTR_E9a => qq{Questi numeri devono raggiungere la somma di %d (hai %d)},
	ERRSTR_I1 => qq{Digita un numero intero},
	ERRSTR_I2 => qq{Seleziona tutte le voci che desideri},
	ERRSTR_I3 => qq{SELEZIONA UNA SOLA RISPOSTA},
	ERRSTR_I30 => qq{Trascinare il puntatore lungo la scala A FORNIRE IL VOSTRO VOTO},
	ERRSTR_I4 => qq{DIGITA LA TUA RISPOSTA},
	ERRSTR_I5 => qq{IMMETTI LE PERCENTUALI, IL TOTALE DEVE ESSERE PARI AL 100%},
	ERRSTR_I6 => qq{DIGITA LA CIFRA IN DOLLARI},
	ERRSTR_I7 => qq{(Tipo di) domanda non valida},
	ERRSTR_I8 => qq{SELEZIONA UNA RISPOSTA PER RIGA},
	ERRSTR_I9 => qq{SELEZIONA UNA RISPOSTA IN OGNI COLONNA PER OGNI RIGA},
	TXT_AGE => qq{et&agrave;},
	TXT_AGE_ONS => qq{Et&agrave; di esordio},
	TXT_AGE_REC => qq{Et&agrave; di recessione},
	TXT_AVAIL => qq{selezioni disponibili},
	TXT_COUNT => qq{Contare},
	TXT_DAY => qq{Giorno},
	TXT_HOWLONG => qq{Quanto tempo fa},
	TXT_ITEM => qq{Voce},
	TXT_JS1 => qq{Abbiamo un problema!},
	TXT_JS2 => qq{Il tuo browser non ha i javascript abilitati. Questo &egrave; un problema perch&eacute; l&#39;indagine utilizza le funzioni avanzate di HTML che richiedono Javascript per essere acceso.},
	TXT_JS3 => qq{Come risolvere il problema},
	TXT_JS4 => qq{&Egrave; possibile utilizzare un altro browser che ha Javascript abilitato, o ottenere istruzioni su come accenderlo qui:},
	TXT_JS5 => qq{Come faccio a sapere quando l&#39;ho fisso?},
	TXT_JS6 => qq{Una volta accesa, tornare a questa pagina e aggiornarla. Se questo messaggio di errore non viene visualizzato, il problema &egrave; risolto.},
	TXT_MONTH => qq{Mese},
	TXT_NOTES => qq{Note},
	TXT_NOTHING => qq{Niente},
	TXT_OTHER_SPEC => qq{Altro (specificare)},
	TXT_QS => qq{Q&#39;s},
	TXT_TICK => qq{Zecca},
	TXT_YEAR => qq{Anno},
	TXT_YOURS => qq{le selezioni},
);
# Default Prompts
#
@def_instr = 	(
		"Invalid question type - please contact support",
		"($sysmsg{ERRSTR_I1})",				# Number
		"($sysmsg{ERRSTR_I2})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I4})",
		"($sysmsg{ERRSTR_I5})",
		"",
		"",
		"($sysmsg{ERRSTR_I6})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I7})",
		"($sysmsg{ERRSTR_I3})",
		"",
		"($sysmsg{ERRSTR_I8})",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",										# Spares are defensive
		"($sysmsg{ERRSTR_I30})",
	);

#
# Even if you have to edit this file, please leave this soldier on the last line
#
1;
