#!/usr/bin/perl
## $Id: xlate.msg.pl,v 1.3 2011-09-14 13:33:56 triton Exp  GENERATED FILE: DO NOT EDIT ! See /cgi-adm/xlate.msg.pl to edit/update
#
# CONTAINS LANGUAGE STRINGS FOR ERROR MESSAGES
#
our %sysmsg = (
	BTN_BACK => qq{De nuevo},
	BTN_DK => qq{No lo s&eacute;},
	BTN_NEXT => qq{Siguiente},
	BTN_REFUSED => qq{Se neg&oacute;},
	BTN_SUBMITTING => qq{La transmisi&oacute;n de ...},
	ERRSTR_E10a => qq{Has elegido %s as&iacute; como %s respuestas a la vez...&iexcl;Dec&iacute;dete, por favor!},
	ERRSTR_E11a => qq{No puedes elegir m&aacute;s de %d respuestas},
	ERRSTR_E11b => qq{Usted debe seleccionar no m&aacute;s de un elemento},
	ERRSTR_E12a => qq{Elige una de las respuestas de la lista},
	ERRSTR_E13a => qq{De la lista desplegable, elige una},
	ERRSTR_E14a => qq{Los porcentajes deben sumar 100 (hasta ahora los tuyos suman %d%)},
	ERRSTR_E15a => qq{Completa todas las respuestas a [%s]},
	ERRSTR_E15b => qq{Por favor, seleccione el c&oacute;digo de experiencia reciente requeridas para %s},
	ERRSTR_E15c => qq{Por favor, seleccione al menos %d respuestas},
	ERRSTR_E15d => qq{Por favor, seleccione al menos %d respuestas para %s},
	ERRSTR_E16a => qq{Error: elige por favor solo una respuesta de cada fila},
	ERRSTR_E17a => qq{Elige una respuesta de la lista de arriba},
	ERRSTR_E18a => qq{Error: Por favor seleccione un n&uacute;mero diferente para cada lugar que refleja su &oacute;rden de preferencia.},
	ERRSTR_E19a => qq{Error: has dado la misma puntuaci&oacute;n a m&uacute;ltiples preguntas},
	ERRSTR_E1a => qq{Te agradecer&iacute;amos que a&ntilde;adieras tus comentarios aqu&iacute; },
	ERRSTR_E20a => qq{Error: no puedes elegir lo mismo dos veces},
	ERRSTR_E21a => qq{Tipo incorrecto de pregunta - ponte en contacto con el servicio de asistencia},
	ERRSTR_E22a => qq{Ha seleccionado &quot;otro&quot;, por favor, dime qu&eacute; otra cosa es},
	ERRSTR_E22b => qq{Ha seleccionado &quot;otro&quot;, por favor, dime qu&eacute; otra cosa es},
	ERRSTR_E22c => qq{Ha seleccionado &quot;otro&quot;, por favor, dime qu&eacute; otra cosa es para %s},
	ERRSTR_E22d => qq{Ha introducido algo, pero no selecciona &quot;otros&quot;, por favor, corrija},
	ERRSTR_E22e => qq{Usted ha calificado &quot;otros&quot;, especifique el mismo (o borrar la respuesta)},
	ERRSTR_E22f => qq{Se ha especificado el &quot;otro&quot;, por favor eval&uacute;e el mismo (o borrar la respuesta)},
	ERRSTR_E23a => qq{Por favor, rellene al menos %d respuestas},
	ERRSTR_E23b => qq{Por favor, rellene al menos una respuesta},
	ERRSTR_E24 => qq{Posiblemente dentro de 12 meses - por favor preguntar ...},
	ERRSTR_E25 => qq{Error: Demandado es de s&oacute;lo},
	ERRSTR_E26 => qq{Por favor, seleccione al menos una de},
	ERRSTR_E27a => qq{Este a&ntilde;o de nacimiento (},
	ERRSTR_E27b => qq{) no parece posible que un},
	ERRSTR_E27c => qq{a&ntilde;os de edad! Tal vez deber&iacute;a ser 2001},
	ERRSTR_E27d => qq{?},
	ERRSTR_E28 => qq{I&#39;m sorry, it doesn&#39;t make sense to REFUSE and DON&#39;T KNOW at the same time},
	ERRSTR_E29 => qq{Por favor arrastre todos los items hasta el &#39;cuadro de sus selecciones&#39;},
	ERRSTR_E29a => qq{Por favor arrastre },
	ERRSTR_E29b => qq{items hasta el &#39;cuadro de sus selecciones&#39;},
	ERRSTR_E2a => qq{Por favor, responde todas las preguntas},
	ERRSTR_E2b => qq{Por favor, rellene al menos %d respuesta},
	ERRSTR_E30a => qq{Debe tener solamente },
	ERRSTR_E30b => qq{items en el &#39;cuadro de sus selecciones&#39;},
	ERRSTR_E3a => qq{No se puede responder %s a la pregunta con un n&uacute;mero},
	ERRSTR_E4a => qq{La puntuaci&oacute;n %d a la pregunta es demasiado baja, deber&iacute;a ser al menos %d},
	ERRSTR_E5a => qq{La puntuaci&oacute;n %d a la pregunta es demasiado alta, no deber&iacute;a ser superior a %d},
	ERRSTR_E6a => qq{Lo siento, pero esta respuesta no tiene sentido (el n&uacute;mero deber&iacute;a ser superior a %d)},
	ERRSTR_E7a => qq{Usted debe seleccionar por lo menos %d art&iacute;culo},
	ERRSTR_E7b => qq{Debe seleccionar por lo menos %d o seleccione la opci&oacute;n %s},
	ERRSTR_E8a => qq{Lo siento, pero esta respuesta no tiene sentido (el n&uacute;mero deber&iacute;a ser superior a %d)},
	ERRSTR_E9a => qq{Lo siento, pero estos n&uacute;meros deben sumar %d  (t&uacute; tienes %d)},
	ERRSTR_I1 => qq{Escribe un n&uacute;mero entero},
	ERRSTR_I2 => qq{ELIGE TANTAS RESPUESTAS COMO CORRESPONDAN },
	ERRSTR_I3 => qq{ELIGE SOLO UNA},
	ERRSTR_I30 => qq{Arrastre el puntero en la escala para proporcionar a su RATING},
	ERRSTR_I4 => qq{POR FAVOR, ESCRIBE TU RESPUESTA},
	ERRSTR_I5 => qq{ESCRIBE PORCENTAJES, EL TOTAL DEBE SUMAR 100%},
	ERRSTR_I6 => qq{ESCRIBE LA CANTIDAD EN N&Uacute;MEROS REDONDOS},
	ERRSTR_I7 => qq{Tipo incorrecto de pregunta },
	ERRSTR_I8 => qq{ELIGE UNA RESPUESTA DE CADA FILA},
	ERRSTR_I9 => qq{SELECCIONAR un elemento en cada columna para cada fila},
	TXT_AGE => qq{Edad},
	TXT_AGE_ONS => qq{Edad de inicio},
	TXT_AGE_REC => qq{Edad recesi&oacute;n},
	TXT_AVAIL => qq{Selecciones disponibles},
	TXT_COUNT => qq{Contar},
	TXT_DAY => qq{Dia},
	TXT_HOWLONG => qq{&iquest;Cu&aacute;nto tiempo hace},
	TXT_ITEM => qq{art&iacute;culo},
	TXT_JS1 => qq{Tenemos un problema!},
	TXT_JS2 => qq{Su navegador no tiene habilitado javascript. Este es un problema porque la encuesta utiliza caracter&iacute;sticas avanzadas de HTML que requieren que Javascript est&eacute; activado.},
	TXT_JS3 => qq{&iquest;C&oacute;mo arreglarlo?},
	TXT_JS4 => qq{Puede utilizar un navegador diferente que tiene Javascript habilitado, o recibir instrucciones sobre c&oacute;mo activarlo aqu&iacute;:},
	TXT_JS5 => qq{&iquest;C&oacute;mo s&eacute; que voy a arreglar?},
	TXT_JS6 => qq{Una vez que haya encendido, volver&aacute; a esta p&aacute;gina y actualizarla. Si este mensaje de error no aparece, el problema est&aacute; resuelto.},
	TXT_MONTH => qq{Mes},
	TXT_NOTES => qq{Notas},
	TXT_NOTHING => qq{Ninguna},
	TXT_OTHER_SPEC => qq{Otro (especificar)},
	TXT_QS => qq{Q&#39;s},
	TXT_TICK => qq{Marque},
	TXT_YEAR => qq{N&ntilde;o},
	TXT_YOURS => qq{Sus selecciones},
);
# Default Prompts
#
@def_instr = 	(
		"Invalid question type - please contact support",
		"($sysmsg{ERRSTR_I1})",				# Number
		"($sysmsg{ERRSTR_I2})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I4})",
		"($sysmsg{ERRSTR_I5})",
		"",
		"",
		"($sysmsg{ERRSTR_I6})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I7})",
		"($sysmsg{ERRSTR_I3})",
		"",
		"($sysmsg{ERRSTR_I8})",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",										# Spares are defensive
		"($sysmsg{ERRSTR_I30})",
	);

#
# Even if you have to edit this file, please leave this soldier on the last line
#
1;
