#!/usr/bin/perl
## $Id: strings-no.pl,v 1.7 2011-09-15 09:49:19 triton Exp $
#
# GENERATED FILE: DO NOT EDIT ! See /cgi-adm/xlate.msg.pl to edit/update
#
# CONTAINS LANGUAGE STRINGS FOR ERROR MESSAGES
#
our %sysmsg = (
	BTN_BACK => qq{Tilbake},
	BTN_DK => qq{Vet ikke},
	BTN_NEXT => qq{Neste},
	BTN_REFUSED => qq{Avsl&aring;tt},
	BTN_SUBMITTING => qq{Sender ...},
	ERRSTR_E10a => qq{Du har valgt %s samt %s ... Vennligst bestem deg!},
	ERRSTR_E11a => qq{Du m&aring; ikke velge mer enn %d objekter},
	ERRSTR_E11b => qq{Du m&aring; ikke velge mer enn ett objekt},
	ERRSTR_E12a => qq{Velg ett av elementene p&aring; listen},
	ERRSTR_E13a => qq{Velg ett fra nedtrekkslisten},
	ERRSTR_E14a => qq{Prosenter m&aring; summere seg til 100 (du har %d% s&aring; langt)},
	ERRSTR_E15a => qq{Fyll ut alle svarene for [%s]},
	ERRSTR_E15b => qq{Velg nyhetskode for %s},
	ERRSTR_E15c => qq{Velg minst %d svar},
	ERRSTR_E15d => qq{Velg minst %d svar for %s},
	ERRSTR_E16a => qq{Feil: m&aring; du gj&oslash;re ett valg fra hver rad},
	ERRSTR_E17a => qq{Foreta et valg fra listen over},
	ERRSTR_E18a => qq{Feil: du m&aring; foreta ett valg fra hver kolonne},
	ERRSTR_E19a => qq{Feil: Du har gitt samme rangering til flere objekter},
	ERRSTR_E1a => qq{Vi ville virkelig satt pris p&aring; om du kunne si noe her  },
	ERRSTR_E20a => qq{Feil: du kan ikke velge det samme to ganger},
	ERRSTR_E21a => qq{Ugyldig type sp&oslash;rsm&aring;l - kontakt kundest&oslash;tte},
	ERRSTR_E22a => qq{Du valgte &quot;annet&quot;, kan du fortelle meg hva den andre tingen er},
	ERRSTR_E22b => qq{Du valgte &quot;annet&quot;, kan du fortelle meg hva den andre tingen er},
	ERRSTR_E22c => qq{Du valgte &quot;annet&quot;, kan du fortelle meg hva den andre tingen er},
	ERRSTR_E22d => qq{Du valgte &quot;annet&quot;, kan du fortelle meg hva den andre tingen er},
	ERRSTR_E22e => qq{Du valgte &quot;annet&quot;, kan du fortelle meg hva den andre tingen er},
	ERRSTR_E22f => qq{Du valgte &quot;annet&quot;, kan du fortelle meg hva den andre tingen er},
	ERRSTR_E23a => qq{Fyll ut minst %d svar},
	ERRSTR_E23b => qq{Fyll ut minst ett svar},
	ERRSTR_E24 => qq{Om mulig innen 12 m&aring;neder - sp&oslash;r ...},
	ERRSTR_E25 => qq{Feil: Respondenten er bare  },
	ERRSTR_E26 => qq{Velg minst ett for %s},
	ERRSTR_E27a => qq{Dette f&oslash;dsels&aring;ret (},
	ERRSTR_E27b => qq{) synes umulig for en  },
	ERRSTR_E27c => qq{  &aring;r gammel!\n Kanskje det skal v&aelig;re  },
	ERRSTR_E27d => qq{?},
	ERRSTR_E28 => qq{Unnskyld, er det ikke fornuftig &aring; NEKTE og ikke vet samtidig},
	ERRSTR_E29 => qq{Vennligst dra alle elementer p&aring; tvers til &quot;Dine valg&quot; boksen},
	ERRSTR_E29a => qq{Vennligst dra},
	ERRSTR_E29b => qq{elementer p&aring; tvers til &quot;Dine valg&quot; boksen},
	ERRSTR_E2a => qq{Vennligst besvar alle sp&oslash;rsm&aring;lene},
	ERRSTR_E2b => qq{Vennligst fyll ut minst %d svar},
	ERRSTR_E30a => qq{Du b&oslash;r bare ha},
	ERRSTR_E30b => qq{elementer i &quot;Dine valg&quot; boksen},
	ERRSTR_E3a => qq{Svaret %s er ikke et tall},
	ERRSTR_E4a => qq{Svaret %d er for lavt, det b&oslash;r v&aelig;re minst %d},
	ERRSTR_E5a => qq{Svaret %d er for h&oslash;yt, det b&oslash;r ikke v&aelig;re mer enn %d},
	ERRSTR_E6a => qq{Beklager, dette svaret gir ikke mening (tallet m&aring; v&aelig;re st&oslash;rre enn eller lik %d)},
	ERRSTR_E7a => qq{Du m&aring; velge minst %d objekter},
	ERRSTR_E7b => qq{Du m&aring; velge minst %d eller velge %s-alternativet},
	ERRSTR_E8a => qq{Beklager, dette svaret gir ikke mening (tallet m&aring; v&aelig;re mindre enn eller lik %d)},
	ERRSTR_E9a => qq{Beklager, disse tallene m&aring; bel&oslash;pe seg til %d (du har %d)},
	ERRSTR_I1 => qq{ANGI ET HELT TALL},
	ERRSTR_I2 => qq{VELG S&Aring; MANGE SOM PASSER},
	ERRSTR_I3 => qq{VELG BARE &Eacute;N},
	ERRSTR_I30 => qq{DRA PEKEREN LANGS SKALAEN FOR &Aring; GI DIN VURDERING},
	ERRSTR_I4 => qq{VENNLIGST SKRIV INN SVARET DITT},
	ERRSTR_I5 => qq{ANGI PROSENTER, M&Aring; SUMMERE SEG TIL 100 %},
	ERRSTR_I6 => qq{ANGI BEL&Oslash;P I HELE KRONER},
	ERRSTR_I7 => qq{UGYLDIG SP&Oslash;RSM&Aring;LSTYPE},
	ERRSTR_I8 => qq{VELG ETT OBJEKT PER RAD},
	ERRSTR_I9 => qq{VELG ETT OBJEKT I HVER KOLONNE PER RAD},
	TXT_AGE => qq{Alder},
	TXT_AGE_ONS => qq{Alder ons.},
	TXT_AGE_REC => qq{Alder reg.},
	TXT_AVAIL => qq{tilgjengelige valg},
	TXT_COUNT => qq{Sum},
	TXT_DAY => qq{Dag},
	TXT_HOWLONG => qq{Hvor lenge siden},
	TXT_ITEM => qq{Objekt},
	TXT_JS1 => qq{Vi har et problem!},
	TXT_JS2 => qq{Nettleseren din ikke har javascript aktivert. Dette er et problem fordi unders&oslash;kelsen bruker avanserte HTML-funksjoner som krever Javascript for &aring; bli sl&aring;tt p&aring;.},
	TXT_JS3 => qq{Hvordan fikse det},
	TXT_JS4 => qq{Du kan enten bruke en annen nettleser som har Javascript, eller f&aring; instruksjoner om hvordan du sl&aring;r den p&aring; her:},
	TXT_JS5 => qq{Hvordan vet jeg n&aring;r jeg har fikset det?},
	TXT_JS6 => qq{N&aring;r du har sl&aring;tt den p&aring;, kommer tilbake til denne siden og oppdatere den. Hvis denne feilmeldingen ikke vises, er problemet l&oslash;st.},
	TXT_MONTH => qq{M&aring;ned},
	TXT_NOTES => qq{Merknader:},
	TXT_NOTHING => qq{Ingenting},
	TXT_OTHER_SPEC => qq{Annet (spesifiser:)},
	TXT_QS => qq{Spm.},
	TXT_TICK => qq{Kryss av},
	TXT_YEAR => qq{&Aring;r},
	TXT_YOURS => qq{dine valg},
);
# Default Prompts
#
@def_instr = 	(
		"Invalid question type - please contact support",
		"($sysmsg{ERRSTR_I1})",				# Number
		"($sysmsg{ERRSTR_I2})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I4})",
		"($sysmsg{ERRSTR_I5})",
		"",
		"",
		"($sysmsg{ERRSTR_I6})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I7})",
		"($sysmsg{ERRSTR_I3})",
		"",
		"($sysmsg{ERRSTR_I8})",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",										# Spares are defensive
		"($sysmsg{ERRSTR_I30})",
	);

#
# Even if you have to edit this file, please leave this soldier on the last line
#
1;
