#!/usr/bin/perl
## $Id: xlate.msg.pl,v 1.3 2011-09-14 13:33:56 triton Exp  GENERATED FILE: DO NOT EDIT ! See /cgi-adm/xlate.msg.pl to edit/update
#
# CONTAINS LANGUAGE STRINGS FOR ERROR MESSAGES
#
our %sysmsg = (
	BTN_BACK => qq{Takaisin},
	BTN_DK => qq{Ei Tied&auml;},
	BTN_NEXT => qq{Seuraava},
	BTN_REFUSED => qq{Kielt. vast.},
	BTN_SUBMITTING => qq{L&auml;hetet&auml;&auml;n ...},
	ERRSTR_E10a => qq{Olet valinnut muitakin kohtia kuin %s Ole hyv&auml; ja tee p&auml;&auml;t&ouml;ksesi!},
	ERRSTR_E11a => qq{Sinun ei pit&auml;isi valita enemp&auml;&auml; kuin %d kohtaa.},
	ERRSTR_E11b => qq{Sinun ei pit&auml;isi valita enemp&auml;&auml; kuin 1 kohta.},
	ERRSTR_E12a => qq{Ole hyv&auml; ja valitse yksi listan vaihtoehdoista.},
	ERRSTR_E13a => qq{Ole hyv&auml; ja valitse yksi alasvetovalikon vaihtoehdoista.},
	ERRSTR_E14a => qq{Prosenttien summan pit&auml;isi olla 100 (sinulla on %d% t&auml;h&auml;n menness&auml;) },
	ERRSTR_E15a => qq{Ole hyv&auml; ja t&auml;yt&auml; kaikki kysymykset %s:aan},
	ERRSTR_E15b => qq{Ole hyv&auml; ja valitse ik&auml; ensi/ik&auml; viime-koodit %s:lle },
	ERRSTR_E15c => qq{Ole hyv&auml; ja valitse ainakin %d vastausta},
	ERRSTR_E15d => qq{Ole hyv&auml; ja valitse ainakin %d vastausta %s:aan},
	ERRSTR_E16a => qq{Virhe:ole hyv&auml; ja tee yksi valinta kultakin rivilt&auml;},
	ERRSTR_E17a => qq{Ole hyv&auml; ja valitse yll&auml;olevasta listasta},
	ERRSTR_E18a => qq{Virhe:ole hyv&auml; ja tee yksi valinta kultakin sarakkeelta},
	ERRSTR_E19a => qq{Virhe:olet antanut saman pisteytyksen useaan kohtaan},
	ERRSTR_E1a => qq{Olisimme todella kiitollisia, jos voisit sanoa jotain t&auml;h&auml;n},
	ERRSTR_E20a => qq{Virhe:et voi valita samaa kahdesti},
	ERRSTR_E21a => qq{Ep&auml;kelpo kysymystyyppi - ole hyv&auml; ota yhteyt&auml; tukeen},
	ERRSTR_E22a => qq{Valitsit &#39;muu&#39;, kerro mik&auml; se muu asia on},
	ERRSTR_E22b => qq{Valitsit &quot;muu&quot;, kerro mik&auml; se muu asia on},
	ERRSTR_E22c => qq{Valitsit &quot;muu&quot;, kerro minulle, mit&auml; muita asia on XX},
	ERRSTR_E22d => qq{Kirjoitit jotain, mutta eiv&auml;t valita &quot;muut&quot;, korjaa se},
	ERRSTR_E22e => qq{Annoit &quot;muu&quot;, mik&auml; se (tai poistaa vastausta)},
	ERRSTR_E22f => qq{Voit m&auml;&auml;ritelty &quot;muut&quot;, Arvioi se (tai poistaa vastausta)},
	ERRSTR_E23a => qq{Ole hyv&auml; ja t&auml;yt&auml; ainakin %d  vastausta},
	ERRSTR_E23b => qq{Ole hyv&auml; ja t&auml;yt&auml; ainakin 1 vastaus},
	ERRSTR_E24 => qq{Mahdollisesti 12 kuukaudessa - ole hyv&auml; ja kysy....},
	ERRSTR_E25 => qq{Virhe: Vastaaja on ainoastaan },
	ERRSTR_E26 => qq{Valitse ainakin yksi vaihtoehdolle %s},
	ERRSTR_E27a => qq{T&auml;m&auml; syntym&auml;vuosi (},
	ERRSTR_E27b => qq{) ei n&auml;yt&auml; mahdolliselta },
	ERRSTR_E27c => qq{ vuotiaalle!\n Ehk&auml; sen pit&auml;isi olla },
	ERRSTR_E27d => qq{?},
	ERRSTR_E28 => qq{Olen pahoillani, se ei ole j&auml;rkev&auml;&auml; kielt&auml;yty&auml; ja tied&auml; samaan aikaan},
	ERRSTR_E29 => qq{Ole hyv&auml; ja vet&auml;&auml; kaikki kohteet poikki &quot;Valintojasi kentt&auml;&auml;n},
	ERRSTR_E29a => qq{Ole hyv&auml; ja ved&auml;},
	ERRSTR_E29b => qq{items across to &#39;Your selections&#39; box},
	ERRSTR_E2a => qq{ole hyv&auml; ja t&auml;yt&auml; kaikki kohdat},
	ERRSTR_E2b => qq{ole hyv&auml; ja vastaa ainakin %d kysymykseen},
	ERRSTR_E30a => qq{Sinun pit&auml;isi olla vain},
	ERRSTR_E30b => qq{kohteille Valintojasi kentt&auml;&auml;n},
	ERRSTR_E3a => qq{Vastaus %s ei ole numero},
	ERRSTR_E4a => qq{Vastaus %d on liian pieni, pit&auml;isi olla ainakin %d},
	ERRSTR_E5a => qq{Vastaus %d on liian suuri, pit&auml;isi olla enint&auml;&auml;n %d},
	ERRSTR_E6a => qq{Anteeksi, t&auml;m&auml; vastaus ei ole j&auml;rkev&auml; (luvun pit&auml;isi olla suurempi tai yht&auml; kuin %d)},
	ERRSTR_E7a => qq{Sinun t&auml;ytyy valita ainakin %d kohtaa},
	ERRSTR_E7b => qq{Sinun t&auml;ytyy valita ainakin %d tai valita %s vaihtoehto},
	ERRSTR_E8a => qq{Anteeksi, t&auml;m&auml; vastaus ei ole j&auml;rkev&auml; (luvun pit&auml;isi olla pienempi tai yht&auml; kuin %d)},
	ERRSTR_E9a => qq{Anteeksi, n&auml;iden lukujen pit&auml;isi olla yhteens&auml; korkeintaan %d (sinulta tulee %d)},
	ERRSTR_I1 => qq{KIRJOITA KOKONAINEN LUKU},
	ERRSTR_I2 => qq{VALITSE NIIN MONTA KUIN SOVELTUU},
	ERRSTR_I3 => qq{Valitse vain yksi},
	ERRSTR_I30 => qq{Vet&auml;m&auml;ll&auml; osoitinta ALONG skaalata j&auml;rjestelm&auml;&auml; pisteit&auml;},
	ERRSTR_I4 => qq{OLE HYV&Auml; JA KIRJOITA VASTAUKSESI},
	ERRSTR_I5 => qq{KIRJOITA PROSENTTEJA, ON OLTAVA YHTEENS&Auml; 100%},
	ERRSTR_I6 => qq{KIRJOITA M&Auml;&Auml;R&Auml; KOKONAISINA DOLLAREINA (EUROINA) },
	ERRSTR_I7 => qq{EP&Auml;KELPO KYSYMYSTYYPPI},
	ERRSTR_I8 => qq{VALITSE YKSI KOHTA PER RIVI},
	ERRSTR_I9 => qq{VALITSE YKSI KOHTA KULTAKIN SARAKKEELTA JA KULTAKIN RIVILT&Auml;},
	TXT_AGE => qq{Ik&auml;},
	TXT_AGE_ONS => qq{IK&Auml; ENSI},
	TXT_AGE_REC => qq{IK&Auml; VIIME},
	TXT_AVAIL => qq{k&auml;ytett&auml;viss&auml; valinnat},
	TXT_COUNT => qq{Ker&auml;ym&auml; ?},
	TXT_DAY => qq{PV},
	TXT_HOWLONG => qq{Milloin},
	TXT_ITEM => qq{asia},
	TXT_JS1 => qq{Meill&auml; on ongelma!},
	TXT_JS2 => qq{Selaimesi JavaScript ei ole k&auml;yt&ouml;ss&auml;. T&auml;m&auml; on ongelma, koska tutkimuksessa k&auml;ytet&auml;&auml;n edistyksellist&auml; HTML toimintoja, jotka edellytt&auml;v&auml;t JavaScript on p&auml;&auml;ll&auml;.},
	TXT_JS3 => qq{Miten korjata sen},
	TXT_JS4 => qq{Voit joko k&auml;ytt&auml;&auml; toista selainta, joka on JavaScript k&auml;yt&ouml;ss&auml; tai saada ohjeita k&auml;ynnist&auml; se t&auml;st&auml;:},
	TXT_JS5 => qq{Mist&auml; tied&auml;n, milloin olen korjannut sen?},
	TXT_JS6 => qq{Kun olet t&auml;ytt&auml;nyt sen, palaa takaisin t&auml;lle sivulle ja p&auml;ivitt&auml;&auml; sit&auml;. Jos t&auml;m&auml; virheilmoitus ei tule n&auml;kyviin, ongelma on korjattu.},
	TXT_MONTH => qq{kuukausi},
	TXT_NOTES => qq{Huomautuksia},
	TXT_NOTHING => qq{ei mit&auml;&auml;n},
	TXT_OTHER_SPEC => qq{JOS MUUTA, T&Auml;SMENN&Auml;:},
	TXT_QS => qq{Q&#39;s},
	TXT_TICK => qq{Rasti},
	TXT_YEAR => qq{V},
	TXT_YOURS => qq{Omat valinnat},
);
# Default Prompts
#
@def_instr = 	(
		"Invalid question type - please contact support",
		"($sysmsg{ERRSTR_I1})",				# Number
		"($sysmsg{ERRSTR_I2})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I4})",
		"($sysmsg{ERRSTR_I5})",
		"",
		"",
		"($sysmsg{ERRSTR_I6})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I7})",
		"($sysmsg{ERRSTR_I3})",
		"",
		"($sysmsg{ERRSTR_I8})",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",										# Spares are defensive
		"($sysmsg{ERRSTR_I30})",
	);

#
# Even if you have to edit this file, please leave this soldier on the last line
#
1;
