#!/usr/bin/perl
## $Id: xlate.msg.pl,v 1.3 2011-09-14 13:33:56 triton Exp  GENERATED FILE: DO NOT EDIT ! See /cgi-adm/xlate.msg.pl to edit/update
#
# CONTAINS LANGUAGE STRINGS FOR ERROR MESSAGES
#
our %sysmsg = (
	BTN_BACK => qq{Tilbage},
	BTN_DK => qq{Ved ikke},
	BTN_NEXT => qq{N&aelig;ste},
	BTN_REFUSED => qq{Afsl&aring;et},
	BTN_SUBMITTING => qq{Indsender...},
	ERRSTR_E10a => qq{Du har valgt b&aring;de %s og %s&#133;Bliv venligst enig med dig selv!},
	ERRSTR_E11a => qq{Du m&aring; ikke v&aelig;lge flere end %d udsagn},
	ERRSTR_E11b => qq{Du m&aring; ikke v&aelig;lge flere end &eacute;t udsagn},
	ERRSTR_E12a => qq{V&aelig;r venlig at v&aelig;lge &eacute;t af udsagnene p&aring; listen},
	ERRSTR_E13a => qq{V&aelig;r venlig at v&aelig;lge &eacute;t af udsagnene p&aring; rullelisten},
	ERRSTR_E14a => qq{Procentdelene skal give i alt 100 (du er oppe p&aring; %d% indtil videre)},
	ERRSTR_E15a => qq{V&aelig;r venlig at udfylde alle svar til [%s]},
	ERRSTR_E15b => qq{V&aelig;r venlig at v&aelig;lge nyhedskode for %s},
	ERRSTR_E15c => qq{V&aelig;lg venligst mindst %d svar},
	ERRSTR_E15d => qq{V&aelig;lg venligst mindst %d svar til %s},
	ERRSTR_E16a => qq{Fejl: V&aelig;lg venligst &eacute;n fra hver r&aelig;kke},
	ERRSTR_E17a => qq{V&aelig;lg venligst ud fra listen ovenfor},
	ERRSTR_E18a => qq{Fejl: V&aelig;lg venligst &eacute;n fra hver kolonne},
	ERRSTR_E19a => qq{Fejl: Du har givet flere udsagn samme placering},
	ERRSTR_E1a => qq{Vi vil s&aelig;tte stor pris p&aring;, hvis du vil fort&aelig;lle noget her },
	ERRSTR_E20a => qq{Fejl: Du m&aring; ikke v&aelig;lge den samme to gange},
	ERRSTR_E21a => qq{Ugyldig type sp&oslash;rgsm&aring;l - kontakt venligst support},
	ERRSTR_E22a => qq{Du valgte &quot;andet&quot;. Fort&aelig;l mig venligst, hvad dette andet er},
	ERRSTR_E22b => qq{Du valgte &quot;andet&quot;. Fort&aelig;l mig venligst, hvad dette andet er},
	ERRSTR_E22c => qq{Du valgte &quot;andet&quot;. Fort&aelig;l mig venligst, hvad dette andet er %s},
	ERRSTR_E22d => qq{Du valgte &quot;andet&quot;. Fort&aelig;l mig venligst, hvad dette andet er},
	ERRSTR_E22e => qq{Du valgte &quot;andet&quot;. Fort&aelig;l mig venligst, hvad dette andet er},
	ERRSTR_E22f => qq{Du valgte &quot;andet&quot;. Fort&aelig;l mig venligst, hvad dette andet er},
	ERRSTR_E23a => qq{V&aelig;r venlig at besvare mindst %d af sp&oslash;rgsm&aring;lene},
	ERRSTR_E23b => qq{V&aelig;r venlig at besvare mindst &eacute;t af sp&oslash;rgsm&aring;lene},
	ERRSTR_E24 => qq{Sandsynligvis inden for 12 m&aring;neder - sp&oslash;rg venligst},
	ERRSTR_E25 => qq{Fejl: Svarpersonen er kun },
	ERRSTR_E26 => qq{V&aelig;lg venligst &eacute;n til %s},
	ERRSTR_E27a => qq{Dette f&oslash;dsels&aring;r (},
	ERRSTR_E27b => qq{) virker ikke sandsynligt for en },
	ERRSTR_E27c => qq{ &aring;r gammel person!\nM&aring;ske skulle det v&aelig;re },
	ERRSTR_E27d => qq{?},
	ERRSTR_E28 => qq{Jeg er ked af, giver det ikke mening at N&AElig;GTE og ikke kender p&aring; samme tid},
	ERRSTR_E29 => qq{Venligst tr&aelig;kke alle elementer ud til &#39;Dine valg&#39; box},
	ERRSTR_E29a => qq{venligst tr&aelig;k},
	ERRSTR_E29b => qq{elementer ud til &#39;Dine valg&#39; box},
	ERRSTR_E2a => qq{Besvar venligst alle sp&oslash;rgsm&aring;lene},
	ERRSTR_E2b => qq{Besvar venligst mindst %d af sp&oslash;rgsm&aring;lene},
	ERRSTR_E30a => qq{Du b&oslash;r have kun},
	ERRSTR_E30b => qq{poster i &#39;Din valg-boksen},
	ERRSTR_E3a => qq{Svaret %s er ikke et tal},
	ERRSTR_E4a => qq{Svaret %d er for lavt, det skal v&aelig;re mindst %d},
	ERRSTR_E5a => qq{Svaret % er for h&oslash;jt, det skal ikke v&aelig;re h&oslash;jere end %d},
	ERRSTR_E6a => qq{Beklager, men dette svar giver ikke mening (tallet skal v&aelig;re st&oslash;rre end eller lig med %d)},
	ERRSTR_E7a => qq{Du skal v&aelig;lge mindst %d udsagn},
	ERRSTR_E7b => qq{Du skal v&aelig;lge mindst %d eller v&aelig;lge mulighed %s},
	ERRSTR_E8a => qq{Beklager, men dette svar giver ikke mening (tallet skal v&aelig;re mindre end eller lig med %d)},
	ERRSTR_E9a => qq{Beklager, men disse tal skal give %d tilsammen (dine giver %)},
	ERRSTR_I1 => qq{INDTAST ET HELT TAL},
	ERRSTR_I2 => qq{V&AElig;LG ALLE, DER PASSER},
	ERRSTR_I3 => qq{V&AElig;LG KUN &Eacute;N MULIGHED},
	ERRSTR_I30 => qq{TR&AElig;K CURSEREN LANGS SKALAEN FOR AT ANGIVE DIN BED&Oslash;MMELSE},
	ERRSTR_I4 => qq{INDTAST VENLIGST DIT SVAR},
	ERRSTR_I5 => qq{INDTAST PROCENTDELE, I ALT 100%},
	ERRSTR_I6 => qq{INDTAST ET BEL&Oslash;B I HELE DOLLAR},
	ERRSTR_I7 => qq{UGYLDIG TYPE SP&Oslash;RGSM&Aring;L},
	ERRSTR_I8 => qq{V&AElig;LG &Eacute;T UDSAGN PR. R&AElig;KKE},
	ERRSTR_I9 => qq{V&AElig;LG &Eacute;T UDSAGN I HVER KOLONNE FOR HVER R&AElig;KKE},
	TXT_AGE => qq{Alder},
	TXT_AGE_ONS => qq{Alder p&aring; sk&aelig;rmen},
	TXT_AGE_REC => qq{Registreret alder},
	TXT_AVAIL => qq{Valgmuligheder},
	TXT_COUNT => qq{Samment&aelig;lling},
	TXT_DAY => qq{Dag},
	TXT_HOWLONG => qq{Hvor l&aelig;nge siden},
	TXT_ITEM => qq{Genstand},
	TXT_JS1 => qq{Vi har et problem!},
	TXT_JS2 => qq{Din browser har ikke javascript aktiveret. Dette er et problem, fordi unders&oslash;gelsen bruger avancerede HTML-funktioner, der kr&aelig;ver Javascript er sl&aring;et til.},
	TXT_JS3 => qq{Hvordan til at ordne det},
	TXT_JS4 => qq{Du kan enten bruge en anden browser, som har Javascript aktiveret, eller f&aring; vejledning i at t&aelig;nde den her:},
	TXT_JS5 => qq{Hvordan kan jeg vide, n&aring;r jeg har l&oslash;st det?},
	TXT_JS6 => qq{N&aring;r du har aktiveret det p&aring;, at komme tilbage til denne side og opfriske den. Hvis denne fejlmeddelelse ikke vises, er problemet l&oslash;st.},
	TXT_MONTH => qq{M&aring;ned},
	TXT_NOTES => qq{Notater},
	TXT_NOTHING => qq{Ingenting},
	TXT_OTHER_SPEC => qq{Andet (specific&eacute;r)},
	TXT_QS => qq{Sp&oslash;rgsm&aring;l},
	TXT_TICK => qq{flueben},
	TXT_YEAR => qq{&Aring;r},
	TXT_YOURS => qq{dine valg},
);
# Default Prompts
#
@def_instr = 	(
		"Invalid question type - please contact support",
		"($sysmsg{ERRSTR_I1})",				# Number
		"($sysmsg{ERRSTR_I2})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I4})",
		"($sysmsg{ERRSTR_I5})",
		"",
		"",
		"($sysmsg{ERRSTR_I6})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I7})",
		"($sysmsg{ERRSTR_I3})",
		"",
		"($sysmsg{ERRSTR_I8})",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",										# Spares are defensive
		"($sysmsg{ERRSTR_I30})",
	);

#
# Even if you have to edit this file, please leave this soldier on the last line
#
1;
