#!/usr/bin/perl
## $Id: xlate.msg.pl,v 1.3 2011-09-14 13:33:56 triton Exp  GENERATED FILE: DO NOT EDIT ! See /cgi-adm/xlate.msg.pl to edit/update
#
# CONTAINS LANGUAGE STRINGS FOR ERROR MESSAGES
#
our %sysmsg = (
	BTN_BACK => qq{Rentre},
	BTN_DK => qq{Ne pas savoir},
	BTN_NEXT => qq{Continuer},
	BTN_REFUSED => qq{Refus&eacute;},
	BTN_SUBMITTING => qq{Soumettre.. },
	ERRSTR_E10a => qq{Vous avez choisi % le s de m&ecirc;me que % le s&#133; forme s&#39;il vous pla&icirc;t votre esprit&nbsp;! },
	ERRSTR_E11a => qq{Vous devez choisir non plus que %d des articles},
	ERRSTR_E11b => qq{Vous devez choisir non plus qu&#39;un article},
	ERRSTR_E12a => qq{Veuillez choisir un item sur la liste},
	ERRSTR_E13a => qq{S&#39;il vous pla&icirc;t l&#39;un choisir de la baisse l&#39;en bas liste},
	ERRSTR_E14a => qq{Les pourcentages se doivent &eacute;lever &agrave; 100 (vous avez %d jusqu&#39;ici)},
	ERRSTR_E15a => qq{S&#39;il vous pla&icirc;t compl&eacute;ter toutes r&eacute;ponses pour [%s]},
	ERRSTR_E15b => qq{S&#39;il vous pla&icirc;t choisir le code de recency pour %s},
	ERRSTR_E15c => qq{S&#39;il vous pla&icirc;t choisir au moins %d des r&eacute;ponses},
	ERRSTR_E15d => qq{S&#39;il vous pla&icirc;t choisir au moins %d des r&eacute;ponses pour %s},
	ERRSTR_E16a => qq{Erreur: Veuillez choisir une r&eacute;ponse &agrave; chaque question},
	ERRSTR_E17a => qq{S&#39;il vous pla&icirc;t faire une s&eacute;lection de la liste au-dessus},
	ERRSTR_E18a => qq{L&#39;erreur: S&#39;il vous pla&icirc;t choisir un num&eacute;ro diff&eacute;rent pour chaque lieu qui refl&egrave;te votre ordre de pr&eacute;f&eacute;rence.},
	ERRSTR_E19a => qq{L&#39;erreur&nbsp;: vous avez donn&eacute; classer pareil aux articles multiples},
	ERRSTR_E1a => qq{Nous vraiment l&#39;appr&eacute;cierions si vous pourriez dire quelque chose ici},
	ERRSTR_E20a => qq{L&#39;erreur&nbsp;: vous ne pouvez pas choisir pareil un deux fois},
	ERRSTR_E21a => qq{Le type nul de question - s&#39;il vous pla&icirc;t le contact soutient},
	ERRSTR_E22a => qq{Vous avez choisi &#39;autre&#39;, s&#39;il vous pla&icirc;t me dire que l&#39;autre chose est},
	ERRSTR_E22b => qq{Vous avez choisi &#39;autre&#39;, s&#39;il vous pla&icirc;t me dire que l&#39;autre chose est},
	ERRSTR_E22c => qq{Vous avez s&eacute;lectionn&eacute; &#39;autres&#39;, s&#39;il vous pla&icirc;t me dire ce que l&#39;autre chose est de },
	ERRSTR_E22d => qq{Vous avez entr&eacute; quelque chose, mais ne pas s&eacute;lectionner &laquo;autre&raquo;, s&#39;il vous pla&icirc;t corriger},
	ERRSTR_E22e => qq{Vous pensez que les &#39;autres&#39;, s&#39;il vous pla&icirc;t le pr&eacute;ciser (ou d&#39;effacer la r&eacute;ponse)},
	ERRSTR_E22f => qq{Vous avez sp&eacute;cifi&eacute; &#39;l&#39;autre&#39;, s&#39;il vous pla&icirc;t taux de celle-ci (ou d&#39;effacer la r&eacute;ponse)},
	ERRSTR_E23a => qq{S&#39;il vous pla&icirc;t remplit au moins %d des r&eacute;ponses},
	ERRSTR_E23b => qq{Veuillez choisir un item sur la liste},
	ERRSTR_E24 => qq{Probablement dans 12 mois - demande s&#39;il vous pla&icirc;t.. },
	ERRSTR_E25 => qq{L&#39;erreur&nbsp;: le R&eacute;pondant est seul},
	ERRSTR_E26 => qq{S&#39;il vous pla&icirc;t choisir au moins l&#39;un pour %s},
	ERRSTR_E27a => qq{Cette ann&eacute;e de naissance (},
	ERRSTR_E27b => qq{) ne semble pas possible pour un},
	ERRSTR_E27c => qq{l&#39;ann&eacute;e vieux !\n Peut-&ecirc;tre ce doit &ecirc;tre},
	ERRSTR_E27d => qq{?},
	ERRSTR_E28 => qq{Je suis d&eacute;sol&eacute;, il ne fait pas le sens pour REFUSER et ne PAS SAVOIR en m&ecirc;me temps},
	ERRSTR_E29 => qq{Veuillez faire glisser toutes les propositions dans la case &#39;Vos s&eacute;lections&#39;},
	ERRSTR_E29a => qq{Veuillez faire glisser},
	ERRSTR_E29b => qq{propositions dans la case &#39;Vos s&eacute;lections&#39;},
	ERRSTR_E2a => qq{S&#39;il vous pla&icirc;t remplit toutes r&eacute;ponses},
	ERRSTR_E2b => qq{S&#39;il vous pla&icirc;t remplit au moins %d r&eacute;ponses},
	ERRSTR_E30a => qq{Vous devriez avoir uniquement},
	ERRSTR_E30b => qq{propositions dans la case &#39;Vos s&eacute;lections&#39;},
	ERRSTR_E3a => qq{La r&eacute;ponse %s n&#39;est pas un nombre},
	ERRSTR_E4a => qq{La r&eacute;ponse %d est trop bas, ce doit &ecirc;tre au moins %d},
	ERRSTR_E5a => qq{La r&eacute;ponse %d est trop haut, ce doit &ecirc;tre non plus que %d},
	ERRSTR_E6a => qq{D&eacute;sol&eacute;, cette r&eacute;ponse ce pas sens de marque (le nombre doit &ecirc;tre plus grand qu&#39;ou &eacute;gal &agrave; %d)},
	ERRSTR_E7a => qq{Vous devez choisir au moins %d des r&eacute;ponses},
	ERRSTR_E7b => qq{Vous devez choisir au moins %d ou choisit le %s option},
	ERRSTR_E8a => qq{D&eacute;sol&eacute;, cette r&eacute;ponse ce pas sens de marque (le nombre doit &ecirc;tre moins qu&#39;ou &eacute;gal &agrave; % d)},
	ERRSTR_E9a => qq{D&eacute;sol&eacute;, ces nombres se doivent &eacute;lever &agrave; %d (vous avez %d)},
	ERRSTR_I1 => qq{ENTRER UN NOMBRE ENTIER},
	ERRSTR_I2 => qq{CHOISIR TOUTES LES R&Eacute;PONSES QUI S&#39;APPLIQUENT},
	ERRSTR_I3 => qq{CHOISIR UNE R&Eacute;PONSE SEULEMENT},
	ERRSTR_I30 => qq{TRAINER LE POINTEUR LE LONG DE L&#39;ECHELLE POUR FOURNIR VOTRE CLASSEMENT},
	ERRSTR_I4 => qq{S&#39;IL VOUS PLAIT TAPER VOTRE R&Eacute;PONSE},
	ERRSTR_I5 => qq{ENTRER DES POURCENTAGES, DOIT TOTALISER 100%},
	ERRSTR_I6 => qq{ENTRER LA QUANTITE DANS LES DOLLARS ENTIERS},
	ERRSTR_I7 => qq{LE TYPE NUL DE QUESTION},
	ERRSTR_I8 => qq{POUR CHAQUE D&Eacute;CLARATION, CHOISISSEZ UNE R&Eacute;PONSE},
	ERRSTR_I9 => qq{CHOISIR UN ARTICLE DANS CHAQUE COLONNE POUR CHAQUE RANG},
	TXT_AGE => qq{&acirc;ge},
	TXT_AGE_ONS => qq{Age commence},
	TXT_AGE_REC => qq{Age finis},
	TXT_AVAIL => qq{S&eacute;lections disponibles},
	TXT_COUNT => qq{Combien?},
	TXT_DAY => qq{Jour},
	TXT_HOWLONG => qq{Comment il y a longtemps},
	TXT_ITEM => qq{Article},
	TXT_JS1 => qq{Nous avons un probl&egrave;me!},
	TXT_JS2 => qq{Votre navigateur ne dispose pas de Javascript. C&#39;est un probl&egrave;me parce que l&#39;enqu&ecirc;te utilise des fonctionnalit&eacute;s avanc&eacute;es de HTML qui n&eacute;cessitent Javascript soit activ&eacute;.},
	TXT_JS3 => qq{Comment y rem&eacute;dier},
	TXT_JS4 => qq{Vous pouvez soit utiliser un autre navigateur qui a le Javascript, ou obtenir des instructions sur la fa&ccedil;on de l&#39;activer ici:},
	TXT_JS5 => qq{Comment puis-je savoir quand je l&#39;ai fix&eacute;?},
	TXT_JS6 => qq{Une fois que vous l&#39;avez activ&eacute;e, revenir &agrave; cette page et de rafra&icirc;chissement. Si ce message d&#39;erreur ne s&#39;affiche pas, le probl&egrave;me est r&eacute;solu.},
	TXT_MONTH => qq{Mois},
	TXT_NOTES => qq{Remarques},
	TXT_NOTHING => qq{Rien},
	TXT_OTHER_SPEC => qq{Autre (sp&eacute;cifier&nbsp;:)},
	TXT_QS => qq{Q&#39;s},
	TXT_TICK => qq{Choisir},
	TXT_YEAR => qq{Ans},
	TXT_YOURS => qq{Vos s&eacute;lections},
);
# Default Prompts
#
@def_instr = 	(
		"Invalid question type - please contact support",
		"($sysmsg{ERRSTR_I1})",				# Number
		"($sysmsg{ERRSTR_I2})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I4})",
		"($sysmsg{ERRSTR_I5})",
		"",
		"",
		"($sysmsg{ERRSTR_I6})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I7})",
		"($sysmsg{ERRSTR_I3})",
		"",
		"($sysmsg{ERRSTR_I8})",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",										# Spares are defensive
		"($sysmsg{ERRSTR_I30})",
	);

#
# Even if you have to edit this file, please leave this soldier on the last line
#
1;
