#!/usr/bin/perl
## $Id: xlate.msg.pl,v 1.2 2011-09-09 12:16:10 triton Exp  GENERATED FILE: DO NOT EDIT ! See /cgi-adm/xlate.msg.pl to edit/update
#
# CONTAINS LANGUAGE STRINGS FOR ERROR MESSAGES
#
our %sysmsg = (
	BTN_BACK => qq{De volta},
	BTN_DK => qq{N&atilde;o sei},
	BTN_NEXT => qq{Continuar},
	BTN_REFUSED => qq{Recusou-se},
	BTN_SUBMITTING => qq{Submetendo},
	ERRSTR_E10a => qq{Voc&ecirc; selecionou %s tanto quanto %s. Por favor, mude de id&eacute;ia, reflita!},
	ERRSTR_E11a => qq{Voc&ecirc; n&atilde;o deve selecionar mais do que %d itens},
	ERRSTR_E11b => qq{Voc&ecirc; deve selecionar n&atilde;o mais do que um item},
	ERRSTR_E12a => qq{Por favor, selecione um dos itens da lista},
	ERRSTR_E13a => qq{Por favor, selecione um item da lista abaixo},
	ERRSTR_E14a => qq{Porcentagens devem somar at&eacute; 100 (voc&ecirc; tem %d% at&eacute; o momento)},
	ERRSTR_E15a => qq{Por favor, complete todas as respostas para [%s]},
	ERRSTR_E15b => qq{Por favor, selecione o c&oacute;digo rec&ecirc;ncia para %s},
	ERRSTR_E15c => qq{Selecione ao menos %d respostas},
	ERRSTR_E15d => qq{Selecione ao menos %d respostas para %s},
	ERRSTR_E16a => qq{Erro: por favor, fa&ccedil;a uma escolha em cada linha},
	ERRSTR_E17a => qq{Por favor, selecione da lista acima },
	ERRSTR_E18a => qq{Erro: por favor , fa&ccedil;a uma escolha em cada coluna},
	ERRSTR_E19a => qq{Erro: voc&ecirc; deu o mesmo ranking para m&uacute;ltiplos itens},
	ERRSTR_E1a => qq{N&oacute;s realmente apreciar&iacute;amos se voc&ecirc; pudesse fazer algum coment&aacute;rio},
	ERRSTR_E20a => qq{Erro: voc&ecirc; n&atilde;o pode escolher o mesmo item duas vezes},
	ERRSTR_E21a => qq{Quest&atilde;o inv&aacute;lida - por favor, contate o suporte},
	ERRSTR_E22a => qq{Voc&ecirc; selecionou &#39;outro&#39;, por favor, me diga o que a outra coisa &eacute;},
	ERRSTR_E22b => qq{Voc&ecirc; selecionou &#39;outro&#39;, por favor, me diga o que a outra coisa &eacute;},
	ERRSTR_E22c => qq{Voc&ecirc; selecionou &#39;outro&#39;, por favor, me diga o que a outra coisa &eacute; para %s},
	ERRSTR_E22d => qq{Voc&ecirc; digitou alguma coisa, mas n&atilde;o selecione &quot;outro&quot;, por favor, corrija-o},
	ERRSTR_E22e => qq{Voc&ecirc; classificado como &#39;outros&#39;, por favor especific&aacute;-lo (ou apagar a resposta)},
	ERRSTR_E22f => qq{Voc&ecirc; especificou o &#39;outro&#39;, por favor classifique-o (ou apagar a resposta)},
	ERRSTR_E23a => qq{Por favor, preencha pelo menos, respostas %d},
	ERRSTR_E23b => qq{Por favor, preencha pelo menos uma resposta},
	ERRSTR_E24 => qq{Possivelmente dentro de 12 meses - por favor, pergunte ...},
	ERRSTR_E25 => qq{Erro: Reclamado &eacute; de apenas},
	ERRSTR_E26 => qq{Selecione ao menos um para %s},
	ERRSTR_E27a => qq{Este ano de nascimento (},
	ERRSTR_E27b => qq{) n&atilde;o parece poss&iacute;vel para um },
	ERRSTR_E27c => qq{anos de idade. Talvez devesse ser},
	ERRSTR_E27d => qq{?},
	ERRSTR_E28 => qq{Sinto muito, n&atilde;o faz sentido recusar e n&atilde;o sabem ao mesmo tempo},
	ERRSTR_E29 => qq{Por favor, arraste todos os itens em toda a caixa &#39;Suas sele&ccedil;&otilde;es&#39;},
	ERRSTR_E29a => qq{Por favor, arraste },
	ERRSTR_E29b => qq{os itens em toda a caixa &#39;Suas sele&ccedil;&otilde;es&#39;},
	ERRSTR_E2a => qq{Por favor, preencha todas as quest&otilde;es},
	ERRSTR_E2b => qq{Por favor, preencha pelo menos 15 resposta},
	ERRSTR_E30a => qq{Voc&ecirc; deve ter apenas},
	ERRSTR_E30b => qq{itens na caixa &#39;Suas sele&ccedil;&otilde;es&#39;},
	ERRSTR_E3a => qq{A resposta %s n&atilde;o &eacute; um n&uacute;mero},
	ERRSTR_E4a => qq{O valor %d da resposta est&aacute; muito baixo, ele deveria ser pelo menos %d},
	ERRSTR_E5a => qq{O valor %d da resposta est&aacute; muito alto, ele n&atilde;o deve ultrapassar %d},
	ERRSTR_E6a => qq{Desculpe, essa resposta n&atilde;o faz sentido (o n&uacute;mero deve ser maior ou igual a %d) },
	ERRSTR_E7a => qq{Voc&ecirc; deve selecionar pelo menos %d itens},
	ERRSTR_E7b => qq{Voc&ecirc; deve selecionar pelo menos %d ou selecione a op&ccedil;&atilde;o %s},
	ERRSTR_E8a => qq{Desculpe, essa resposta n&atilde;o faz sentido (o n&uacute;mero deve ser maior ou igual a %d)},
	ERRSTR_E9a => qq{Desculpe, esses n&uacute;meros devem somar at&eacute; %d (voc&ecirc; tem %d)},
	ERRSTR_I1 => qq{Digite o n&uacute;mero todo},
	ERRSTR_I2 => qq{Selecione tantos itens quanto tiver escolhido},
	ERRSTR_I3 => qq{Selecione apenas um item},
	ERRSTR_I30 => qq{Arraste o ponteiro ao longo da escala de fornecer o seu RATING},
	ERRSTR_I4 => qq{Por favor, digite sua resposta},
	ERRSTR_I5 => qq{Digite as porcentagens, deve totalizar 100%},
	ERRSTR_I6 => qq{Digite a quantia total em d&oacute;lares},
	ERRSTR_I7 => qq{Quest&atilde;o inv&aacute;lida},
	ERRSTR_I8 => qq{Selecione um item por linha},
	ERRSTR_I9 => qq{Selecionar um item em cada coluna para cada linha},
	TXT_AGE => qq{Idade},
	TXT_AGE_ONS => qq{Idade de in&iacute;cio},
	TXT_AGE_REC => qq{Idade da recess&atilde;o},
	TXT_AVAIL => qq{Sele&ccedil;&otilde;es dispon&iacute;veis},
	TXT_COUNT => qq{Contar},
	TXT_DAY => qq{Dia},
	TXT_HOWLONG => qq{H&aacute; quanto tempo},
	TXT_ITEM => qq{Item },
	TXT_JS1 => qq{Temos um problema!},
	TXT_JS2 => qq{Seu navegador n&atilde;o tem JavaScript habilitado. Este &eacute; um problema porque a pesquisa utiliza recursos avan&ccedil;ados de HTML que exigem que o Javascript esteja ativado.},
	TXT_JS3 => qq{Como corrigi-lo},
	TXT_JS4 => qq{Voc&ecirc; pode usar um navegador diferente, que tem o Javascript habilitado, ou obter instru&ccedil;&otilde;es sobre como ativ&aacute;-lo  aqui:},
	TXT_JS5 => qq{Como eu sei quando tenho que fixa-lo?},
	TXT_JS6 => qq{Uma vez que voc&ecirc; ligou, volte a esta p&aacute;gina e atualiz&aacute;-la.  Se esta mensagem de erro  n&atilde;o aparecer, o problema est&aacute; resolvido.},
	TXT_MONTH => qq{M&ecirc;s},
	TXT_NOTES => qq{Notas},
	TXT_NOTHING => qq{Nada},
	TXT_OTHER_SPEC => qq{Outros (especificar)},
	TXT_QS => qq{Q&#39;s},
	TXT_TICK => qq{Carrapato},
	TXT_YEAR => qq{Ano},
	TXT_YOURS => qq{Suas sele&ccedil;&otilde;es},
);
# Default Prompts
#
@def_instr = 	(
		"Invalid question type - please contact support",
		"($sysmsg{ERRSTR_I1})",				# Number
		"($sysmsg{ERRSTR_I2})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I4})",
		"($sysmsg{ERRSTR_I5})",
		"",
		"",
		"($sysmsg{ERRSTR_I6})",
		"($sysmsg{ERRSTR_I3})",
		"($sysmsg{ERRSTR_I7})",
		"($sysmsg{ERRSTR_I3})",
		"",
		"($sysmsg{ERRSTR_I8})",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",										# Spares are defensive
		"($sysmsg{ERRSTR_I30})",
	);

#
# Even if you have to edit this file, please leave this soldier on the last line
#
1;
