#!/usr/bin/perl
# generated by TPerl::Parser because it does not exist 
# Wed Jun 19 05:07:34 2002
# config2.pl should be hand edited for future quick hacks and overwrites etc.
$login_page = '/cgi-mr/pwikit_login.pl?id=<%id%>&password=<%password%>';
$allow_restart=1;

$BTN_NEXT = " NEXT >> ";
$BTN_REFUSED = "NEXT (skips checking)";
$BTN_BACK = " << BACK ";
$show_back_button = 1;
@jump_index = (
				'A',
				'q1.q4',
				'LAST.LAST',
				);
1;
