bless({
  _SID           => "MAP009",
  _TritonRoot    => "/home/vhosts/pwidev/triton",
  _config_subdir => "config",
  _data_subdir   => "web",
  _doc_root      => undef,
  _doc_subdir    => "doc",
  _final_subdir  => "final",
  _html_subdir   => "html",
  _masks         => {},
  _options       => {
                      block_size       => 5,
                      custom_footer    => "<center><img src=\"/themes/ekit/ekit.daa.png\" alt=\"Discipline, Accountability, Achievement\" ></center>",
                      focus_off        => 1,
                      mailto           => "ctwebb\@mapconsulting.com",
                      no_copy          => 1,
                      no_progress_bar  => 1,
                      one_at_a_time    => 0,
                      optional_written => 0,
                      qbanner          => "<table border=0 cellpadding=0 cellspacing=0 class=\"bannertable\"><tr><TD class=\"bannerlogo\">&nbsp;<TD width=\"50px\" >&nbsp;<tr><TD class=\"bluebar\"> &nbsp;&nbsp; Spreadsheet of Vital Financial Factors<TH class=\"bluebarq\">Q9</table>",
                      qscale           => "<P><%q_label%>",
                      show_back_button => 1,
                      survey_name      => "Spreadsheet of Vital Financial Factors",
                      thankyou_url     => "thanks.htm",
                      theme            => "ekit",
                      window_title     => "Q9 - Spreadsheet of Vital Financial Factors",
                    },
  _questions     => [
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _code       => [
                                         "duedate=duedate",
                                         "id=id",
                                         "token=token",
                                         "login_page=login_page",
                                         "warning=warning",
                                         "ws_details=ws_details",
                                         "qbanner=qbanner",
                                         "qscale=qscale",
                                       ],
                        _dataInfo   => [],
                        _label      => "AA",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "",
                        _qnum       => 1,
                        _qtype      => 20,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => ["bogus"],
                        _dataInfo   => [],
                        _label      => "A",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "<%qbanner%><TABLE width=\"600\"><TR><TD class=\"prompt\">A key element of the MAP workshop is the analysis of your organization's Vital Financial Factors. Your Workshop Leader will use the information, as deemed appropriate, to develop a graph, ratios and other statistics that will be presented to you for learning purposes.<P>The information will be treated confidentially by MAP and will not be shared with anyone without your express permission.<HR>Step 1:<BR>Review your last four fiscal year-end (FYE) financial statements (balance sheets, profit and loss statements, etc.) and your current year-to-date financial statement.<BR><BR><HR>Step 2:<BR>In columns 1 through 5, transfer the figures from your financial statements into the appropriate spaces. Place the <U>current year</u> in column <B>5</B>, most recent in columns 4, etc. In current year, indicate the number of months included.<BR><BR>Note: You may round off to the nearest hundred dollars, if convenient. MAP is aware that you may not be able to complete each line item requested due to the nature of your organization's business. Please complete all items that are applicable.<BR><BR><HR>Step 3:<BR>The items under \"people\" can be obtained from your payroll records.<BR><BR><HR>Step 4:<BR>Total square feet of your plant should include the space occupied by both office and physical plant.<BR><BR><HR>Step 5:<BR>Please complete the spreadsheet as soon as possible prior to <%duedate%>.&nbsp;</TD></TR></TABLE>",
                        _qnum       => 2,
                        _qtype      => 7,
                        _scores     => [0],
                        _setvalues  => [undef],
                        _skips      => [1],
                        _vars       => [undef],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames  => [],
                        _attributes  => [
                                          "FYE (i.e., 2005, 2006, 2007, etc.)",
                                          "Sales/Revenue",
                                          "Cost of sales *",
                                          "Gross profit",
                                          "General & administrative (plus selling costs) *",
                                          "Net profit / (loss) *",
                                          "Accounts receivable",
                                          "Accounts payable",
                                          "Inventory *",
                                          "Total current assets",
                                          "Fixed assets",
                                          "Total assets",
                                          "Current liabilities",
                                          "Long-term liabilities",
                                          "Total liabilities",
                                          "Net worth",
                                        ],
                        _dataInfo    => [
                                          {
                                            "pos" => 0,
                                            rkey => "_Q1",
                                            var => "Q1x1x1",
                                            var_label => "FYE (i.e., 2005, 2006, 2007, etc.)-1-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 1,
                                            rkey => "_Q1",
                                            var => "Q1x1x2",
                                            var_label => "FYE (i.e., 2005, 2006, 2007, etc.)-2-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 2,
                                            rkey => "_Q1",
                                            var => "Q1x1x3",
                                            var_label => "FYE (i.e., 2005, 2006, 2007, etc.)-3-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 3,
                                            rkey => "_Q1",
                                            var => "Q1x1x4",
                                            var_label => "FYE (i.e., 2005, 2006, 2007, etc.)-4-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 4,
                                            rkey => "_Q1",
                                            var => "Q1x1x5",
                                            var_label => "FYE (i.e., 2005, 2006, 2007, etc.)-5-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 5,
                                            rkey => "_Q1",
                                            var => "Q1x2x1",
                                            var_label => "Sales/Revenue-1-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 6,
                                            rkey => "_Q1",
                                            var => "Q1x2x2",
                                            var_label => "Sales/Revenue-2-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 7,
                                            rkey => "_Q1",
                                            var => "Q1x2x3",
                                            var_label => "Sales/Revenue-3-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 8,
                                            rkey => "_Q1",
                                            var => "Q1x2x4",
                                            var_label => "Sales/Revenue-4-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 9,
                                            rkey => "_Q1",
                                            var => "Q1x2x5",
                                            var_label => "Sales/Revenue-5-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 10,
                                            rkey => "_Q1",
                                            var => "Q1x3x1",
                                            var_label => "Cost of sales *-1-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 11,
                                            rkey => "_Q1",
                                            var => "Q1x3x2",
                                            var_label => "Cost of sales *-2-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 12,
                                            rkey => "_Q1",
                                            var => "Q1x3x3",
                                            var_label => "Cost of sales *-3-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 13,
                                            rkey => "_Q1",
                                            var => "Q1x3x4",
                                            var_label => "Cost of sales *-4-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 14,
                                            rkey => "_Q1",
                                            var => "Q1x3x5",
                                            var_label => "Cost of sales *-5-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 15,
                                            rkey => "_Q1",
                                            var => "Q1x4x1",
                                            var_label => "Gross profit-1-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 16,
                                            rkey => "_Q1",
                                            var => "Q1x4x2",
                                            var_label => "Gross profit-2-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 17,
                                            rkey => "_Q1",
                                            var => "Q1x4x3",
                                            var_label => "Gross profit-3-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 18,
                                            rkey => "_Q1",
                                            var => "Q1x4x4",
                                            var_label => "Gross profit-4-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 19,
                                            rkey => "_Q1",
                                            var => "Q1x4x5",
                                            var_label => "Gross profit-5-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 20,
                                            rkey => "_Q1",
                                            var => "Q1x5x1",
                                            var_label => "General & administrative (plus selling costs) *-1-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 21,
                                            rkey => "_Q1",
                                            var => "Q1x5x2",
                                            var_label => "General & administrative (plus selling costs) *-2-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 22,
                                            rkey => "_Q1",
                                            var => "Q1x5x3",
                                            var_label => "General & administrative (plus selling costs) *-3-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 23,
                                            rkey => "_Q1",
                                            var => "Q1x5x4",
                                            var_label => "General & administrative (plus selling costs) *-4-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 24,
                                            rkey => "_Q1",
                                            var => "Q1x5x5",
                                            var_label => "General & administrative (plus selling costs) *-5-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 25,
                                            rkey => "_Q1",
                                            var => "Q1x6x1",
                                            var_label => "Net profit / (loss) *-1-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 26,
                                            rkey => "_Q1",
                                            var => "Q1x6x2",
                                            var_label => "Net profit / (loss) *-2-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 27,
                                            rkey => "_Q1",
                                            var => "Q1x6x3",
                                            var_label => "Net profit / (loss) *-3-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 28,
                                            rkey => "_Q1",
                                            var => "Q1x6x4",
                                            var_label => "Net profit / (loss) *-4-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 29,
                                            rkey => "_Q1",
                                            var => "Q1x6x5",
                                            var_label => "Net profit / (loss) *-5-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 30,
                                            rkey => "_Q1",
                                            var => "Q1x7x1",
                                            var_label => "Accounts receivable-1-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 31,
                                            rkey => "_Q1",
                                            var => "Q1x7x2",
                                            var_label => "Accounts receivable-2-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 32,
                                            rkey => "_Q1",
                                            var => "Q1x7x3",
                                            var_label => "Accounts receivable-3-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 33,
                                            rkey => "_Q1",
                                            var => "Q1x7x4",
                                            var_label => "Accounts receivable-4-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 34,
                                            rkey => "_Q1",
                                            var => "Q1x7x5",
                                            var_label => "Accounts receivable-5-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 35,
                                            rkey => "_Q1",
                                            var => "Q1x8x1",
                                            var_label => "Accounts payable-1-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 36,
                                            rkey => "_Q1",
                                            var => "Q1x8x2",
                                            var_label => "Accounts payable-2-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 37,
                                            rkey => "_Q1",
                                            var => "Q1x8x3",
                                            var_label => "Accounts payable-3-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 38,
                                            rkey => "_Q1",
                                            var => "Q1x8x4",
                                            var_label => "Accounts payable-4-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 39,
                                            rkey => "_Q1",
                                            var => "Q1x8x5",
                                            var_label => "Accounts payable-5-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 40,
                                            rkey => "_Q1",
                                            var => "Q1x9x1",
                                            var_label => "Inventory *-1-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 41,
                                            rkey => "_Q1",
                                            var => "Q1x9x2",
                                            var_label => "Inventory *-2-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 42,
                                            rkey => "_Q1",
                                            var => "Q1x9x3",
                                            var_label => "Inventory *-3-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 43,
                                            rkey => "_Q1",
                                            var => "Q1x9x4",
                                            var_label => "Inventory *-4-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 44,
                                            rkey => "_Q1",
                                            var => "Q1x9x5",
                                            var_label => "Inventory *-5-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 45,
                                            rkey => "_Q1",
                                            var => "Q1x10x1",
                                            var_label => "Total current assets-1-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 46,
                                            rkey => "_Q1",
                                            var => "Q1x10x2",
                                            var_label => "Total current assets-2-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 47,
                                            rkey => "_Q1",
                                            var => "Q1x10x3",
                                            var_label => "Total current assets-3-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 48,
                                            rkey => "_Q1",
                                            var => "Q1x10x4",
                                            var_label => "Total current assets-4-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 49,
                                            rkey => "_Q1",
                                            var => "Q1x10x5",
                                            var_label => "Total current assets-5-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 50,
                                            rkey => "_Q1",
                                            var => "Q1x11x1",
                                            var_label => "Fixed assets-1-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 51,
                                            rkey => "_Q1",
                                            var => "Q1x11x2",
                                            var_label => "Fixed assets-2-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 52,
                                            rkey => "_Q1",
                                            var => "Q1x11x3",
                                            var_label => "Fixed assets-3-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 53,
                                            rkey => "_Q1",
                                            var => "Q1x11x4",
                                            var_label => "Fixed assets-4-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 54,
                                            rkey => "_Q1",
                                            var => "Q1x11x5",
                                            var_label => "Fixed assets-5-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 55,
                                            rkey => "_Q1",
                                            var => "Q1x12x1",
                                            var_label => "Total assets-1-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 56,
                                            rkey => "_Q1",
                                            var => "Q1x12x2",
                                            var_label => "Total assets-2-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 57,
                                            rkey => "_Q1",
                                            var => "Q1x12x3",
                                            var_label => "Total assets-3-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 58,
                                            rkey => "_Q1",
                                            var => "Q1x12x4",
                                            var_label => "Total assets-4-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 59,
                                            rkey => "_Q1",
                                            var => "Q1x12x5",
                                            var_label => "Total assets-5-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 60,
                                            rkey => "_Q1",
                                            var => "Q1x13x1",
                                            var_label => "Current liabilities-1-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 61,
                                            rkey => "_Q1",
                                            var => "Q1x13x2",
                                            var_label => "Current liabilities-2-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 62,
                                            rkey => "_Q1",
                                            var => "Q1x13x3",
                                            var_label => "Current liabilities-3-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 63,
                                            rkey => "_Q1",
                                            var => "Q1x13x4",
                                            var_label => "Current liabilities-4-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 64,
                                            rkey => "_Q1",
                                            var => "Q1x13x5",
                                            var_label => "Current liabilities-5-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 65,
                                            rkey => "_Q1",
                                            var => "Q1x14x1",
                                            var_label => "Long-term liabilities-1-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 66,
                                            rkey => "_Q1",
                                            var => "Q1x14x2",
                                            var_label => "Long-term liabilities-2-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 67,
                                            rkey => "_Q1",
                                            var => "Q1x14x3",
                                            var_label => "Long-term liabilities-3-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 68,
                                            rkey => "_Q1",
                                            var => "Q1x14x4",
                                            var_label => "Long-term liabilities-4-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 69,
                                            rkey => "_Q1",
                                            var => "Q1x14x5",
                                            var_label => "Long-term liabilities-5-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 70,
                                            rkey => "_Q1",
                                            var => "Q1x15x1",
                                            var_label => "Total liabilities-1-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 71,
                                            rkey => "_Q1",
                                            var => "Q1x15x2",
                                            var_label => "Total liabilities-2-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 72,
                                            rkey => "_Q1",
                                            var => "Q1x15x3",
                                            var_label => "Total liabilities-3-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 73,
                                            rkey => "_Q1",
                                            var => "Q1x15x4",
                                            var_label => "Total liabilities-4-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 74,
                                            rkey => "_Q1",
                                            var => "Q1x15x5",
                                            var_label => "Total liabilities-5-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 75,
                                            rkey => "_Q1",
                                            var => "Q1x16x1",
                                            var_label => "Net worth-1-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 76,
                                            rkey => "_Q1",
                                            var => "Q1x16x2",
                                            var_label => "Net worth-2-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 77,
                                            rkey => "_Q1",
                                            var => "Q1x16x3",
                                            var_label => "Net worth-3-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 78,
                                            rkey => "_Q1",
                                            var => "Q1x16x4",
                                            var_label => "Net worth-4-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                          {
                                            "pos" => 79,
                                            rkey => "_Q1",
                                            var => "Q1x16x5",
                                            var_label => "Net worth-5-<%qbanner%><P><%q_label%> Vital Financial Information",
                                          },
                                        ],
                        _g_varnames  => [1, 2, 3, 4, 5],
                        _label       => 1,
                        _opt         => {
                                          dk => undef,
                                          instr => "* if applicable",
                                          left_word => "Prior years",
                                          limhi => 999999999,
                                          middle => undef,
                                          right_word => "Current",
                                          scale => -5,
                                        },
                        _prompt      => "<%qbanner%><P><%q_label%> Vital Financial Information",
                        _qnum        => 3,
                        _qtype       => 29,
                        _scale_words => [1, 2, 3, 4, 5],
                        _scores      => [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                        _setvalues   => [
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                        ],
                        _skips       => [
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                        ],
                        _vars        => [
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                        ],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames  => [],
                        _attributes  => [
                                          "Average number of total employees during this year",
                                          "Average number of management people",
                                          "Number of terminations",
                                        ],
                        _dataInfo    => [
                                          {
                                            "pos" => 0,
                                            rkey => "_Q2",
                                            var => "Q2x1x1",
                                            var_label => "Average number of total employees during this year-1-People",
                                          },
                                          {
                                            "pos" => 1,
                                            rkey => "_Q2",
                                            var => "Q2x1x2",
                                            var_label => "Average number of total employees during this year-2-People",
                                          },
                                          {
                                            "pos" => 2,
                                            rkey => "_Q2",
                                            var => "Q2x1x3",
                                            var_label => "Average number of total employees during this year-3-People",
                                          },
                                          {
                                            "pos" => 3,
                                            rkey => "_Q2",
                                            var => "Q2x1x4",
                                            var_label => "Average number of total employees during this year-4-People",
                                          },
                                          {
                                            "pos" => 4,
                                            rkey => "_Q2",
                                            var => "Q2x1x5",
                                            var_label => "Average number of total employees during this year-5-People",
                                          },
                                          {
                                            "pos" => 5,
                                            rkey => "_Q2",
                                            var => "Q2x2x1",
                                            var_label => "Average number of management people-1-People",
                                          },
                                          {
                                            "pos" => 6,
                                            rkey => "_Q2",
                                            var => "Q2x2x2",
                                            var_label => "Average number of management people-2-People",
                                          },
                                          {
                                            "pos" => 7,
                                            rkey => "_Q2",
                                            var => "Q2x2x3",
                                            var_label => "Average number of management people-3-People",
                                          },
                                          {
                                            "pos" => 8,
                                            rkey => "_Q2",
                                            var => "Q2x2x4",
                                            var_label => "Average number of management people-4-People",
                                          },
                                          {
                                            "pos" => 9,
                                            rkey => "_Q2",
                                            var => "Q2x2x5",
                                            var_label => "Average number of management people-5-People",
                                          },
                                          {
                                            "pos" => 10,
                                            rkey => "_Q2",
                                            var => "Q2x3x1",
                                            var_label => "Number of terminations-1-People",
                                          },
                                          {
                                            "pos" => 11,
                                            rkey => "_Q2",
                                            var => "Q2x3x2",
                                            var_label => "Number of terminations-2-People",
                                          },
                                          {
                                            "pos" => 12,
                                            rkey => "_Q2",
                                            var => "Q2x3x3",
                                            var_label => "Number of terminations-3-People",
                                          },
                                          {
                                            "pos" => 13,
                                            rkey => "_Q2",
                                            var => "Q2x3x4",
                                            var_label => "Number of terminations-4-People",
                                          },
                                          {
                                            "pos" => 14,
                                            rkey => "_Q2",
                                            var => "Q2x3x5",
                                            var_label => "Number of terminations-5-People",
                                          },
                                        ],
                        _g_varnames  => [1, 2, 3, 4, 5],
                        _label       => 2,
                        _opt         => {
                                          dk => undef,
                                          instr => "",
                                          left_word => "Prior years",
                                          limhi => 999999,
                                          middle => undef,
                                          right_word => "Current",
                                          scale => -5,
                                        },
                        _prompt      => "People",
                        _qnum        => 4,
                        _qtype       => 29,
                        _scale_words => [1, 2, 3, 4, 5],
                        _scores      => [0, 0, 0],
                        _setvalues   => [undef, undef, undef],
                        _skips       => [undef, undef, undef],
                        _vars        => [undef, undef, undef],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames  => [],
                        _attributes  => ["Total square feet", "Locations"],
                        _dataInfo    => [
                                          {
                                            "pos" => 0,
                                            rkey => "_Q3",
                                            var => "Q3x1x1",
                                            var_label => "Total square feet-1-Plant/Office",
                                          },
                                          {
                                            "pos" => 1,
                                            rkey => "_Q3",
                                            var => "Q3x1x2",
                                            var_label => "Total square feet-2-Plant/Office",
                                          },
                                          {
                                            "pos" => 2,
                                            rkey => "_Q3",
                                            var => "Q3x1x3",
                                            var_label => "Total square feet-3-Plant/Office",
                                          },
                                          {
                                            "pos" => 3,
                                            rkey => "_Q3",
                                            var => "Q3x1x4",
                                            var_label => "Total square feet-4-Plant/Office",
                                          },
                                          {
                                            "pos" => 4,
                                            rkey => "_Q3",
                                            var => "Q3x1x5",
                                            var_label => "Total square feet-5-Plant/Office",
                                          },
                                          {
                                            "pos" => 5,
                                            rkey => "_Q3",
                                            var => "Q3x2x1",
                                            var_label => "Locations-1-Plant/Office",
                                          },
                                          {
                                            "pos" => 6,
                                            rkey => "_Q3",
                                            var => "Q3x2x2",
                                            var_label => "Locations-2-Plant/Office",
                                          },
                                          {
                                            "pos" => 7,
                                            rkey => "_Q3",
                                            var => "Q3x2x3",
                                            var_label => "Locations-3-Plant/Office",
                                          },
                                          {
                                            "pos" => 8,
                                            rkey => "_Q3",
                                            var => "Q3x2x4",
                                            var_label => "Locations-4-Plant/Office",
                                          },
                                          {
                                            "pos" => 9,
                                            rkey => "_Q3",
                                            var => "Q3x2x5",
                                            var_label => "Locations-5-Plant/Office",
                                          },
                                        ],
                        _g_varnames  => [1, 2, 3, 4, 5],
                        _label       => 3,
                        _opt         => {
                                          dk => undef,
                                          instr => "",
                                          left_word => "Prior years",
                                          limhi => 999999,
                                          middle => undef,
                                          right_word => "Current",
                                          scale => -5,
                                        },
                        _prompt      => "Plant/Office",
                        _qnum        => 5,
                        _qtype       => 29,
                        _scale_words => [1, 2, 3, 4, 5],
                        _scores      => [0, 0],
                        _setvalues   => [undef, undef],
                        _skips       => [undef, undef],
                        _vars        => [undef, undef],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => ["Months"],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q4",
                                           var => "Q4",
                                           var_label => "Months-Please indicate number of months you are currently into your current fiscal year",
                                         },
                                       ],
                        _label      => 4,
                        _opt        => { instr => "", limhi => 12, limlo => 1, required => 0, scale => 0 },
                        _prompt     => "Please indicate number of months you are currently into your current fiscal year",
                        _qnum       => 6,
                        _qtype      => 1,
                        _scores     => [0],
                        _setvalues  => [undef],
                        _skips      => [undef],
                        _vars       => [undef],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _code       => [
                                         "my \$dcount = &count_data;",
                                         "&debug(\"Datacount = \$dcount\");",
                                         "if (\$dcount>0) {\$q_no = goto_qlab(\"LAST\") - 1;}",
                                         "if (\$dcount==0) {&db_conn;&db_set_status(\$survey_id,\$resp{id},\$resp{token},0,0)}",
                                       ],
                        _dataInfo   => [],
                        _label      => "CHECK",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "Check if we have enough data to allow submission of form",
                        _qnum       => 7,
                        _qtype      => 27,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames    => [],
                        _attributes    => [],
                        _dataInfo      => [
                                            {
                                              "pos" => 0,
                                              rkey => "ext_BACK2",
                                              type => "hidden",
                                              var => "BACK2",
                                              var_label => "See external page \"nodata.htm\"",
                                            },
                                          ],
                        _external_info => {
                                            names    => [undef, "BACK2"],
                                            options  => {
                                                          "" => {
                                                                alt => "HOME",
                                                                onclick => "document.location='/cgi-mr/pwikit_login.pl?id=<%id%>&password=<%token%>'",
                                                                tabindex => -1,
                                                                type => "BUTTON",
                                                                value => " HOME ",
                                                              },
                                                          BACK2 => { name => "BACK2", type => "hidden" },
                                                        },
                                            "values" => { "" => [" HOME ", " GO BACK "] },
                                          },
                        _label         => "NODATA",
                        _opt           => { external => "nodata.htm", instr => "", scale => 0 },
                        _prompt        => "See external page \"nodata.htm\"",
                        _qnum          => 8,
                        _qtype         => 7,
                        _scores        => [],
                        _setvalues     => [],
                        _skips         => [],
                        _vars          => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _code       => ["duedate=duedate", "id=id", "token=token"],
                        _dataInfo   => [],
                        _label      => "BREAK",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "",
                        _qnum       => 9,
                        _qtype      => 20,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames    => [],
                        _attributes    => [],
                        _dataInfo      => [
                                            {
                                              "pos" => 0,
                                              rkey => "ext_finish",
                                              type => "hidden",
                                              var => "finish",
                                              var_label => "This is implemented as an external",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_q_labs",
                                              var => "q_labs",
                                              var_label => "This is implemented as an external",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_BACK2",
                                              type => "hidden",
                                              var => "BACK2",
                                              var_label => "This is implemented as an external",
                                            },
                                          ],
                        _external_info => {
                                            names    => ["finish", "q_labs", undef, "BACK2"],
                                            options  => {
                                                          "" => {
                                                                onclick => "document.q.finish.value='';",
                                                                type    => "SUBMIT",
                                                                value   => " SUBMIT ",
                                                              },
                                                          BACK2 => { name => "BACK2", type => "hidden" },
                                                          finish => { name => "finish", type => "hidden" },
                                                          q_labs => {},
                                                        },
                                            "values" => { "" => [" SUBMIT ", "NOT YET", " GO BACK "] },
                                          },
                        _label         => "LAST",
                        _opt           => { external => "last.htm", instr => "", scale => 0 },
                        _prompt        => "This is implemented as an external",
                        _qnum          => 10,
                        _qtype         => 7,
                        _scores        => [],
                        _setvalues     => [],
                        _skips         => [],
                        _vars          => [],
                      }, "TPerl::Survey::Question"),
                    ],
}, "TPerl::Survey")