#!/usr/bin/perl
# generated by TPerl::Parser::_config_file 
# Sat Dec 29 11:02:58 2012
$numq = 11;
$do_footer = '0';
$survey_name = 'Management and Leadership Inventory - manager/partner';
$one_at_a_time = '0';
$qscale = '<TABLE width="600"><TR><TD class="prompt">Please select the numbers which best describe <%fullname%>\'s management and leadership abilities, 1 being poor, 9 being excellent.  These ratings will be shared with <%firstname%> in a constructive manner.  Please be candid.</TD></TR></TABLE> <P><%q_label%>';
$block_size = '4';
$custom_footer = '<center><img src="/themes/ekit/ekit.daa.png" alt="Discipline, Accountability, Achievement" ></center>';
$focus_off = '1';
$no_copy = '1';
$plain = '1';
$no_progress_bar = '1';
$allow_restart = '1';
$qbanner = '<table border=0 cellpadding=0 cellspacing=0 class="bannertable"><tr><TD class="bannerlogo">&nbsp;<TD width="50px" >&nbsp;<tr><TD class="bluebar"> &nbsp;&nbsp; Management and Leadership Inventory<TH class="bluebarq">Q12</table>';
$textcolor = '#000000';
$theme = 'ekit';
$no_methods = '1';
$mailto = 'ctwebb@mapconsulting.com';
$style = 'plain';
$background = '';
$window_title = 'Q12 - Management and Leadership Inventory - manager/partner';
$do_body = '1';
$no_validation = '1';
$written_rows = '10';
$optional_written = '0';
$dive_in = '1';
$thankyou_url = 'thanks.htm';
$bg_color = '#FFFFFF';
$written_cols = '80';
$banner_top = '0';
1;
