version: "3"
services:
  web:
    build: ./server
    volumes:
      - ./server/app:/home/vhosts/ekit/htdocs
      - ./server/log:/var/log/apache2
    ports:
      - 8080:8080

  db:
    build: ./db
    volumes:
      - ./db/save_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fuel_dev
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    restart: always
    ports:
      - 3030:3030
    depends_on:
      - db

