#!/usr/bin/perl
# generated by TPerl::Parser::_config_file 
# Sat Dec 29 11:02:59 2012
$numq = 9;
$do_footer = '0';
$survey_name = 'Post Workshop Survey';
$one_at_a_time = '0';
$qscale = '<P>For the following questions please use the scale of 1 to 9 where 1 is Poor and 9 is Excellent.<P>If you are not sure or don\'t know, please use the NA option.<P><%q_label%>';
$block_size = '3';
$custom_footer = '<center><img src="/themes/ekit/ekit.daa.png" alt="Discipline, Accountability, Achievement" ></center>';
$no_copy = '1';
$plain = '1';
$no_progress_bar = '1';
$qbanner = '<table border=0 cellpadding=0 cellspacing=0 class="bannertable"><tr><TD class="bannerlogo">&nbsp;<TD width="50px" >&nbsp;<tr><TD class="bluebar"> &nbsp;&nbsp; Post Workshop Survey<TH class="bluebarq">Q26</table>';
$textcolor = '#000000';
$theme = 'ekit';
$no_methods = '1';
$mailto = 'ctwebb@mapconsulting.com';
$style = 'plain';
$background = '';
$window_title = 'MAP026 - Post Workshop Survey';
$do_body = '1';
$written_rows = '10';
$force_expand = '1';
$optional_written = '0';
$thankyou_url = 'thanks.htm';
$bg_color = '#FFFFFF';
$written_cols = '80';
$show_back_button = '1';
$banner_top = '0';
1;
