#!/usr/bin/perl
# generated by TPerl::Parser because it does not exist 
# Fri Jul 20 03:29:42 2007
# config2.pl should be hand edited for future quick hacks and overwrites etc.
@jump_index = (
		'q1.q3',
		'q4.q6',
		'q7.q9',
	);
%datalist = (
	Workshop => 'workshopdate',
	Leader => 'workshop_leader_name',
);
1;

