bless({
  _SID           => "MAP026",
  _TritonRoot    => "/home/vhosts/pwidev/triton",
  _config_subdir => "config",
  _data_subdir   => "web",
  _doc_root      => undef,
  _doc_subdir    => "doc",
  _final_subdir  => "final",
  _html_subdir   => "html",
  _masks         => {},
  _options       => {
                      block_size       => 3,
                      custom_footer    => "<center><img src=\"/themes/ekit/ekit.daa.png\" alt=\"Discipline, Accountability, Achievement\" ></center>",
                      force_expand     => 1,
                      mailto           => "ctwebb\@mapconsulting.com",
                      no_copy          => 1,
                      no_progress_bar  => 1,
                      one_at_a_time    => 0,
                      optional_written => 0,
                      qbanner          => "<table border=0 cellpadding=0 cellspacing=0 class=\"bannertable\"><tr><TD class=\"bannerlogo\">&nbsp;<TD width=\"50px\" >&nbsp;<tr><TD class=\"bluebar\"> &nbsp;&nbsp; Post Workshop Survey<TH class=\"bluebarq\">Q26</table>",
                      qscale           => "<P>For the following questions please use the scale of 1 to 9 where 1 is Poor and 9 is Excellent.<P>If you are not sure or don't know, please use the NA option.<P><%q_label%>",
                      show_back_button => 1,
                      survey_name      => "Post Workshop Survey",
                      thankyou_url     => "thanks.htm",
                      theme            => "ekit",
                      window_title     => "MAP026 - Post Workshop Survey",
                      written_cols     => 80,
                      written_rows     => 10,
                    },
  _questions     => [
                      bless({
                        _a_varnames  => [1, 2, 3],
                        _attributes  => [
                                          "1. The overall MAP experience so far",
                                          "2. Pre-workshop communication",
                                          "3. Feedback from within your organization",
                                        ],
                        _dataInfo    => [
                                          {
                                            "pos" => 0,
                                            rkey => "_Q1",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q1x1",
                                            var_label => "1. The overall MAP experience so far-<%qbanner%><%qscale%> Please rate the following aspects of your experience with MAP:",
                                          },
                                          {
                                            "pos" => 1,
                                            rkey => "_Q1",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q1x2",
                                            var_label => "2. Pre-workshop communication-<%qbanner%><%qscale%> Please rate the following aspects of your experience with MAP:",
                                          },
                                          {
                                            "pos" => 2,
                                            rkey => "_Q1",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q1x3",
                                            var_label => "3. Feedback from within your organization-<%qbanner%><%qscale%> Please rate the following aspects of your experience with MAP:",
                                          },
                                        ],
                        _g_varnames  => [1, 2, 3, 4, 5, 6, 7, 8, 9],
                        _label       => 1,
                        _opt         => {
                                          dk => "NA",
                                          instr => "",
                                          left_word => "Poor",
                                          middle => undef,
                                          required => "all",
                                          right_word => "Excellent",
                                          scale => -9,
                                        },
                        _prompt      => "<%qbanner%><%qscale%> Please rate the following aspects of your experience with MAP:",
                        _qnum        => 1,
                        _qtype       => 14,
                        _scale_words => [1, 2, 3, 4, 5, 6, 7, 8, 9, "NA"],
                        _scores      => [0, 0, 0],
                        _setvalues   => [undef, undef, undef],
                        _skips       => [undef, undef, undef],
                        _vars        => [undef, undef, undef],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames  => [4, 5],
                        _attributes  => ["4. Overall explanation of MMS", "5. Business goal setting"],
                        _dataInfo    => [
                                          {
                                            "pos" => 0,
                                            rkey => "_Q2",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q2x4",
                                            var_label => "4. Overall explanation of MMS-Please rate the presentation of the MAP Management System:",
                                          },
                                          {
                                            "pos" => 1,
                                            rkey => "_Q2",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q2x5",
                                            var_label => "5. Business goal setting-Please rate the presentation of the MAP Management System:",
                                          },
                                        ],
                        _g_varnames  => [1, 2, 3, 4, 5, 6, 7, 8, 9],
                        _label       => 2,
                        _opt         => {
                                          dk => "NA",
                                          instr => "",
                                          left_word => "Poor",
                                          middle => undef,
                                          right_word => "Excellent",
                                          scale => -9,
                                        },
                        _prompt      => "Please rate the presentation of the MAP Management System:",
                        _qnum        => 2,
                        _qtype       => 14,
                        _scale_words => [1, 2, 3, 4, 5, 6, 7, 8, 9, "NA"],
                        _scores      => [0, 0],
                        _setvalues   => [undef, undef],
                        _skips       => [undef, undef],
                        _vars        => [undef, undef],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames  => [6, 7, 8, 9, 10, 11, 12, 13],
                        _attributes  => [
                                          "6. Personal Growth Program",
                                          "7. Controlling",
                                          "8. Communicating",
                                          "9. Planning",
                                          "10. Organizing",
                                          "11. Time Management",
                                          "12. Staffing",
                                          "13. Leading",
                                        ],
                        _dataInfo    => [
                                          {
                                            "pos" => 0,
                                            rkey => "_Q3",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q3x6",
                                            var_label => "6. Personal Growth Program-Please rate the presentation of the MAP program modules:",
                                          },
                                          {
                                            "pos" => 1,
                                            rkey => "_Q3",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q3x7",
                                            var_label => "7. Controlling-Please rate the presentation of the MAP program modules:",
                                          },
                                          {
                                            "pos" => 2,
                                            rkey => "_Q3",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q3x8",
                                            var_label => "8. Communicating-Please rate the presentation of the MAP program modules:",
                                          },
                                          {
                                            "pos" => 3,
                                            rkey => "_Q3",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q3x9",
                                            var_label => "9. Planning-Please rate the presentation of the MAP program modules:",
                                          },
                                          {
                                            "pos" => 4,
                                            rkey => "_Q3",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q3x10",
                                            var_label => "10. Organizing-Please rate the presentation of the MAP program modules:",
                                          },
                                          {
                                            "pos" => 5,
                                            rkey => "_Q3",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q3x11",
                                            var_label => "11. Time Management-Please rate the presentation of the MAP program modules:",
                                          },
                                          {
                                            "pos" => 6,
                                            rkey => "_Q3",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q3x12",
                                            var_label => "12. Staffing-Please rate the presentation of the MAP program modules:",
                                          },
                                          {
                                            "pos" => 7,
                                            rkey => "_Q3",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q3x13",
                                            var_label => "13. Leading-Please rate the presentation of the MAP program modules:",
                                          },
                                        ],
                        _g_varnames  => [1, 2, 3, 4, 5, 6, 7, 8, 9],
                        _label       => 3,
                        _opt         => {
                                          dk => "NA",
                                          instr => "",
                                          left_word => "Poor",
                                          middle => undef,
                                          right_word => "Excellent",
                                          scale => -9,
                                        },
                        _prompt      => "Please rate the presentation of the MAP program modules:",
                        _qnum        => 3,
                        _qtype       => 14,
                        _scale_words => [1, 2, 3, 4, 5, 6, 7, 8, 9, "NA"],
                        _scores      => [0, 0, 0, 0, 0, 0, 0, 0],
                        _setvalues   => [undef, undef, undef, undef, undef, undef, undef, undef],
                        _skips       => [undef, undef, undef, undef, undef, undef, undef, undef],
                        _vars        => [undef, undef, undef, undef, undef, undef, undef, undef],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames  => [14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
                        _attributes  => [
                                          "14. Checklists / Handouts",
                                          "15. Wall Charts",
                                          "16. Video/slide presentation",
                                          "17. Life Planning",
                                          "18. Communication video",
                                          "19. Team consulting",
                                          "20. DISC Style Analysis",
                                          "21. FIRO-B",
                                          "22. Archer Team Project and Video Playback",
                                          "23. Hotel Facility",
                                          "24. Hotel Food Quality",
                                          "25. Hotel Service",
                                        ],
                        _dataInfo    => [
                                          {
                                            "pos" => 0,
                                            rkey => "_Q4",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q4x14",
                                            var_label => "14. Checklists / Handouts-<%qbanner%><%qscale%> Please rate the following:",
                                          },
                                          {
                                            "pos" => 1,
                                            rkey => "_Q4",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q4x15",
                                            var_label => "15. Wall Charts-<%qbanner%><%qscale%> Please rate the following:",
                                          },
                                          {
                                            "pos" => 2,
                                            rkey => "_Q4",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q4x16",
                                            var_label => "16. Video/slide presentation-<%qbanner%><%qscale%> Please rate the following:",
                                          },
                                          {
                                            "pos" => 3,
                                            rkey => "_Q4",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q4x17",
                                            var_label => "17. Life Planning-<%qbanner%><%qscale%> Please rate the following:",
                                          },
                                          {
                                            "pos" => 4,
                                            rkey => "_Q4",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q4x18",
                                            var_label => "18. Communication video-<%qbanner%><%qscale%> Please rate the following:",
                                          },
                                          {
                                            "pos" => 5,
                                            rkey => "_Q4",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q4x19",
                                            var_label => "19. Team consulting-<%qbanner%><%qscale%> Please rate the following:",
                                          },
                                          {
                                            "pos" => 6,
                                            rkey => "_Q4",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q4x20",
                                            var_label => "20. DISC Style Analysis-<%qbanner%><%qscale%> Please rate the following:",
                                          },
                                          {
                                            "pos" => 7,
                                            rkey => "_Q4",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q4x21",
                                            var_label => "21. FIRO-B-<%qbanner%><%qscale%> Please rate the following:",
                                          },
                                          {
                                            "pos" => 8,
                                            rkey => "_Q4",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q4x22",
                                            var_label => "22. Archer Team Project and Video Playback-<%qbanner%><%qscale%> Please rate the following:",
                                          },
                                          {
                                            "pos" => 9,
                                            rkey => "_Q4",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q4x23",
                                            var_label => "23. Hotel Facility-<%qbanner%><%qscale%> Please rate the following:",
                                          },
                                          {
                                            "pos" => 10,
                                            rkey => "_Q4",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q4x24",
                                            var_label => "24. Hotel Food Quality-<%qbanner%><%qscale%> Please rate the following:",
                                          },
                                          {
                                            "pos" => 11,
                                            rkey => "_Q4",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q4x25",
                                            var_label => "25. Hotel Service-<%qbanner%><%qscale%> Please rate the following:",
                                          },
                                        ],
                        _g_varnames  => [1, 2, 3, 4, 5, 6, 7, 8, 9],
                        _label       => 4,
                        _opt         => {
                                          dk => "NA",
                                          instr => "",
                                          left_word => "Poor",
                                          middle => undef,
                                          right_word => "Excellent",
                                          scale => -9,
                                        },
                        _prompt      => "<%qbanner%><%qscale%> Please rate the following:",
                        _qnum        => 4,
                        _qtype       => 14,
                        _scale_words => [1, 2, 3, 4, 5, 6, 7, 8, 9, "NA"],
                        _scores      => [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                        _setvalues   => [
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                        ],
                        _skips       => [
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                        ],
                        _vars        => [
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                        ],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames  => [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37],
                        _attributes  => [
                                          "26. Overall effectiveness",
                                          "27. Presentation skills overall",
                                          "28. Facilitated vs. lectured",
                                          "29. Knowledge of materials",
                                          "30. Keeping the workshop fast paced",
                                          "31. Encouraged and listened to participant's comments",
                                          "32. Making the workshop interesting",
                                          "33. Enthusiasm and confidence",
                                          "34. Sensitivity to needs of the group",
                                          "35. Asked challenging questions of the participants",
                                          "36. Balanced communication with participants",
                                          "37. Could help your organization achieve its goals",
                                        ],
                        _dataInfo    => [
                                          {
                                            "pos" => 0,
                                            rkey => "_Q5",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q5x26",
                                            var_label => "26. Overall effectiveness-Please rate your workshop leader on the following:",
                                          },
                                          {
                                            "pos" => 1,
                                            rkey => "_Q5",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q5x27",
                                            var_label => "27. Presentation skills overall-Please rate your workshop leader on the following:",
                                          },
                                          {
                                            "pos" => 2,
                                            rkey => "_Q5",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q5x28",
                                            var_label => "28. Facilitated vs. lectured-Please rate your workshop leader on the following:",
                                          },
                                          {
                                            "pos" => 3,
                                            rkey => "_Q5",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q5x29",
                                            var_label => "29. Knowledge of materials-Please rate your workshop leader on the following:",
                                          },
                                          {
                                            "pos" => 4,
                                            rkey => "_Q5",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q5x30",
                                            var_label => "30. Keeping the workshop fast paced-Please rate your workshop leader on the following:",
                                          },
                                          {
                                            "pos" => 5,
                                            rkey => "_Q5",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q5x31",
                                            var_label => "31. Encouraged and listened to participant's comments-Please rate your workshop leader on the following:",
                                          },
                                          {
                                            "pos" => 6,
                                            rkey => "_Q5",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q5x32",
                                            var_label => "32. Making the workshop interesting-Please rate your workshop leader on the following:",
                                          },
                                          {
                                            "pos" => 7,
                                            rkey => "_Q5",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q5x33",
                                            var_label => "33. Enthusiasm and confidence-Please rate your workshop leader on the following:",
                                          },
                                          {
                                            "pos" => 8,
                                            rkey => "_Q5",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q5x34",
                                            var_label => "34. Sensitivity to needs of the group-Please rate your workshop leader on the following:",
                                          },
                                          {
                                            "pos" => 9,
                                            rkey => "_Q5",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q5x35",
                                            var_label => "35. Asked challenging questions of the participants-Please rate your workshop leader on the following:",
                                          },
                                          {
                                            "pos" => 10,
                                            rkey => "_Q5",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q5x36",
                                            var_label => "36. Balanced communication with participants-Please rate your workshop leader on the following:",
                                          },
                                          {
                                            "pos" => 11,
                                            rkey => "_Q5",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q5x37",
                                            var_label => "37. Could help your organization achieve its goals-Please rate your workshop leader on the following:",
                                          },
                                        ],
                        _g_varnames  => [1, 2, 3, 4, 5, 6, 7, 8, 9],
                        _label       => 5,
                        _opt         => {
                                          dk => "NA",
                                          instr => "",
                                          left_word => "Poor",
                                          middle => undef,
                                          right_word => "Excellent",
                                          scale => -9,
                                        },
                        _prompt      => "Please rate your workshop leader on the following:",
                        _qnum        => 5,
                        _qtype       => 14,
                        _scale_words => [1, 2, 3, 4, 5, 6, 7, 8, 9, "NA"],
                        _scores      => [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                        _setvalues   => [
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                        ],
                        _skips       => [
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                        ],
                        _vars        => [
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                          undef,
                                        ],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames  => [38, 39, 40, 41, 42, 43],
                        _attributes  => [
                                          "38. Highly participative",
                                          "39. Life changing",
                                          "40. Practical",
                                          "41. Not intimidating",
                                          "42. Inspirational",
                                          "43. Very structured",
                                        ],
                        _dataInfo    => [
                                          {
                                            "pos" => 0,
                                            rkey => "_Q6",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q6x38",
                                            var_label => "38. Highly participative-Please rate the following attributes of the workshop:",
                                          },
                                          {
                                            "pos" => 1,
                                            rkey => "_Q6",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q6x39",
                                            var_label => "39. Life changing-Please rate the following attributes of the workshop:",
                                          },
                                          {
                                            "pos" => 2,
                                            rkey => "_Q6",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q6x40",
                                            var_label => "40. Practical-Please rate the following attributes of the workshop:",
                                          },
                                          {
                                            "pos" => 3,
                                            rkey => "_Q6",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q6x41",
                                            var_label => "41. Not intimidating-Please rate the following attributes of the workshop:",
                                          },
                                          {
                                            "pos" => 4,
                                            rkey => "_Q6",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q6x42",
                                            var_label => "42. Inspirational-Please rate the following attributes of the workshop:",
                                          },
                                          {
                                            "pos" => 5,
                                            rkey => "_Q6",
                                            val_if_true => "+1",
                                            val_label => {
                                                  1  => "1 Poor ",
                                                  2  => 2,
                                                  3  => 3,
                                                  4  => 4,
                                                  5  => 5,
                                                  6  => 6,
                                                  7  => 7,
                                                  8  => 8,
                                                  9  => "9 Excellent ",
                                                  10 => "NA",
                                                },
                                            var => "Q6x43",
                                            var_label => "43. Very structured-Please rate the following attributes of the workshop:",
                                          },
                                        ],
                        _g_varnames  => [1, 2, 3, 4, 5, 6, 7, 8, 9],
                        _label       => 6,
                        _opt         => {
                                          dk => "NA",
                                          instr => "",
                                          left_word => "Poor",
                                          middle => undef,
                                          right_word => "Excellent",
                                          scale => -9,
                                        },
                        _prompt      => "Please rate the following attributes of the workshop:",
                        _qnum        => 6,
                        _qtype       => 14,
                        _scale_words => [1, 2, 3, 4, 5, 6, 7, 8, 9, "NA"],
                        _scores      => [0, 0, 0, 0, 0, 0],
                        _setvalues   => [undef, undef, undef, undef, undef, undef],
                        _skips       => [undef, undef, undef, undef, undef, undef],
                        _vars        => [undef, undef, undef, undef, undef, undef],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [
                                         "Very long",
                                         "Moderately long",
                                         "Too short",
                                         "Moderately short",
                                         "Just right",
                                         "NA",
                                       ],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q7",
                                           val_if_true => "+1",
                                           val_label => {
                                                 1 => "Very long",
                                                 2 => "Moderately long",
                                                 3 => "Too short",
                                                 4 => "Moderately short",
                                                 5 => "Just right",
                                                 6 => "NA",
                                               },
                                           var => "Q7",
                                           var_label => "<%qbanner%> <P><%q_label%> The length of the workshop was:",
                                         },
                                       ],
                        _label      => 7,
                        _opt        => { instr => "", required => 0, scale => 0 },
                        _prompt     => "<%qbanner%> <P><%q_label%> The length of the workshop was:",
                        _qnum       => 7,
                        _qtype      => 3,
                        _scores     => [0, 0, 0, 0, 0, 0],
                        _setvalues  => [undef, undef, undef, undef, undef, undef],
                        _skips      => [undef, undef, undef, undef, undef, undef],
                        _vars       => [undef, undef, undef, undef, undef, undef],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q8",
                                           var => "Q8",
                                           var_label => "-What would you add, delete, or change about the workshop?",
                                         },
                                       ],
                        _label      => 8,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "What would you add, delete, or change about the workshop?",
                        _qnum       => 8,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q9",
                                           var => "Q9",
                                           var_label => "-What feedback do you have regarding your workshop leader?",
                                         },
                                       ],
                        _label      => 9,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "What feedback do you have regarding your workshop leader?",
                        _qnum       => 9,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                    ],
}, "TPerl::Survey")