bless({
  _SID           => "MAP011",
  _TritonRoot    => "/home/vhosts/pwidev/triton",
  _config_subdir => "config",
  _data_subdir   => "web",
  _doc_root      => undef,
  _doc_subdir    => "doc",
  _final_subdir  => "final",
  _html_subdir   => "html",
  _masks         => {},
  _options       => {
                      block_size       => 6,
                      custom_footer    => "<center><img src=\"/themes/ekit/ekit.daa.png\" alt=\"Discipline, Accountability, Achievement\" ></center>",
                      focus_off        => 1,
                      mailto           => "ctwebb\@mapconsulting.com",
                      no_copy          => 1,
                      no_progress_bar  => 1,
                      one_at_a_time    => 0,
                      optional_written => 0,
                      qbanner          => "<table border=0 cellpadding=0 cellspacing=0 class=\"bannertable\"><tr><TD class=\"bannerlogo\">&nbsp;<TD width=\"50px\" >&nbsp;<tr><TD class=\"bluebar\"> &nbsp;&nbsp;  Questionnaire for Supervising Manager or Partner<TH class=\"bluebarq\">Q11</table>",
                      qscale           => "<P><%q_label%>",
                      survey_name      => "Questionnaire for supervising manager or partner",
                      thankyou_url     => "thanks.htm",
                      theme            => "ekit",
                      window_title     => "Q11 - Questionnaire for supervising manager or partner",
                      written_cols     => 80,
                      written_rows     => 10,
                    },
  _questions     => [
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _code       => [
                                         "duedate=duedate",
                                         "id=id",
                                         "token=token",
                                         "login_page=login_page",
                                         "warning=warning",
                                         "ws_details=ws_details",
                                         "fullname=fullname",
                                         "firstname=firstname",
                                         "qbanner=qbanner",
                                         "qscale=qscale",
                                       ],
                        _dataInfo   => [],
                        _label      => "AA",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "",
                        _qnum       => 1,
                        _qtype      => 20,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _dataInfo   => [],
                        _label      => "A",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "<%qbanner%><TABLE width=\"600\"><TR><TD class=\"prompt\">As <%fullname%>'s supervising manager or partner, your candid and thoughtful answers to the following questions are critical in guiding us to help <%fullname%> achieve the goals of this program: increased productivity and overall management effectiveness.  Our staff discreetly uses this information.  However, certain comments may require anonymity.  Please designate those accordingly.</TD></TR></TABLE>",
                        _qnum       => 2,
                        _qtype      => 7,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q1",
                                           var => "Q1",
                                           var_label => "-Please describe the leadership/management strengths of <%fullname%>.",
                                         },
                                       ],
                        _label      => 1,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "Please describe the leadership/management strengths of <%fullname%>.",
                        _qnum       => 3,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q2",
                                           var => "Q2",
                                           var_label => "-Every leader/manager has opportunities for growth and improvement. What are the management <br>and/or leadership skills in which <%fullname%> could improve?",
                                         },
                                       ],
                        _label      => 2,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "Every leader/manager has opportunities for growth and improvement. What are the management <br>and/or leadership skills in which <%fullname%> could improve?",
                        _qnum       => 4,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q3",
                                           var => "Q3",
                                           var_label => "-What are <%fullname%>'s measurable performance goals (\$, #, %, etc.) for the next 12 months?",
                                         },
                                       ],
                        _label      => 3,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "What are <%fullname%>'s measurable performance goals (\$, #, %, etc.) for the next 12 months?",
                        _qnum       => 5,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q4",
                                           var => "Q4",
                                           var_label => "-What are <%fullname%>'s measurable performance goals (\$, #, %, etc.) that should be achieved within the <br>next 30 - 45 days?",
                                         },
                                       ],
                        _label      => 4,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "What are <%fullname%>'s measurable performance goals (\$, #, %, etc.) that should be achieved within the <br>next 30 - 45 days?",
                        _qnum       => 6,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q5",
                                           var => "Q5",
                                           var_label => "-What are the main challenges <%fullname%> must solve in order to achieve the above goals?",
                                         },
                                       ],
                        _label      => 5,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "What are the main challenges <%fullname%> must solve in order to achieve the above goals?",
                        _qnum       => 7,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q6",
                                           var => "Q6",
                                           var_label => "-<%qbanner%><P><%q_label%> What is the realistic personal career goal(s) for <%fullname%> within the organization?",
                                         },
                                       ],
                        _label      => 6,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "<%qbanner%><P><%q_label%> What is the realistic personal career goal(s) for <%fullname%> within the organization?",
                        _qnum       => 8,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q7",
                                           var => "Q7",
                                           var_label => "-What are the main COMMUNICATING challenges that <%fullname%> faces (e.g., style, effectiveness, <br>frequency, internal, external, etc.)?  <I>Please be specific.</I>",
                                         },
                                       ],
                        _label      => 7,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "What are the main COMMUNICATING challenges that <%fullname%> faces (e.g., style, effectiveness, <br>frequency, internal, external, etc.)?  <I>Please be specific.</I>",
                        _qnum       => 9,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q8",
                                           var => "Q8",
                                           var_label => "-What are the main PLANNING challenges <%fullname%> faces (e.g., no formal planning, unclear goals, <br>projects, etc.)?  <I>Please be specific.</I>",
                                         },
                                       ],
                        _label      => 8,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "What are the main PLANNING challenges <%fullname%> faces (e.g., no formal planning, unclear goals, <br>projects, etc.)?  <I>Please be specific.</I>",
                        _qnum       => 10,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q9",
                                           var => "Q9",
                                           var_label => "-What are the main ORGANIZING challenges <%fullname%> faces (e.g., personal organization, availability of <br>supplies, equipment, financial resources, time, organizational structure, etc.)?  <I>Please be specific.</I>",
                                         },
                                       ],
                        _label      => 9,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "What are the main ORGANIZING challenges <%fullname%> faces (e.g., personal organization, availability of <br>supplies, equipment, financial resources, time, organizational structure, etc.)?  <I>Please be specific.</I>",
                        _qnum       => 11,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q10",
                                           var => "Q10",
                                           var_label => "-What are the main STAFFING challenges <%fullname%> faces (e.g., recruiting, selecting right people, training, <br>development, retaining, etc.)?  <I>Please be specific.</I>",
                                         },
                                       ],
                        _label      => 10,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "What are the main STAFFING challenges <%fullname%> faces (e.g., recruiting, selecting right people, training, <br>development, retaining, etc.)?  <I>Please be specific.</I>",
                        _qnum       => 12,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q11",
                                           var => "Q11",
                                           var_label => "-What are the main CONTROLLING challenges <%fullname%> faces (e.g., accountability, follow-through, <br>taking corrective action, cost and inventory control, productivity, quality, etc.)?  <I>Please be specific.</I>",
                                         },
                                       ],
                        _label      => 11,
                        _opt        => { dk => undef, instr => "", required => 3, scale => 0 },
                        _prompt     => "What are the main CONTROLLING challenges <%fullname%> faces (e.g., accountability, follow-through, <br>taking corrective action, cost and inventory control, productivity, quality, etc.)?  <I>Please be specific.</I>",
                        _qnum       => 13,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q12",
                                           var => "Q12",
                                           var_label => "-<%qbanner%><P><%q_label%> What are the main LEADING challenges <%fullname%> faces (e.g., clear vision, motivation, teamwork, <br>initiating action, innovation, commitment to team goals, etc.)?<BR> <I>Please be specific.</I>",
                                         },
                                       ],
                        _label      => 12,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "<%qbanner%><P><%q_label%> What are the main LEADING challenges <%fullname%> faces (e.g., clear vision, motivation, teamwork, <br>initiating action, innovation, commitment to team goals, etc.)?<BR> <I>Please be specific.</I>",
                        _qnum       => 14,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q13",
                                           var => "Q13",
                                           var_label => "-What would you expect <%fullname%> to gain from this management process?  How will you know when <br>those expectations have been met?",
                                         },
                                       ],
                        _label      => 13,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "What would you expect <%fullname%> to gain from this management process?  How will you know when <br>those expectations have been met?",
                        _qnum       => 15,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _code       => [
                                         "my \$dcount = &count_data;",
                                         "&debug(\"Datacount = \$dcount\");",
                                         "if (\$dcount>0) {\$q_no = goto_qlab(\"LAST\") - 1;}",
                                         "if (\$dcount==0) {&db_conn;&db_set_status(\$survey_id,\$resp{id},\$resp{token},0,0)}",
                                       ],
                        _dataInfo   => [],
                        _label      => "CHECK",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "Check if we have enough data to allow submission of form",
                        _qnum       => 16,
                        _qtype      => 27,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames    => [],
                        _attributes    => [],
                        _dataInfo      => [
                                            {
                                              "pos" => 0,
                                              rkey => "ext_BACK2",
                                              type => "hidden",
                                              var => "BACK2",
                                              var_label => "See external page \"nodata.htm\"",
                                            },
                                          ],
                        _external_info => {
                                            names    => [undef, "BACK2"],
                                            options  => {
                                                          "" => {
                                                                alt => "HOME",
                                                                onclick => "document.location='/cgi-mr/pwikit_login.pl?id=<%id%>&password=<%token%>'",
                                                                tabindex => -1,
                                                                type => "BUTTON",
                                                                value => " HOME ",
                                                              },
                                                          BACK2 => { name => "BACK2", type => "hidden" },
                                                        },
                                            "values" => { "" => [" HOME ", " GO BACK "] },
                                          },
                        _label         => "NODATA",
                        _opt           => { external => "nodata.htm", instr => "", scale => 0 },
                        _prompt        => "See external page \"nodata.htm\"",
                        _qnum          => 17,
                        _qtype         => 7,
                        _scores        => [],
                        _setvalues     => [],
                        _skips         => [],
                        _vars          => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames    => [],
                        _attributes    => [],
                        _dataInfo      => [
                                            {
                                              "pos" => 0,
                                              rkey => "ext_finish",
                                              type => "hidden",
                                              var => "finish",
                                              var_label => "This is implemented as an external",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_q_labs",
                                              var => "q_labs",
                                              var_label => "This is implemented as an external",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_BACK2",
                                              type => "hidden",
                                              var => "BACK2",
                                              var_label => "This is implemented as an external",
                                            },
                                          ],
                        _external_info => {
                                            names    => ["finish", "q_labs", undef, "BACK2"],
                                            options  => {
                                                          "" => {
                                                                onclick => "document.q.finish.value='';",
                                                                type    => "SUBMIT",
                                                                value   => " SUBMIT ",
                                                              },
                                                          BACK2 => { name => "BACK2", type => "hidden" },
                                                          finish => { name => "finish", type => "hidden" },
                                                          q_labs => {},
                                                        },
                                            "values" => { "" => [" SUBMIT ", "NOT YET", " GO BACK "] },
                                          },
                        _label         => "LAST",
                        _opt           => { external => "last.htm", instr => "", scale => 0 },
                        _prompt        => "This is implemented as an external",
                        _qnum          => 18,
                        _qtype         => 7,
                        _scores        => [],
                        _setvalues     => [],
                        _skips         => [],
                        _vars          => [],
                      }, "TPerl::Survey::Question"),
                    ],
}, "TPerl::Survey")
