#!/bin/bash
#
#
cd /home/vhosts/ekit/scripts
perl pwikit_boss_stop_flag.pl
#
# Prevent any escalation or reminder messages being sent out
#
perl db.pl "update EMAIL_MSG_STATUS set done_epoch=999 where done_EPOCH is null and start_epoch>=CREATED_EPOCH+5"
#
# Insert new events into the event logs.  The files are synced 
# from puffin in roots crontab.
#perl maillog_events.pl --nosync
#
# Clean out old mli batch files
#
find ../triton/MAP101/html/admin/mli* -mtime +5 -exec rm {} \;

#
# Run the numbers for the online MAP Post Workshop survey
#
perl statsplit.pl MAP026 --is=3
perl recode.pl MAP026 -ini=recode -ext=all
# Sort the file by date and fix the date format
perl tsv_sortfile.pl ../triton/MAP026/final/MAP026_all_recode.txt ../triton/MAP026/final/MAP026_all_recode_sort.txt
perl tpivot.pl MAP026 -ini=wsexperience.ini
perl tpivot.pl MAP026 -ini=wspresentation.ini
perl tpivot.pl MAP026 -ini=wsgeneral.ini
perl tpivot.pl MAP026 -ini=wsleader.ini
perl tpivot.pl MAP026 -ini=wsworkshop.ini

