bless({
  _SID           => "MAP005",
  _TritonRoot    => "/home/vhosts/pwidev/triton",
  _config_subdir => "config",
  _data_subdir   => "web",
  _doc_root      => undef,
  _doc_subdir    => "doc",
  _final_subdir  => "final",
  _html_subdir   => "html",
  _masks         => {},
  _options       => {
                      block_size       => 5,
                      custom_footer    => "<center><img src=\"/themes/ekit/ekit.daa.png\" alt=\"Discipline, Accountability, Achievement\" ></center>",
                      focus_off        => 1,
                      mailto           => "ctwebb\@mapconsulting.com",
                      no_copy          => 1,
                      no_progress_bar  => 1,
                      one_at_a_time    => 0,
                      optional_written => 0,
                      qbanner          => "<table border=0 cellpadding=0 cellspacing=0 class=\"bannertable\"><tr><TD class=\"bannerlogo\">&nbsp;<TD width=\"50px\" >&nbsp;<tr><TD class=\"bluebar\"> &nbsp;&nbsp; Key Outside Influences List<TH class=\"bluebarq\">Q5</table>",
                      qscale           => "<P><%q_label%>",
                      survey_name      => "Key Outside Influences List",
                      thankyou_url     => "thanks.htm",
                      theme            => "ekit2",
                      window_title     => "MAP005 - Key Outside Influences",
                    },
  _questions     => [
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _code       => [
                                         "duedate=duedate",
                                         "id=id",
                                         "token=token",
                                         "login_page=login_page",
                                         "story=story",
                                         "qbanner=qbanner",
                                         "qscale=qscale",
                                       ],
                        _dataInfo   => [],
                        _label      => "AA",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "",
                        _qnum       => 1,
                        _qtype      => 20,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _dataInfo   => [],
                        _label      => "A",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "<%qbanner%>",
                        _qnum       => 2,
                        _qtype      => 7,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames    => [],
                        _attributes    => [],
                        _dataInfo      => [
                                            {
                                              "pos" => 0,
                                              rkey => "ext_q_labs",
                                              var => "q_labs",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_session",
                                              type => "hidden",
                                              var => "session",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 30,
                                              "pos" => 0,
                                              rkey => "ext_name1",
                                              type => "text",
                                              var => "name1",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 37,
                                              "pos" => 0,
                                              rkey => "ext_company1",
                                              type => "text",
                                              var => "company1",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 24,
                                              "pos" => 0,
                                              rkey => "ext_title1",
                                              type => "text",
                                              var => "title1",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_phone1",
                                              type => "text",
                                              var => "phone1",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 29,
                                              "pos" => 0,
                                              rkey => "ext_email1",
                                              type => "text",
                                              var => "email1",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 30,
                                              "pos" => 0,
                                              rkey => "ext_name2",
                                              type => "text",
                                              var => "name2",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 37,
                                              "pos" => 0,
                                              rkey => "ext_company2",
                                              type => "text",
                                              var => "company2",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 24,
                                              "pos" => 0,
                                              rkey => "ext_title2",
                                              type => "text",
                                              var => "title2",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_phone2",
                                              type => "text",
                                              var => "phone2",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 29,
                                              "pos" => 0,
                                              rkey => "ext_email2",
                                              type => "text",
                                              var => "email2",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 30,
                                              "pos" => 0,
                                              rkey => "ext_name3",
                                              type => "text",
                                              var => "name3",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 37,
                                              "pos" => 0,
                                              rkey => "ext_company3",
                                              type => "text",
                                              var => "company3",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 24,
                                              "pos" => 0,
                                              rkey => "ext_title3",
                                              type => "text",
                                              var => "title3",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_phone3",
                                              type => "text",
                                              var => "phone3",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 29,
                                              "pos" => 0,
                                              rkey => "ext_email3",
                                              type => "text",
                                              var => "email3",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 30,
                                              "pos" => 0,
                                              rkey => "ext_name4",
                                              type => "text",
                                              var => "name4",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 37,
                                              "pos" => 0,
                                              rkey => "ext_company4",
                                              type => "text",
                                              var => "company4",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 24,
                                              "pos" => 0,
                                              rkey => "ext_title4",
                                              type => "text",
                                              var => "title4",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_phone4",
                                              type => "text",
                                              var => "phone4",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 29,
                                              "pos" => 0,
                                              rkey => "ext_email4",
                                              type => "text",
                                              var => "email4",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 30,
                                              "pos" => 0,
                                              rkey => "ext_name5",
                                              type => "text",
                                              var => "name5",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 37,
                                              "pos" => 0,
                                              rkey => "ext_company5",
                                              type => "text",
                                              var => "company5",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 24,
                                              "pos" => 0,
                                              rkey => "ext_title5",
                                              type => "text",
                                              var => "title5",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_phone5",
                                              type => "text",
                                              var => "phone5",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 29,
                                              "pos" => 0,
                                              rkey => "ext_email5",
                                              type => "text",
                                              var => "email5",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 30,
                                              "pos" => 0,
                                              rkey => "ext_name6",
                                              type => "text",
                                              var => "name6",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 37,
                                              "pos" => 0,
                                              rkey => "ext_company6",
                                              type => "text",
                                              var => "company6",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 24,
                                              "pos" => 0,
                                              rkey => "ext_title6",
                                              type => "text",
                                              var => "title6",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_phone6",
                                              type => "text",
                                              var => "phone6",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 29,
                                              "pos" => 0,
                                              rkey => "ext_email6",
                                              type => "text",
                                              var => "email6",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 30,
                                              "pos" => 0,
                                              rkey => "ext_name7",
                                              type => "text",
                                              var => "name7",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 37,
                                              "pos" => 0,
                                              rkey => "ext_company7",
                                              type => "text",
                                              var => "company7",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 24,
                                              "pos" => 0,
                                              rkey => "ext_title7",
                                              type => "text",
                                              var => "title7",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_phone7",
                                              type => "text",
                                              var => "phone7",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 29,
                                              "pos" => 0,
                                              rkey => "ext_email7",
                                              type => "text",
                                              var => "email7",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 30,
                                              "pos" => 0,
                                              rkey => "ext_name8",
                                              type => "text",
                                              var => "name8",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 37,
                                              "pos" => 0,
                                              rkey => "ext_company8",
                                              type => "text",
                                              var => "company8",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 24,
                                              "pos" => 0,
                                              rkey => "ext_title8",
                                              type => "text",
                                              var => "title8",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_phone8",
                                              type => "text",
                                              var => "phone8",
                                              var_label => "Key Outside Influences List",
                                            },
                                            {
                                              "length" => 29,
                                              "pos" => 0,
                                              rkey => "ext_email8",
                                              type => "text",
                                              var => "email8",
                                              var_label => "Key Outside Influences List",
                                            },
                                          ],
                        _external_info => {
                                            names    => [
                                                          "q_labs",
                                                          "session",
                                                          "name1",
                                                          "company1",
                                                          "title1",
                                                          "phone1",
                                                          "email1",
                                                          "name2",
                                                          "company2",
                                                          "title2",
                                                          "phone2",
                                                          "email2",
                                                          "name3",
                                                          "company3",
                                                          "title3",
                                                          "phone3",
                                                          "email3",
                                                          "name4",
                                                          "company4",
                                                          "title4",
                                                          "phone4",
                                                          "email4",
                                                          "name5",
                                                          "company5",
                                                          "title5",
                                                          "phone5",
                                                          "email5",
                                                          "name6",
                                                          "company6",
                                                          "title6",
                                                          "phone6",
                                                          "email6",
                                                          "name7",
                                                          "company7",
                                                          "title7",
                                                          "phone7",
                                                          "email7",
                                                          "name8",
                                                          "company8",
                                                          "title8",
                                                          "phone8",
                                                          "email8",
                                                        ],
                                            options  => {
                                                          company1 => {
                                                                        class    => "input",
                                                                        name     => "company1",
                                                                        onchange => "yuk()",
                                                                        size     => 37,
                                                                        type     => "text",
                                                                      },
                                                          company2 => {
                                                                        class    => "input2",
                                                                        name     => "company2",
                                                                        onchange => "yuk()",
                                                                        size     => 37,
                                                                        type     => "text",
                                                                      },
                                                          company3 => {
                                                                        class    => "input",
                                                                        name     => "company3",
                                                                        onchange => "yuk()",
                                                                        size     => 37,
                                                                        type     => "text",
                                                                      },
                                                          company4 => {
                                                                        class    => "input2",
                                                                        name     => "company4",
                                                                        onchange => "yuk()",
                                                                        size     => 37,
                                                                        type     => "text",
                                                                      },
                                                          company5 => {
                                                                        class    => "input",
                                                                        name     => "company5",
                                                                        onchange => "yuk()",
                                                                        size     => 37,
                                                                        type     => "text",
                                                                      },
                                                          company6 => {
                                                                        class    => "input2",
                                                                        name     => "company6",
                                                                        onchange => "yuk()",
                                                                        size     => 37,
                                                                        type     => "text",
                                                                      },
                                                          company7 => {
                                                                        class    => "input",
                                                                        name     => "company7",
                                                                        onchange => "yuk()",
                                                                        size     => 37,
                                                                        type     => "text",
                                                                      },
                                                          company8 => {
                                                                        class    => "input2",
                                                                        name     => "company8",
                                                                        onchange => "yuk()",
                                                                        size     => 37,
                                                                        type     => "text",
                                                                      },
                                                          email1   => {
                                                                        class    => "input",
                                                                        name     => "email1",
                                                                        onchange => "yuk()",
                                                                        size     => 29,
                                                                        type     => "text",
                                                                      },
                                                          email2   => {
                                                                        class    => "input2",
                                                                        name     => "email2",
                                                                        onchange => "yuk()",
                                                                        size     => 29,
                                                                        type     => "text",
                                                                      },
                                                          email3   => {
                                                                        class    => "input",
                                                                        name     => "email3",
                                                                        onchange => "yuk()",
                                                                        size     => 29,
                                                                        type     => "text",
                                                                      },
                                                          email4   => {
                                                                        class    => "input2",
                                                                        name     => "email4",
                                                                        onchange => "yuk()",
                                                                        size     => 29,
                                                                        type     => "text",
                                                                      },
                                                          email5   => {
                                                                        class    => "input",
                                                                        name     => "email5",
                                                                        onchange => "yuk()",
                                                                        size     => 29,
                                                                        type     => "text",
                                                                      },
                                                          email6   => {
                                                                        class    => "input2",
                                                                        name     => "email6",
                                                                        onchange => "yuk()",
                                                                        size     => 29,
                                                                        type     => "text",
                                                                      },
                                                          email7   => {
                                                                        class    => "input",
                                                                        name     => "email7",
                                                                        onchange => "yuk()",
                                                                        size     => 29,
                                                                        type     => "text",
                                                                      },
                                                          email8   => {
                                                                        class    => "input2",
                                                                        name     => "email8",
                                                                        onchange => "yuk()",
                                                                        size     => 29,
                                                                        type     => "text",
                                                                      },
                                                          name1    => {
                                                                        class    => "input",
                                                                        name     => "name1",
                                                                        onchange => "yuk()",
                                                                        size     => 30,
                                                                        type     => "text",
                                                                      },
                                                          name2    => {
                                                                        class    => "input2",
                                                                        name     => "name2",
                                                                        onchange => "yuk()",
                                                                        size     => 30,
                                                                        type     => "text",
                                                                      },
                                                          name3    => {
                                                                        class    => "input",
                                                                        name     => "name3",
                                                                        onchange => "yuk()",
                                                                        size     => 30,
                                                                        type     => "text",
                                                                      },
                                                          name4    => {
                                                                        class    => "input2",
                                                                        name     => "name4",
                                                                        onchange => "yuk()",
                                                                        size     => 30,
                                                                        type     => "text",
                                                                      },
                                                          name5    => {
                                                                        class    => "input",
                                                                        name     => "name5",
                                                                        onchange => "yuk()",
                                                                        size     => 30,
                                                                        type     => "text",
                                                                      },
                                                          name6    => {
                                                                        class    => "input2",
                                                                        name     => "name6",
                                                                        onchange => "yuk()",
                                                                        size     => 30,
                                                                        type     => "text",
                                                                      },
                                                          name7    => {
                                                                        class    => "input",
                                                                        name     => "name7",
                                                                        onchange => "yuk()",
                                                                        size     => 30,
                                                                        type     => "text",
                                                                      },
                                                          name8    => {
                                                                        class    => "input2",
                                                                        name     => "name8",
                                                                        onchange => "yuk()",
                                                                        size     => 30,
                                                                        type     => "text",
                                                                      },
                                                          phone1   => {
                                                                        class    => "input",
                                                                        name     => "phone1",
                                                                        onchange => "yuk()",
                                                                        size     => 15,
                                                                        type     => "text",
                                                                      },
                                                          phone2   => {
                                                                        class    => "input2",
                                                                        name     => "phone2",
                                                                        onchange => "yuk()",
                                                                        size     => 15,
                                                                        type     => "text",
                                                                      },
                                                          phone3   => {
                                                                        class    => "input",
                                                                        name     => "phone3",
                                                                        onchange => "yuk()",
                                                                        size     => 15,
                                                                        type     => "text",
                                                                      },
                                                          phone4   => {
                                                                        class    => "input2",
                                                                        name     => "phone4",
                                                                        onchange => "yuk()",
                                                                        size     => 15,
                                                                        type     => "text",
                                                                      },
                                                          phone5   => {
                                                                        class    => "input",
                                                                        name     => "phone5",
                                                                        onchange => "yuk()",
                                                                        size     => 15,
                                                                        type     => "text",
                                                                      },
                                                          phone6   => {
                                                                        class    => "input2",
                                                                        name     => "phone6",
                                                                        onchange => "yuk()",
                                                                        size     => 15,
                                                                        type     => "text",
                                                                      },
                                                          phone7   => {
                                                                        class    => "input",
                                                                        name     => "phone7",
                                                                        onchange => "yuk()",
                                                                        size     => 15,
                                                                        type     => "text",
                                                                      },
                                                          phone8   => {
                                                                        class    => "input2",
                                                                        name     => "phone8",
                                                                        onchange => "yuk()",
                                                                        size     => 15,
                                                                        type     => "text",
                                                                      },
                                                          q_labs   => {},
                                                          session  => { name => "session", type => "hidden", value => "" },
                                                          title1   => {
                                                                        class    => "input",
                                                                        name     => "title1",
                                                                        onchange => "yuk()",
                                                                        size     => 24,
                                                                        type     => "text",
                                                                      },
                                                          title2   => {
                                                                        class    => "input2",
                                                                        name     => "title2",
                                                                        onchange => "yuk()",
                                                                        size     => 24,
                                                                        type     => "text",
                                                                      },
                                                          title3   => {
                                                                        class    => "input",
                                                                        name     => "title3",
                                                                        onchange => "yuk()",
                                                                        size     => 24,
                                                                        type     => "text",
                                                                      },
                                                          title4   => {
                                                                        class    => "input2",
                                                                        name     => "title4",
                                                                        onchange => "yuk()",
                                                                        size     => 24,
                                                                        type     => "text",
                                                                      },
                                                          title5   => {
                                                                        class    => "input",
                                                                        name     => "title5",
                                                                        onchange => "yuk()",
                                                                        size     => 24,
                                                                        type     => "text",
                                                                      },
                                                          title6   => {
                                                                        class    => "input2",
                                                                        name     => "title6",
                                                                        onchange => "yuk()",
                                                                        size     => 24,
                                                                        type     => "text",
                                                                      },
                                                          title7   => {
                                                                        class    => "input",
                                                                        name     => "title7",
                                                                        onchange => "yuk()",
                                                                        size     => 24,
                                                                        type     => "text",
                                                                      },
                                                          title8   => {
                                                                        class    => "input2",
                                                                        name     => "title8",
                                                                        onchange => "yuk()",
                                                                        size     => 24,
                                                                        type     => "text",
                                                                      },
                                                        },
                                            "values" => {},
                                          },
                        _label         => 1,
                        _opt           => {
                                            execute  => "pwikit_koilist_cgi.pl",
                                            external => "keyout.htm",
                                            instr    => "",
                                            required => "all",
                                            scale    => 0,
                                          },
                        _prompt        => "Key Outside Influences List",
                        _qnum          => 3,
                        _qtype         => 7,
                        _scores        => [],
                        _setvalues     => [],
                        _skips         => [],
                        _vars          => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
                        _dataInfo   => [
                                         {
                                           maskpos => { mask => 0 },
                                           "pos" => 0,
                                           rkey => "_Q2",
                                           val_if_true => 1,
                                           val_label => { 1 => 1 },
                                           var => "Q2x1",
                                           var_label => "1-Below is a list of the names you have provided. <P>We will send these people an email, telling them about your upcoming workshop. <P>Please select which of these people should receive emails now:",
                                         },
                                         {
                                           maskpos => { mask => 1 },
                                           "pos" => 1,
                                           rkey => "_Q2",
                                           val_if_true => 2,
                                           val_label => { 2 => 2 },
                                           var => "Q2x2",
                                           var_label => "2-Below is a list of the names you have provided. <P>We will send these people an email, telling them about your upcoming workshop. <P>Please select which of these people should receive emails now:",
                                         },
                                         {
                                           maskpos => { mask => 2 },
                                           "pos" => 2,
                                           rkey => "_Q2",
                                           val_if_true => 3,
                                           val_label => { 3 => 3 },
                                           var => "Q2x3",
                                           var_label => "3-Below is a list of the names you have provided. <P>We will send these people an email, telling them about your upcoming workshop. <P>Please select which of these people should receive emails now:",
                                         },
                                         {
                                           maskpos => { mask => 3 },
                                           "pos" => 3,
                                           rkey => "_Q2",
                                           val_if_true => 4,
                                           val_label => { 4 => 4 },
                                           var => "Q2x4",
                                           var_label => "4-Below is a list of the names you have provided. <P>We will send these people an email, telling them about your upcoming workshop. <P>Please select which of these people should receive emails now:",
                                         },
                                         {
                                           maskpos => { mask => 4 },
                                           "pos" => 4,
                                           rkey => "_Q2",
                                           val_if_true => 5,
                                           val_label => { 5 => 5 },
                                           var => "Q2x5",
                                           var_label => "5-Below is a list of the names you have provided. <P>We will send these people an email, telling them about your upcoming workshop. <P>Please select which of these people should receive emails now:",
                                         },
                                         {
                                           maskpos => { mask => 5 },
                                           "pos" => 5,
                                           rkey => "_Q2",
                                           val_if_true => 6,
                                           val_label => { 6 => 6 },
                                           var => "Q2x6",
                                           var_label => "6-Below is a list of the names you have provided. <P>We will send these people an email, telling them about your upcoming workshop. <P>Please select which of these people should receive emails now:",
                                         },
                                         {
                                           maskpos => { mask => 6 },
                                           "pos" => 6,
                                           rkey => "_Q2",
                                           val_if_true => 7,
                                           val_label => { 7 => 7 },
                                           var => "Q2x7",
                                           var_label => "7-Below is a list of the names you have provided. <P>We will send these people an email, telling them about your upcoming workshop. <P>Please select which of these people should receive emails now:",
                                         },
                                         {
                                           maskpos => { mask => 7 },
                                           "pos" => 7,
                                           rkey => "_Q2",
                                           val_if_true => 8,
                                           val_label => { 8 => 8 },
                                           var => "Q2x8",
                                           var_label => "8-Below is a list of the names you have provided. <P>We will send these people an email, telling them about your upcoming workshop. <P>Please select which of these people should receive emails now:",
                                         },
                                         {
                                           maskpos => { mask => 8 },
                                           "pos" => 8,
                                           rkey => "_Q2",
                                           val_if_true => 9,
                                           val_label => { 9 => 9 },
                                           var => "Q2x9",
                                           var_label => "9-Below is a list of the names you have provided. <P>We will send these people an email, telling them about your upcoming workshop. <P>Please select which of these people should receive emails now:",
                                         },
                                         {
                                           maskpos => { mask => 9 },
                                           "pos" => 9,
                                           rkey => "_Q2",
                                           val_if_true => 10,
                                           val_label => { 10 => 10 },
                                           var => "Q2x10",
                                           var_label => "10-Below is a list of the names you have provided. <P>We will send these people an email, telling them about your upcoming workshop. <P>Please select which of these people should receive emails now:",
                                         },
                                         {
                                           maskpos => { mask => 10 },
                                           "pos" => 10,
                                           rkey => "_Q2",
                                           val_if_true => 11,
                                           val_label => { 11 => 11 },
                                           var => "Q2x11",
                                           var_label => "11-Below is a list of the names you have provided. <P>We will send these people an email, telling them about your upcoming workshop. <P>Please select which of these people should receive emails now:",
                                         },
                                         {
                                           maskpos => { mask => 11 },
                                           "pos" => 11,
                                           rkey => "_Q2",
                                           val_if_true => 12,
                                           val_label => { 12 => 12 },
                                           var => "Q2x12",
                                           var_label => "12-Below is a list of the names you have provided. <P>We will send these people an email, telling them about your upcoming workshop. <P>Please select which of these people should receive emails now:",
                                         },
                                         {
                                           maskpos => { mask => 12 },
                                           "pos" => 12,
                                           rkey => "_Q2",
                                           val_if_true => 13,
                                           val_label => { 13 => 13 },
                                           var => "Q2x13",
                                           var_label => "13-Below is a list of the names you have provided. <P>We will send these people an email, telling them about your upcoming workshop. <P>Please select which of these people should receive emails now:",
                                         },
                                         {
                                           maskpos => { mask => 13 },
                                           "pos" => 13,
                                           rkey => "_Q2",
                                           val_if_true => 14,
                                           val_label => { 14 => 14 },
                                           var => "Q2x14",
                                           var_label => "14-Below is a list of the names you have provided. <P>We will send these people an email, telling them about your upcoming workshop. <P>Please select which of these people should receive emails now:",
                                         },
                                         {
                                           maskpos => { mask => 14 },
                                           "pos" => 14,
                                           rkey => "_Q2",
                                           val_if_true => 15,
                                           val_label => { 15 => 15 },
                                           var => "Q2x15",
                                           var_label => "15-Below is a list of the names you have provided. <P>We will send these people an email, telling them about your upcoming workshop. <P>Please select which of these people should receive emails now:",
                                         },
                                         {
                                           maskpos => { mask => 15 },
                                           "pos" => 15,
                                           rkey => "_Q2",
                                           val_if_true => 16,
                                           val_label => { 16 => 16 },
                                           var => "Q2x16",
                                           var_label => "16-Below is a list of the names you have provided. <P>We will send these people an email, telling them about your upcoming workshop. <P>Please select which of these people should receive emails now:",
                                         },
                                         {
                                           maskpos => { mask => 16 },
                                           "pos" => 16,
                                           rkey => "_Q2",
                                           val_if_true => 17,
                                           val_label => { 17 => 17 },
                                           var => "Q2x17",
                                           var_label => "17-Below is a list of the names you have provided. <P>We will send these people an email, telling them about your upcoming workshop. <P>Please select which of these people should receive emails now:",
                                         },
                                         {
                                           maskpos => { mask => 17 },
                                           "pos" => 17,
                                           rkey => "_Q2",
                                           val_if_true => 18,
                                           val_label => { 18 => 18 },
                                           var => "Q2x18",
                                           var_label => "18-Below is a list of the names you have provided. <P>We will send these people an email, telling them about your upcoming workshop. <P>Please select which of these people should receive emails now:",
                                         },
                                         {
                                           maskpos => { mask => 18 },
                                           "pos" => 18,
                                           rkey => "_Q2",
                                           val_if_true => 19,
                                           val_label => { 19 => 19 },
                                           var => "Q2x19",
                                           var_label => "19-Below is a list of the names you have provided. <P>We will send these people an email, telling them about your upcoming workshop. <P>Please select which of these people should receive emails now:",
                                         },
                                         {
                                           maskpos => { mask => 19 },
                                           "pos" => 19,
                                           rkey => "_Q2",
                                           val_if_true => 20,
                                           val_label => { 20 => 20 },
                                           var => "Q2x20",
                                           var_label => "20-Below is a list of the names you have provided. <P>We will send these people an email, telling them about your upcoming workshop. <P>Please select which of these people should receive emails now:",
                                         },
                                       ],
                        _label      => 2,
                        _opt        => {
                                         execute      => "pwikit_koilist_cgi.pl",
                                         instr        => "Click the NEXT button below to send emails to the names checked above",
                                         mask_include => "peers",
                                         required     => 0,
                                         scale        => 0,
                                       },
                        _prompt     => "Below is a list of the names you have provided. <P>We will send these people an email, telling them about your upcoming workshop. <P>Please select which of these people should receive emails now:",
                        _qnum       => 4,
                        _qtype      => 2,
                        _scores     => [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                        _setvalues  => [
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                       ],
                        _skips      => [
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                       ],
                        _vars       => [
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                       ],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _dataInfo   => [],
                        _label      => "BREAK",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "",
                        _qnum       => 5,
                        _qtype      => 8,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _dataInfo   => [],
                        _label      => "SENT",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "<%qbanner%> <P> \$\$story You can come back and add to the list later if you wish.",
                        _qnum       => 6,
                        _qtype      => 7,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _code       => [
                                         "my \$dcount = &count_data;",
                                         "&debug(\"Datacount = \$dcount\");",
                                         "if (\$dcount>0) {\$q_no = goto_qlab(\"LAST\") - 1;}",
                                         "if (\$dcount==0) {&db_conn;&db_set_status(\$survey_id,\$resp{id},\$resp{token},0,0)};",
                                       ],
                        _dataInfo   => [],
                        _label      => "CHECK",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "Check if we have enough data to allow submission of form",
                        _qnum       => 7,
                        _qtype      => 27,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames    => [],
                        _attributes    => [],
                        _dataInfo      => [
                                            {
                                              "pos" => 0,
                                              rkey => "ext_BACK2",
                                              type => "hidden",
                                              var => "BACK2",
                                              var_label => "See external page \"nodata.htm\"",
                                            },
                                          ],
                        _external_info => {
                                            names    => [undef, "BACK2"],
                                            options  => {
                                                          "" => {
                                                                alt => "HOME",
                                                                onclick => "document.location='/cgi-mr/pwikit_login.pl?id=<%id%>&password=<%token%>'",
                                                                tabindex => -1,
                                                                type => "BUTTON",
                                                                value => " HOME ",
                                                              },
                                                          BACK2 => { name => "BACK2", type => "hidden" },
                                                        },
                                            "values" => { "" => [" HOME ", " GO BACK "] },
                                          },
                        _label         => "NODATA",
                        _opt           => { external => "nodata.htm", instr => "", scale => 0 },
                        _prompt        => "See external page \"nodata.htm\"",
                        _qnum          => 8,
                        _qtype         => 7,
                        _scores        => [],
                        _setvalues     => [],
                        _skips         => [],
                        _vars          => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames    => [],
                        _attributes    => [],
                        _dataInfo      => [
                                            {
                                              "pos" => 0,
                                              rkey => "ext_finish",
                                              type => "hidden",
                                              var => "finish",
                                              var_label => "This is implemented as an external",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_q_labs",
                                              var => "q_labs",
                                              var_label => "This is implemented as an external",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_BACK2",
                                              type => "hidden",
                                              var => "BACK2",
                                              var_label => "This is implemented as an external",
                                            },
                                          ],
                        _external_info => {
                                            names    => ["finish", "q_labs", undef, "BACK2"],
                                            options  => {
                                                          "" => {
                                                                onclick => "document.q.finish.value='';",
                                                                type    => "SUBMIT",
                                                                value   => " SUBMIT ",
                                                              },
                                                          BACK2 => { name => "BACK2", type => "hidden" },
                                                          finish => { name => "finish", type => "hidden" },
                                                          q_labs => {},
                                                        },
                                            "values" => { "" => [" SUBMIT ", "NOT YET", " GO BACK "] },
                                          },
                        _label         => "LAST",
                        _opt           => { external => "last.htm", instr => "", scale => 0 },
                        _prompt        => "This is implemented as an external",
                        _qnum          => 9,
                        _qtype         => 7,
                        _scores        => [],
                        _setvalues     => [],
                        _skips         => [],
                        _vars          => [],
                      }, "TPerl::Survey::Question"),
                    ],
}, "TPerl::Survey")