#!/usr/bin/perl
#	$Id: db_get.pl,v 1.2 2007/05/11 01:50:56 triton Exp $
#
# CGI script called to get data from the database
# Requests for data are handled in a single CGI request 

use strict;
use CGI::Carp qw(fatalsToBrowser);
use Data::Dumper;

use TPerl::MyDB;
use TPerl::CGI;
use TPerl::TSV;
use TPerl::TritonConfig;

#
# Definitions and constants
#

#
# Start of main code
#
my $q = new TPerl::CGI;
my %args = $q->args;
my $debug = $args{debug};

print "Content-type: text/plain\n\n";

my $dbh = dbh TPerl::MyDB(debug=>$debug) or
    die "Canna connect to db ". TPerl::MyDB->err();

# Error generating code (for testing purposes)
if (0)
	{
	print "<H2>Testing error 911 (call Homer for help) generated by server process</h2><P> Please remove debugging code\n";
#	x=2;
	exit(1);
	}
#
# Get on with the business:
#
my $sql = qq{$args{sql}};
print "Executing SQL statement: $sql\n" if ($debug);
my $th = $dbh->prepare($sql) || die "Cannot prepare SQL statement: $DBI::errstr\n";
#
$th->execute() || die "Cannot prepare SQL statement: $DBI::errstr\n";
my $line = 0;
while (my $href = $th->fetchrow_arrayref)
	{
	print join("~~~",@ {$th->{NAME}})."```" if ($line == 0);
	print join("~~~",@ {$href})."```";
	$line++;
	}
$th->finish;
print "*** END OF FILE *** \n";
1;
