bless({
  _SID           => "MAP008",
  _TritonRoot    => "/home/vhosts/pwidev/triton",
  _config_subdir => "config",
  _data_subdir   => "web",
  _doc_root      => undef,
  _doc_subdir    => "doc",
  _final_subdir  => "final",
  _html_subdir   => "html",
  _masks         => {},
  _options       => {
                      block_size       => 5,
                      custom_footer    => "<center><img src=\"/themes/ekit/ekit.daa.png\" alt=\"Discipline, Accountability, Achievement\" ></center>",
                      focus_off        => 1,
                      mailto           => "ctwebb\@mapconsulting.com",
                      no_copy          => 1,
                      no_progress_bar  => 1,
                      one_at_a_time    => 0,
                      optional_written => 0,
                      qbanner          => "<table border=0 cellpadding=0 cellspacing=0 class=\"bannertable\"><tr><TD class=\"bannerlogo\">&nbsp;<TD width=\"50px\" >&nbsp;<tr><TD class=\"bluebar\"> &nbsp;&nbsp; Organizational Summary<TH class=\"bluebarq\">Q8</table>",
                      qscale           => "<P><%q_label%>",
                      survey_name      => "Organizational Summary",
                      thankyou_url     => "thanks.htm",
                      theme            => "ekit",
                      window_title     => "Q8 - Organizational Summary",
                    },
  _questions     => [
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _code       => [
                                         "duedate=duedate",
                                         "id=id",
                                         "token=token",
                                         "returnfax=returnfax",
                                         "adminemail=adminemail",
                                         "ws_details=ws_details",
                                         "warning=warning",
                                         "qbanner=qbanner",
                                         "qscale=qscale",
                                       ],
                        _dataInfo   => [],
                        _label      => "AA",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "",
                        _qnum       => 1,
                        _qtype      => 20,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _dataInfo   => [],
                        _label      => "A",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "<%qbanner%>",
                        _qnum       => 2,
                        _qtype      => 7,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [
                                         "Type of business/institution:",
                                         "Number of employees:",
                                         "Annual revenue, sales or budget:",
                                         "Annual profit or surplus:",
                                       ],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q1-0",
                                           var => "Q1x1",
                                           var_label => "Type of business/institution:-General information",
                                         },
                                         {
                                           "pos" => 0,
                                           rkey => "_Q1-1",
                                           var => "Q1x2",
                                           var_label => "Number of employees:-General information",
                                         },
                                         {
                                           "pos" => 0,
                                           rkey => "_Q1-2",
                                           var => "Q1x3",
                                           var_label => "Annual revenue, sales or budget:-General information",
                                         },
                                         {
                                           "pos" => 0,
                                           rkey => "_Q1-3",
                                           var => "Q1x4",
                                           var_label => "Annual profit or surplus:-General information",
                                         },
                                       ],
                        _label      => 1,
                        _opt        => { instr => "", required => 0, scale => 0 },
                        _prompt     => "General information",
                        _qnum       => 3,
                        _qtype      => 15,
                        _scores     => [0, 0, 0, 0],
                        _setvalues  => [undef, undef, undef, undef],
                        _skips      => [undef, undef, undef, undef],
                        _vars       => [undef, undef, undef, undef],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q2",
                                           var => "Q2",
                                           var_label => "-Please list the major business goals for the organization in the next three years.",
                                         },
                                       ],
                        _label      => 2,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "Please list the major business goals for the organization in the next three years.",
                        _qnum       => 4,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q3",
                                           var => "Q3",
                                           var_label => "-Please list your own major professional goals over the next three years.",
                                         },
                                       ],
                        _label      => 3,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "Please list your own major professional goals over the next three years.",
                        _qnum       => 5,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => ["A", "B", "C"],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q4-0",
                                           var => "Q4x1",
                                           var_label => "A-What obstacles must you overcome to achieve the goals for your organization?",
                                         },
                                         {
                                           "pos" => 0,
                                           rkey => "_Q4-1",
                                           var => "Q4x2",
                                           var_label => "B-What obstacles must you overcome to achieve the goals for your organization?",
                                         },
                                         {
                                           "pos" => 0,
                                           rkey => "_Q4-2",
                                           var => "Q4x3",
                                           var_label => "C-What obstacles must you overcome to achieve the goals for your organization?",
                                         },
                                       ],
                        _label      => 4,
                        _opt        => { instr => "", required => 0, scale => 0 },
                        _prompt     => "What obstacles must you overcome to achieve the goals for your organization?",
                        _qnum       => 6,
                        _qtype      => 15,
                        _scores     => [0, 0, 0],
                        _setvalues  => [undef, undef, undef],
                        _skips      => [undef, undef, undef],
                        _vars       => [undef, undef, undef],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => ["A", "B", "C"],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q5-0",
                                           var => "Q5x1",
                                           var_label => "A-<%qbanner%><P><%q_label%> What obstacles must you overcome to achieve your own professional goals?",
                                         },
                                         {
                                           "pos" => 0,
                                           rkey => "_Q5-1",
                                           var => "Q5x2",
                                           var_label => "B-<%qbanner%><P><%q_label%> What obstacles must you overcome to achieve your own professional goals?",
                                         },
                                         {
                                           "pos" => 0,
                                           rkey => "_Q5-2",
                                           var => "Q5x3",
                                           var_label => "C-<%qbanner%><P><%q_label%> What obstacles must you overcome to achieve your own professional goals?",
                                         },
                                       ],
                        _label      => 5,
                        _opt        => { instr => "", required => 0, scale => 0 },
                        _prompt     => "<%qbanner%><P><%q_label%> What obstacles must you overcome to achieve your own professional goals?",
                        _qnum       => 7,
                        _qtype      => 15,
                        _scores     => [0, 0, 0],
                        _setvalues  => [undef, undef, undef],
                        _skips      => [undef, undef, undef],
                        _vars       => [undef, undef, undef],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => ["x"],
                        _dataInfo   => [],
                        _label      => 6,
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "On a separate sheet of paper, diagram your present organization structure.&nbsp; (Attach a chart if you have it.&nbsp; <br>Please include on it the names of key people and their respective positions.)&nbsp; You can fax this to us <br>at \$\$returnfax, email it to <a href=\"mailto:ctwebb\@mapconsulting.com\">ctwebb\@mapconsulting.com</a>, or you can mail it to <p>Cathy Webb, <br>14140 Ventura Boulevard, <br>Suite 208, <br>Sherman Oaks, <br>CA 91423.",
                        _qnum       => 8,
                        _qtype      => 7,
                        _scores     => [0],
                        _setvalues  => [undef],
                        _skips      => [7],
                        _vars       => [undef],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames    => [],
                        _attributes    => [],
                        _dataInfo      => [
                                            {
                                              "pos" => 0,
                                              rkey => "ext_q_labs",
                                              var => "q_labs",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_session",
                                              type => "hidden",
                                              var => "session",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_name1",
                                              type => "text",
                                              var => "name1",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_position1",
                                              type => "text",
                                              var => "position1",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_strength1",
                                              type => "text",
                                              var => "strength1",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_improve1",
                                              type => "text",
                                              var => "improve1",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_name2",
                                              type => "text",
                                              var => "name2",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_position2",
                                              type => "text",
                                              var => "position2",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_strength2",
                                              type => "text",
                                              var => "strength2",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_improve2",
                                              type => "text",
                                              var => "improve2",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_name3",
                                              type => "text",
                                              var => "name3",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_position3",
                                              type => "text",
                                              var => "position3",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_strength3",
                                              type => "text",
                                              var => "strength3",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_improve3",
                                              type => "text",
                                              var => "improve3",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_name4",
                                              type => "text",
                                              var => "name4",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_position4",
                                              type => "text",
                                              var => "position4",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_strength4",
                                              type => "text",
                                              var => "strength4",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_improve4",
                                              type => "text",
                                              var => "improve4",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_name5",
                                              type => "text",
                                              var => "name5",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_position5",
                                              type => "text",
                                              var => "position5",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_strength5",
                                              type => "text",
                                              var => "strength5",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_improve5",
                                              type => "text",
                                              var => "improve5",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_name6",
                                              type => "text",
                                              var => "name6",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_position6",
                                              type => "text",
                                              var => "position6",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_strength6",
                                              type => "text",
                                              var => "strength6",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_improve6",
                                              type => "text",
                                              var => "improve6",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_name7",
                                              type => "text",
                                              var => "name7",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_position7",
                                              type => "text",
                                              var => "position7",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_strength7",
                                              type => "text",
                                              var => "strength7",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_improve7",
                                              type => "text",
                                              var => "improve7",
                                              var_label => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                                            },
                                          ],
                        _external_info => {
                                            names    => [
                                                          "q_labs",
                                                          "session",
                                                          "name1",
                                                          "position1",
                                                          "strength1",
                                                          "improve1",
                                                          "name2",
                                                          "position2",
                                                          "strength2",
                                                          "improve2",
                                                          "name3",
                                                          "position3",
                                                          "strength3",
                                                          "improve3",
                                                          "name4",
                                                          "position4",
                                                          "strength4",
                                                          "improve4",
                                                          "name5",
                                                          "position5",
                                                          "strength5",
                                                          "improve5",
                                                          "name6",
                                                          "position6",
                                                          "strength6",
                                                          "improve6",
                                                          "name7",
                                                          "position7",
                                                          "strength7",
                                                          "improve7",
                                                        ],
                                            options  => {
                                                          improve1  => {
                                                                         class    => "input",
                                                                         name     => "improve1",
                                                                         onchange => "yuk(this)",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                          improve2  => {
                                                                         class    => "input",
                                                                         name     => "improve2",
                                                                         onchange => "yuk()",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                          improve3  => {
                                                                         class    => "input",
                                                                         name     => "improve3",
                                                                         onchange => "yuk()",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                          improve4  => {
                                                                         class    => "input",
                                                                         name     => "improve4",
                                                                         onchange => "yuk()",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                          improve5  => {
                                                                         class    => "input",
                                                                         name     => "improve5",
                                                                         onchange => "yuk()",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                          improve6  => {
                                                                         class    => "input",
                                                                         name     => "improve6",
                                                                         onchange => "yuk()",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                          improve7  => {
                                                                         class    => "input",
                                                                         name     => "improve7",
                                                                         onchange => "yuk()",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                          name1     => {
                                                                         class    => "input",
                                                                         name     => "name1",
                                                                         onchange => "yuk(this)",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                          name2     => {
                                                                         class    => "input",
                                                                         name     => "name2",
                                                                         onchange => "yuk()",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                          name3     => {
                                                                         class    => "input",
                                                                         name     => "name3",
                                                                         onchange => "yuk()",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                          name4     => {
                                                                         class    => "input",
                                                                         name     => "name4",
                                                                         onchange => "yuk()",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                          name5     => {
                                                                         class    => "input",
                                                                         name     => "name5",
                                                                         onchange => "yuk()",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                          name6     => {
                                                                         class    => "input",
                                                                         name     => "name6",
                                                                         onchange => "yuk()",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                          name7     => {
                                                                         class    => "input",
                                                                         name     => "name7",
                                                                         onchange => "yuk()",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                          position1 => {
                                                                         class    => "input",
                                                                         name     => "position1",
                                                                         onchange => "yuk(this)",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                          position2 => {
                                                                         class    => "input",
                                                                         name     => "position2",
                                                                         onchange => "yuk()",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                          position3 => {
                                                                         class    => "input",
                                                                         name     => "position3",
                                                                         onchange => "yuk()",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                          position4 => {
                                                                         class    => "input",
                                                                         name     => "position4",
                                                                         onchange => "yuk()",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                          position5 => {
                                                                         class    => "input",
                                                                         name     => "position5",
                                                                         onchange => "yuk()",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                          position6 => {
                                                                         class    => "input",
                                                                         name     => "position6",
                                                                         onchange => "yuk()",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                          position7 => {
                                                                         class    => "input",
                                                                         name     => "position7",
                                                                         onchange => "yuk()",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                          q_labs    => {},
                                                          session   => { name => "session", type => "hidden", value => "" },
                                                          strength1 => {
                                                                         class    => "input",
                                                                         name     => "strength1",
                                                                         onchange => "yuk(this)",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                          strength2 => {
                                                                         class    => "input",
                                                                         name     => "strength2",
                                                                         onchange => "yuk()",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                          strength3 => {
                                                                         class    => "input",
                                                                         name     => "strength3",
                                                                         onchange => "yuk()",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                          strength4 => {
                                                                         class    => "input",
                                                                         name     => "strength4",
                                                                         onchange => "yuk()",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                          strength5 => {
                                                                         class    => "input",
                                                                         name     => "strength5",
                                                                         onchange => "yuk()",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                          strength6 => {
                                                                         class    => "input",
                                                                         name     => "strength6",
                                                                         onchange => "yuk()",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                          strength7 => {
                                                                         class    => "input",
                                                                         name     => "strength7",
                                                                         onchange => "yuk()",
                                                                         size     => 20,
                                                                         type     => "text",
                                                                       },
                                                        },
                                            "values" => {},
                                          },
                        _label         => 7,
                        _opt           => { external => "keyppl.htm", instr => "", scale => 0 },
                        _prompt        => "describe the main strengths and opportunities for improvement of the key people in your own senior management team:",
                        _qnum          => 9,
                        _qtype         => 7,
                        _scores        => [],
                        _setvalues     => [],
                        _skips         => [],
                        _vars          => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames    => [],
                        _attributes    => [],
                        _dataInfo      => [
                                            {
                                              "pos" => 0,
                                              rkey => "ext_q_labs",
                                              var => "q_labs",
                                              var_label => "Branch offices, affiliates satelites or divisions (Name of unit/Location/Phone/Person in charge)",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_session",
                                              type => "hidden",
                                              var => "session",
                                              var_label => "Branch offices, affiliates satelites or divisions (Name of unit/Location/Phone/Person in charge)",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_unit1",
                                              type => "text",
                                              var => "unit1",
                                              var_label => "Branch offices, affiliates satelites or divisions (Name of unit/Location/Phone/Person in charge)",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_location1",
                                              type => "text",
                                              var => "location1",
                                              var_label => "Branch offices, affiliates satelites or divisions (Name of unit/Location/Phone/Person in charge)",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_phone1",
                                              type => "text",
                                              var => "phone1",
                                              var_label => "Branch offices, affiliates satelites or divisions (Name of unit/Location/Phone/Person in charge)",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_incharge1",
                                              type => "text",
                                              var => "incharge1",
                                              var_label => "Branch offices, affiliates satelites or divisions (Name of unit/Location/Phone/Person in charge)",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_unit2",
                                              type => "text",
                                              var => "unit2",
                                              var_label => "Branch offices, affiliates satelites or divisions (Name of unit/Location/Phone/Person in charge)",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_location2",
                                              type => "text",
                                              var => "location2",
                                              var_label => "Branch offices, affiliates satelites or divisions (Name of unit/Location/Phone/Person in charge)",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_phone2",
                                              type => "text",
                                              var => "phone2",
                                              var_label => "Branch offices, affiliates satelites or divisions (Name of unit/Location/Phone/Person in charge)",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_incharge2",
                                              type => "text",
                                              var => "incharge2",
                                              var_label => "Branch offices, affiliates satelites or divisions (Name of unit/Location/Phone/Person in charge)",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_unit3",
                                              type => "text",
                                              var => "unit3",
                                              var_label => "Branch offices, affiliates satelites or divisions (Name of unit/Location/Phone/Person in charge)",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_location3",
                                              type => "text",
                                              var => "location3",
                                              var_label => "Branch offices, affiliates satelites or divisions (Name of unit/Location/Phone/Person in charge)",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_phone3",
                                              type => "text",
                                              var => "phone3",
                                              var_label => "Branch offices, affiliates satelites or divisions (Name of unit/Location/Phone/Person in charge)",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_incharge3",
                                              type => "text",
                                              var => "incharge3",
                                              var_label => "Branch offices, affiliates satelites or divisions (Name of unit/Location/Phone/Person in charge)",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_unit4",
                                              type => "text",
                                              var => "unit4",
                                              var_label => "Branch offices, affiliates satelites or divisions (Name of unit/Location/Phone/Person in charge)",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_location4",
                                              type => "text",
                                              var => "location4",
                                              var_label => "Branch offices, affiliates satelites or divisions (Name of unit/Location/Phone/Person in charge)",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_phone4",
                                              type => "text",
                                              var => "phone4",
                                              var_label => "Branch offices, affiliates satelites or divisions (Name of unit/Location/Phone/Person in charge)",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_incharge4",
                                              type => "text",
                                              var => "incharge4",
                                              var_label => "Branch offices, affiliates satelites or divisions (Name of unit/Location/Phone/Person in charge)",
                                            },
                                          ],
                        _external_info => {
                                            names    => [
                                                          "q_labs",
                                                          "session",
                                                          "unit1",
                                                          "location1",
                                                          "phone1",
                                                          "incharge1",
                                                          "unit2",
                                                          "location2",
                                                          "phone2",
                                                          "incharge2",
                                                          "unit3",
                                                          "location3",
                                                          "phone3",
                                                          "incharge3",
                                                          "unit4",
                                                          "location4",
                                                          "phone4",
                                                          "incharge4",
                                                        ],
                                            options  => {
                                                          incharge1 => { class => "input", name => "incharge1", onchange => "yuk()", type => "text" },
                                                          incharge2 => { class => "input", name => "incharge2", onchange => "yuk()", type => "text" },
                                                          incharge3 => { class => "input", name => "incharge3", onchange => "yuk()", type => "text" },
                                                          incharge4 => { class => "input", name => "incharge4", onchange => "yuk()", type => "text" },
                                                          location1 => { class => "input", name => "location1", onchange => "yuk()", type => "text" },
                                                          location2 => { class => "input", name => "location2", onchange => "yuk()", type => "text" },
                                                          location3 => { class => "input", name => "location3", onchange => "yuk()", type => "text" },
                                                          location4 => { class => "input", name => "location4", onchange => "yuk()", type => "text" },
                                                          phone1    => { class => "input", name => "phone1", onchange => "yuk()", type => "text" },
                                                          phone2    => { class => "input", name => "phone2", onchange => "yuk()", type => "text" },
                                                          phone3    => { class => "input", name => "phone3", onchange => "yuk()", type => "text" },
                                                          phone4    => { class => "input", name => "phone4", onchange => "yuk()", type => "text" },
                                                          q_labs    => {},
                                                          session   => { name => "session", type => "hidden", value => "" },
                                                          unit1     => { class => "input", name => "unit1", onchange => "yuk()", type => "text" },
                                                          unit2     => { class => "input", name => "unit2", onchange => "yuk()", type => "text" },
                                                          unit3     => { class => "input", name => "unit3", onchange => "yuk()", type => "text" },
                                                          unit4     => { class => "input", name => "unit4", onchange => "yuk()", type => "text" },
                                                        },
                                            "values" => {},
                                          },
                        _label         => 8,
                        _opt           => { external => "branches.htm", instr => "", scale => 0 },
                        _prompt        => "Branch offices, affiliates satelites or divisions (Name of unit/Location/Phone/Person in charge)",
                        _qnum          => 10,
                        _qtype         => 7,
                        _scores        => [],
                        _setvalues     => [],
                        _skips         => [],
                        _vars          => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _code       => [
                                         "my \$dcount = &count_data;",
                                         "&debug(\"Datacount = \$dcount\");",
                                         "if (\$dcount>0) {\$q_no = goto_qlab(\"LAST\") - 1;}",
                                         "if (\$dcount==0) {&db_conn;&db_set_status(\$survey_id,\$resp{id},\$resp{token},0,0)}",
                                       ],
                        _dataInfo   => [],
                        _label      => "CHECK",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "Check if we have enough data to allow submission of form",
                        _qnum       => 11,
                        _qtype      => 27,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames    => [],
                        _attributes    => [],
                        _dataInfo      => [
                                            {
                                              "pos" => 0,
                                              rkey => "ext_BACK2",
                                              type => "hidden",
                                              var => "BACK2",
                                              var_label => "See external page \"nodata.htm\"",
                                            },
                                          ],
                        _external_info => {
                                            names    => [undef, "BACK2"],
                                            options  => {
                                                          "" => {
                                                                alt => "HOME",
                                                                onclick => "document.location='/cgi-mr/pwikit_login.pl?id=<%id%>&password=<%token%>'",
                                                                tabindex => -1,
                                                                type => "BUTTON",
                                                                value => " HOME ",
                                                              },
                                                          BACK2 => { name => "BACK2", type => "hidden" },
                                                        },
                                            "values" => { "" => [" HOME ", " GO BACK "] },
                                          },
                        _label         => "NODATA",
                        _opt           => { external => "nodata.htm", instr => "", scale => 0 },
                        _prompt        => "See external page \"nodata.htm\"",
                        _qnum          => 12,
                        _qtype         => 7,
                        _scores        => [],
                        _setvalues     => [],
                        _skips         => [],
                        _vars          => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames    => [],
                        _attributes    => [],
                        _dataInfo      => [
                                            {
                                              "pos" => 0,
                                              rkey => "ext_finish",
                                              type => "hidden",
                                              var => "finish",
                                              var_label => "This is implemented as an external",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_q_labs",
                                              var => "q_labs",
                                              var_label => "This is implemented as an external",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_BACK2",
                                              type => "hidden",
                                              var => "BACK2",
                                              var_label => "This is implemented as an external",
                                            },
                                          ],
                        _external_info => {
                                            names    => ["finish", "q_labs", undef, "BACK2"],
                                            options  => {
                                                          "" => {
                                                                onclick => "document.q.finish.value='';",
                                                                type    => "SUBMIT",
                                                                value   => " SUBMIT ",
                                                              },
                                                          BACK2 => { name => "BACK2", type => "hidden" },
                                                          finish => { name => "finish", type => "hidden" },
                                                          q_labs => {},
                                                        },
                                            "values" => { "" => [" SUBMIT ", "NOT YET", " GO BACK "] },
                                          },
                        _label         => "LAST",
                        _opt           => { external => "last.htm", instr => "", scale => 0 },
                        _prompt        => "This is implemented as an external",
                        _qnum          => 13,
                        _qtype         => 7,
                        _scores        => [],
                        _setvalues     => [],
                        _skips         => [],
                        _vars          => [],
                      }, "TPerl::Survey::Question"),
                    ],
}, "TPerl::Survey")