#!/usr/bin/perl
# generated by TPerl::Parser::_config_file 
# Sat Dec 29 11:02:55 2012
$numq = 12;
$do_footer = '0';
$survey_name = 'Management and Leadership Inventory: Participant';
$one_at_a_time = '0';
$qscale = '<TABLE width="600px"><TR><TD class="prompt">Please select the numbers which best describe your management and leadership abilities, 1 being poor, 9 being excellent.  Your supervising manager or partner will complete the same form and the comparative results will be used as a coaching tool.  Please be candid and frank.</TD></TR></TABLE><P><%q_label%>';
$block_size = '4';
$custom_footer = '<center><img src="/themes/ekit/ekit.daa.png" alt="Discipline, Accountability, Achievement" ></center>';
$focus_off = '1';
$no_copy = '1';
$plain = '1';
$no_progress_bar = '1';
$qbanner = '<table border=0 cellpadding=0 cellspacing=0 class="bannertable"><tr><TD class="bannerlogo">&nbsp;<TD width="50px" >&nbsp;<tr><TD class="bluebar"> &nbsp;&nbsp; Management And Leadership Inventory<TH class="bluebarq">Q2</table>';
$textcolor = '#000000';
$theme = 'ekit';
$no_methods = '1';
$mailto = 'ctwebb@mapconsulting.com';
$style = 'plain';
$background = '';
$window_title = 'Q2 - Management and Leadership Inventory: Participant';
$do_body = '1';
$no_validation = '1';
$optional_written = '0';
$thankyou_url = 'thanks.htm';
$bg_color = '#FFFFFF';
$banner_top = '0';
1;
