bless({
  _SID           => "MAP002",
  _TritonRoot    => "/home/vhosts/pwidev/triton",
  _config_subdir => "config",
  _data_subdir   => "web",
  _doc_root      => undef,
  _doc_subdir    => "doc",
  _final_subdir  => "final",
  _html_subdir   => "html",
  _masks         => {},
  _options       => {
                      block_size       => 4,
                      custom_footer    => "<center><img src=\"/themes/ekit/ekit.daa.png\" alt=\"Discipline, Accountability, Achievement\" ></center>",
                      focus_off        => 1,
                      mailto           => "ctwebb\@mapconsulting.com",
                      no_copy          => 1,
                      no_progress_bar  => 1,
                      no_validation    => 1,
                      one_at_a_time    => 0,
                      optional_written => 0,
                      qbanner          => "<table border=0 cellpadding=0 cellspacing=0 class=\"bannertable\"><tr><TD class=\"bannerlogo\">&nbsp;<TD width=\"50px\" >&nbsp;<tr><TD class=\"bluebar\"> &nbsp;&nbsp; Management And Leadership Inventory<TH class=\"bluebarq\">Q2</table>",
                      qscale           => "<TABLE width=\"600px\"><TR><TD class=\"prompt\">Please select the numbers which best describe your management and leadership abilities, 1 being poor, 9 being excellent.  Your supervising manager or partner will complete the same form and the comparative results will be used as a coaching tool.  Please be candid and frank.</TD></TR></TABLE><P><%q_label%>",
                      survey_name      => "Management and Leadership Inventory: Participant",
                      thankyou_url     => "thanks.htm",
                      theme            => "ekit",
                      window_title     => "Q2 - Management and Leadership Inventory: Participant",
                    },
  _questions     => [
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _code       => [
                                         "duedate=duedate",
                                         "id=id",
                                         "token=token",
                                         "login_page=login_page",
                                         "warning=warning",
                                         "ws_details=ws_details",
                                         "qbanner=qbanner",
                                         "qscale=qscale",
                                       ],
                        _dataInfo   => [],
                        _label      => "A",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "",
                        _qnum       => 1,
                        _qtype      => 20,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [
                                         "Speaking one-on-one",
                                         "Speaking in groups",
                                         "Writing skills",
                                         "Listening",
                                         "Relating to supervising manager/partner",
                                         "Relating to peers",
                                         "Relating to direct reports",
                                       ],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q1",
                                           val_if_true => "+1",
                                           val_label => {
                                                 1 => "1 Poor Average",
                                                 2 => 2,
                                                 3 => 3,
                                                 4 => 4,
                                                 5 => 5,
                                                 6 => 6,
                                                 7 => 7,
                                                 8 => 8,
                                                 9 => "9 Excellent Average",
                                               },
                                           var => "Q1x1",
                                           var_label => "Speaking one-on-one-<BOGUS><%qbanner%><%qscale%> Communicating Abilities (Ability to convey meaning and obtain understanding).",
                                         },
                                         {
                                           "pos" => 1,
                                           rkey => "_Q1",
                                           val_if_true => "+1",
                                           val_label => {
                                                 1 => "1 Poor Average",
                                                 2 => 2,
                                                 3 => 3,
                                                 4 => 4,
                                                 5 => 5,
                                                 6 => 6,
                                                 7 => 7,
                                                 8 => 8,
                                                 9 => "9 Excellent Average",
                                               },
                                           var => "Q1x2",
                                           var_label => "Speaking in groups-<BOGUS><%qbanner%><%qscale%> Communicating Abilities (Ability to convey meaning and obtain understanding).",
                                         },
                                         {
                                           "pos" => 2,
                                           rkey => "_Q1",
                                           val_if_true => "+1",
                                           val_label => {
                                                 1 => "1 Poor Average",
                                                 2 => 2,
                                                 3 => 3,
                                                 4 => 4,
                                                 5 => 5,
                                                 6 => 6,
                                                 7 => 7,
                                                 8 => 8,
                                                 9 => "9 Excellent Average",
                                               },
                                           var => "Q1x3",
                                           var_label => "Writing skills-<BOGUS><%qbanner%><%qscale%> Communicating Abilities (Ability to convey meaning and obtain understanding).",
                                         },
                                         {
                                           "pos" => 3,
                                           rkey => "_Q1",
                                           val_if_true => "+1",
                                           val_label => {
                                                 1 => "1 Poor Average",
                                                 2 => 2,
                                                 3 => 3,
                                                 4 => 4,
                                                 5 => 5,
                                                 6 => 6,
                                                 7 => 7,
                                                 8 => 8,
                                                 9 => "9 Excellent Average",
                                               },
                                           var => "Q1x4",
                                           var_label => "Listening-<BOGUS><%qbanner%><%qscale%> Communicating Abilities (Ability to convey meaning and obtain understanding).",
                                         },
                                         {
                                           "pos" => 4,
                                           rkey => "_Q1",
                                           val_if_true => "+1",
                                           val_label => {
                                                 1 => "1 Poor Average",
                                                 2 => 2,
                                                 3 => 3,
                                                 4 => 4,
                                                 5 => 5,
                                                 6 => 6,
                                                 7 => 7,
                                                 8 => 8,
                                                 9 => "9 Excellent Average",
                                               },
                                           var => "Q1x5",
                                           var_label => "Relating to supervising manager/partner-<BOGUS><%qbanner%><%qscale%> Communicating Abilities (Ability to convey meaning and obtain understanding).",
                                         },
                                         {
                                           "pos" => 5,
                                           rkey => "_Q1",
                                           val_if_true => "+1",
                                           val_label => {
                                                 1 => "1 Poor Average",
                                                 2 => 2,
                                                 3 => 3,
                                                 4 => 4,
                                                 5 => 5,
                                                 6 => 6,
                                                 7 => 7,
                                                 8 => 8,
                                                 9 => "9 Excellent Average",
                                               },
                                           var => "Q1x6",
                                           var_label => "Relating to peers-<BOGUS><%qbanner%><%qscale%> Communicating Abilities (Ability to convey meaning and obtain understanding).",
                                         },
                                         {
                                           "pos" => 6,
                                           rkey => "_Q1",
                                           val_if_true => "+1",
                                           val_label => {
                                                 1 => "1 Poor Average",
                                                 2 => 2,
                                                 3 => 3,
                                                 4 => 4,
                                                 5 => 5,
                                                 6 => 6,
                                                 7 => 7,
                                                 8 => 8,
                                                 9 => "9 Excellent Average",
                                               },
                                           var => "Q1x7",
                                           var_label => "Relating to direct reports-<BOGUS><%qbanner%><%qscale%> Communicating Abilities (Ability to convey meaning and obtain understanding).",
                                         },
                                       ],
                        _label      => 1,
                        _opt        => {
                                         dk => undef,
                                         instr => "",
                                         left_word => "Poor",
                                         middle => "Average",
                                         required => 2,
                                         right_word => "Excellent",
                                         scale => 9,
                                       },
                        _prompt     => "<BOGUS><%qbanner%><%qscale%> Communicating Abilities (Ability to convey meaning and obtain understanding).",
                        _qnum       => 2,
                        _qtype      => 14,
                        _scores     => [0, 0, 0, 0, 0, 0, 0],
                        _setvalues  => [undef, undef, undef, undef, undef, undef, undef],
                        _skips      => [undef, undef, undef, undef, undef, undef, undef],
                        _vars       => [undef, undef, undef, undef, undef, undef, undef],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [
                                         "Foreseeing problems and opportunities",
                                         "Analyzing problems and facts",
                                         "Setting clear, measurable goals",
                                         "Developing strategies",
                                         "Scheduling work and planning time",
                                       ],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q2",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q2x1",
                                           var_label => "Foreseeing problems and opportunities-Planning Abilities (Ability to develop goals and strategies for future action).",
                                         },
                                         {
                                           "pos" => 1,
                                           rkey => "_Q2",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q2x2",
                                           var_label => "Analyzing problems and facts-Planning Abilities (Ability to develop goals and strategies for future action).",
                                         },
                                         {
                                           "pos" => 2,
                                           rkey => "_Q2",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q2x3",
                                           var_label => "Setting clear, measurable goals-Planning Abilities (Ability to develop goals and strategies for future action).",
                                         },
                                         {
                                           "pos" => 3,
                                           rkey => "_Q2",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q2x4",
                                           var_label => "Developing strategies-Planning Abilities (Ability to develop goals and strategies for future action).",
                                         },
                                         {
                                           "pos" => 4,
                                           rkey => "_Q2",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q2x5",
                                           var_label => "Scheduling work and planning time-Planning Abilities (Ability to develop goals and strategies for future action).",
                                         },
                                       ],
                        _label      => 2,
                        _opt        => {
                                         dk => undef,
                                         instr => "",
                                         left_word => "Poor",
                                         middle => undef,
                                         required => 2,
                                         right_word => "Excellent",
                                         scale => 9,
                                       },
                        _prompt     => "Planning Abilities (Ability to develop goals and strategies for future action).",
                        _qnum       => 3,
                        _qtype      => 14,
                        _scores     => [0, 0, 0, 0, 0],
                        _setvalues  => [undef, undef, undef, undef, undef],
                        _skips      => [undef, undef, undef, undef, undef],
                        _vars       => [undef, undef, undef, undef, undef],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [
                                         "Allocating resources",
                                         "Coordinating the work of others",
                                         "Sorting the vital from the less important",
                                         "Delegating",
                                         "Each team member understands job responsibilities",
                                       ],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q3",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q3x1",
                                           var_label => "Allocating resources-Organizing Abilities (Ability to align work and resources productively in relation to goals).",
                                         },
                                         {
                                           "pos" => 1,
                                           rkey => "_Q3",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q3x2",
                                           var_label => "Coordinating the work of others-Organizing Abilities (Ability to align work and resources productively in relation to goals).",
                                         },
                                         {
                                           "pos" => 2,
                                           rkey => "_Q3",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q3x3",
                                           var_label => "Sorting the vital from the less important-Organizing Abilities (Ability to align work and resources productively in relation to goals).",
                                         },
                                         {
                                           "pos" => 3,
                                           rkey => "_Q3",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q3x4",
                                           var_label => "Delegating-Organizing Abilities (Ability to align work and resources productively in relation to goals).",
                                         },
                                         {
                                           "pos" => 4,
                                           rkey => "_Q3",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q3x5",
                                           var_label => "Each team member understands job responsibilities-Organizing Abilities (Ability to align work and resources productively in relation to goals).",
                                         },
                                       ],
                        _label      => 3,
                        _opt        => {
                                         dk => undef,
                                         instr => "",
                                         left_word => "Poor",
                                         middle => undef,
                                         required => "all",
                                         right_word => "Excellent",
                                         scale => 9,
                                       },
                        _prompt     => "Organizing Abilities (Ability to align work and resources productively in relation to goals).",
                        _qnum       => 4,
                        _qtype      => 14,
                        _scores     => [0, 0, 0, 0, 0],
                        _setvalues  => [undef, undef, undef, undef, undef],
                        _skips      => [undef, undef, undef, undef, undef],
                        _vars       => [undef, undef, undef, undef, undef],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [
                                         "Aligning staffing needs with company goals",
                                         "Recruiting",
                                         "Selecting the right people",
                                         "Providing training opportunities",
                                         "Retaining people",
                                         "Developing potential in people",
                                       ],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q4",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q4x1",
                                           var_label => "Aligning staffing needs with company goals-Staffing Abilities (Ability to recruit, select, develop and retain people).",
                                         },
                                         {
                                           "pos" => 1,
                                           rkey => "_Q4",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q4x2",
                                           var_label => "Recruiting-Staffing Abilities (Ability to recruit, select, develop and retain people).",
                                         },
                                         {
                                           "pos" => 2,
                                           rkey => "_Q4",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q4x3",
                                           var_label => "Selecting the right people-Staffing Abilities (Ability to recruit, select, develop and retain people).",
                                         },
                                         {
                                           "pos" => 3,
                                           rkey => "_Q4",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q4x4",
                                           var_label => "Providing training opportunities-Staffing Abilities (Ability to recruit, select, develop and retain people).",
                                         },
                                         {
                                           "pos" => 4,
                                           rkey => "_Q4",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q4x5",
                                           var_label => "Retaining people-Staffing Abilities (Ability to recruit, select, develop and retain people).",
                                         },
                                         {
                                           "pos" => 5,
                                           rkey => "_Q4",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q4x6",
                                           var_label => "Developing potential in people-Staffing Abilities (Ability to recruit, select, develop and retain people).",
                                         },
                                       ],
                        _label      => 4,
                        _opt        => {
                                         dk => undef,
                                         instr => "",
                                         left_word => "Poor",
                                         middle => undef,
                                         required => "all",
                                         right_word => "Excellent",
                                         scale => 9,
                                       },
                        _prompt     => "Staffing Abilities (Ability to recruit, select, develop and retain people).",
                        _qnum       => 5,
                        _qtype      => 14,
                        _scores     => [0, 0, 0, 0, 0, 0],
                        _setvalues  => [undef, undef, undef, undef, undef, undef],
                        _skips      => [undef, undef, undef, undef, undef, undef],
                        _vars       => [undef, undef, undef, undef, undef, undef],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [
                                         "Setting standards",
                                         "Assessing performance",
                                         "Following through",
                                         "Holding people accountable",
                                         "Taking corrective action",
                                       ],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q5",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q5x1",
                                           var_label => "Setting standards-<%qbanner%><%qscale%> Controlling Abilities (Measuring performance and taking appropriate action).",
                                         },
                                         {
                                           "pos" => 1,
                                           rkey => "_Q5",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q5x2",
                                           var_label => "Assessing performance-<%qbanner%><%qscale%> Controlling Abilities (Measuring performance and taking appropriate action).",
                                         },
                                         {
                                           "pos" => 2,
                                           rkey => "_Q5",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q5x3",
                                           var_label => "Following through-<%qbanner%><%qscale%> Controlling Abilities (Measuring performance and taking appropriate action).",
                                         },
                                         {
                                           "pos" => 3,
                                           rkey => "_Q5",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q5x4",
                                           var_label => "Holding people accountable-<%qbanner%><%qscale%> Controlling Abilities (Measuring performance and taking appropriate action).",
                                         },
                                         {
                                           "pos" => 4,
                                           rkey => "_Q5",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q5x5",
                                           var_label => "Taking corrective action-<%qbanner%><%qscale%> Controlling Abilities (Measuring performance and taking appropriate action).",
                                         },
                                       ],
                        _label      => 5,
                        _opt        => {
                                         dk => undef,
                                         instr => "",
                                         left_word => "Poor",
                                         middle => undef,
                                         required => "all",
                                         right_word => "Excellent",
                                         scale => 9,
                                       },
                        _prompt     => "<%qbanner%><%qscale%> Controlling Abilities (Measuring performance and taking appropriate action).",
                        _qnum       => 6,
                        _qtype      => 14,
                        _scores     => [0, 0, 0, 0, 0],
                        _setvalues  => [undef, undef, undef, undef, undef],
                        _skips      => [undef, undef, undef, undef, undef],
                        _vars       => [undef, undef, undef, undef, undef],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [
                                         "Causes a high level of teamwork",
                                         "Commits self to team goals",
                                         "Gives support to others' programs",
                                         "Coordinates with others to achieve goals",
                                       ],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q6",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q6x1",
                                           var_label => "Causes a high level of teamwork-Teamwork Abilities (Ability to work together to  achieve common goals).",
                                         },
                                         {
                                           "pos" => 1,
                                           rkey => "_Q6",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q6x2",
                                           var_label => "Commits self to team goals-Teamwork Abilities (Ability to work together to  achieve common goals).",
                                         },
                                         {
                                           "pos" => 2,
                                           rkey => "_Q6",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q6x3",
                                           var_label => "Gives support to others' programs-Teamwork Abilities (Ability to work together to  achieve common goals).",
                                         },
                                         {
                                           "pos" => 3,
                                           rkey => "_Q6",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q6x4",
                                           var_label => "Coordinates with others to achieve goals-Teamwork Abilities (Ability to work together to  achieve common goals).",
                                         },
                                       ],
                        _label      => 6,
                        _opt        => {
                                         dk => undef,
                                         instr => "",
                                         left_word => "Poor",
                                         middle => undef,
                                         required => "all",
                                         right_word => "Excellent",
                                         scale => 9,
                                       },
                        _prompt     => "Teamwork Abilities (Ability to work together to  achieve common goals).",
                        _qnum       => 7,
                        _qtype      => 14,
                        _scores     => [0, 0, 0, 0],
                        _setvalues  => [undef, undef, undef, undef],
                        _skips      => [undef, undef, undef, undef],
                        _vars       => [undef, undef, undef, undef],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [
                                         "Clearly communicates vision and values",
                                         "Demonstrates determination and relentless resolve",
                                         "Demonstrates integrity",
                                         "Shows confidence",
                                         "Develops trust",
                                         "Is an excellent coach and mentor",
                                         "Inspires continuous improvement",
                                         "Demonstrates personal humility",
                                         "Demonstrates passion and commitment",
                                         "Confronts difficult issues and finds resolution",
                                         "Attracts strong people to the organization",
                                         "Maintains the focus of the organization",
                                         "Each team member has clear, quantifiable goals",
                                         "Demonstrates empathy",
                                         "Encourages excellence",
                                         "Job duties of the team are aligned with the organization's direction",
                                         "Discovers and develops the strengths of others",
                                         "Embraces and implements change",
                                       ],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q7",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q7x1",
                                           var_label => "Clearly communicates vision and values-Leading Abilities (Ability to inspire people to achieve goals).",
                                         },
                                         {
                                           "pos" => 1,
                                           rkey => "_Q7",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q7x2",
                                           var_label => "Demonstrates determination and relentless resolve-Leading Abilities (Ability to inspire people to achieve goals).",
                                         },
                                         {
                                           "pos" => 2,
                                           rkey => "_Q7",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q7x3",
                                           var_label => "Demonstrates integrity-Leading Abilities (Ability to inspire people to achieve goals).",
                                         },
                                         {
                                           "pos" => 3,
                                           rkey => "_Q7",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q7x4",
                                           var_label => "Shows confidence-Leading Abilities (Ability to inspire people to achieve goals).",
                                         },
                                         {
                                           "pos" => 4,
                                           rkey => "_Q7",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q7x5",
                                           var_label => "Develops trust-Leading Abilities (Ability to inspire people to achieve goals).",
                                         },
                                         {
                                           "pos" => 5,
                                           rkey => "_Q7",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q7x6",
                                           var_label => "Is an excellent coach and mentor-Leading Abilities (Ability to inspire people to achieve goals).",
                                         },
                                         {
                                           "pos" => 6,
                                           rkey => "_Q7",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q7x7",
                                           var_label => "Inspires continuous improvement-Leading Abilities (Ability to inspire people to achieve goals).",
                                         },
                                         {
                                           "pos" => 7,
                                           rkey => "_Q7",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q7x8",
                                           var_label => "Demonstrates personal humility-Leading Abilities (Ability to inspire people to achieve goals).",
                                         },
                                         {
                                           "pos" => 8,
                                           rkey => "_Q7",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q7x9",
                                           var_label => "Demonstrates passion and commitment-Leading Abilities (Ability to inspire people to achieve goals).",
                                         },
                                         {
                                           "pos" => 9,
                                           rkey => "_Q7",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q7x10",
                                           var_label => "Confronts difficult issues and finds resolution-Leading Abilities (Ability to inspire people to achieve goals).",
                                         },
                                         {
                                           "pos" => 10,
                                           rkey => "_Q7",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q7x11",
                                           var_label => "Attracts strong people to the organization-Leading Abilities (Ability to inspire people to achieve goals).",
                                         },
                                         {
                                           "pos" => 11,
                                           rkey => "_Q7",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q7x12",
                                           var_label => "Maintains the focus of the organization-Leading Abilities (Ability to inspire people to achieve goals).",
                                         },
                                         {
                                           "pos" => 12,
                                           rkey => "_Q7",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q7x13",
                                           var_label => "Each team member has clear, quantifiable goals-Leading Abilities (Ability to inspire people to achieve goals).",
                                         },
                                         {
                                           "pos" => 13,
                                           rkey => "_Q7",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q7x14",
                                           var_label => "Demonstrates empathy-Leading Abilities (Ability to inspire people to achieve goals).",
                                         },
                                         {
                                           "pos" => 14,
                                           rkey => "_Q7",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q7x15",
                                           var_label => "Encourages excellence-Leading Abilities (Ability to inspire people to achieve goals).",
                                         },
                                         {
                                           "pos" => 15,
                                           rkey => "_Q7",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q7x16",
                                           var_label => "Job duties of the team are aligned with the organization's direction-Leading Abilities (Ability to inspire people to achieve goals).",
                                         },
                                         {
                                           "pos" => 16,
                                           rkey => "_Q7",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q7x17",
                                           var_label => "Discovers and develops the strengths of others-Leading Abilities (Ability to inspire people to achieve goals).",
                                         },
                                         {
                                           "pos" => 17,
                                           rkey => "_Q7",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q7x18",
                                           var_label => "Embraces and implements change-Leading Abilities (Ability to inspire people to achieve goals).",
                                         },
                                       ],
                        _label      => 7,
                        _opt        => {
                                         dk => undef,
                                         instr => "",
                                         left_word => "Poor",
                                         middle => undef,
                                         required => "all",
                                         right_word => "Excellent",
                                         scale => 9,
                                       },
                        _prompt     => "Leading Abilities (Ability to inspire people to achieve goals).",
                        _qnum       => 8,
                        _qtype      => 14,
                        _scores     => [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                        _setvalues  => [
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                       ],
                        _skips      => [
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                       ],
                        _vars       => [
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                       ],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _code       => [
                                         "my \$dcount = &count_data;",
                                         "&debug(\"Datacount = \$dcount\");",
                                         "if (\$dcount>0) {\$q_no = goto_qlab(\"LAST\") - 1;}",
                                         "if (\$dcount==0) {&db_conn;&db_set_status(\$survey_id,\$resp{id},\$resp{token},0,0)}",
                                       ],
                        _dataInfo   => [],
                        _label      => "CHECK",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "Check if we have enough data to allow submission of form",
                        _qnum       => 9,
                        _qtype      => 27,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames    => [],
                        _attributes    => [],
                        _dataInfo      => [
                                            {
                                              "pos" => 0,
                                              rkey => "ext_BACK2",
                                              type => "hidden",
                                              var => "BACK2",
                                              var_label => "See external page \"nodata.htm\"",
                                            },
                                          ],
                        _external_info => {
                                            names    => [undef, "BACK2"],
                                            options  => {
                                                          "" => {
                                                                alt => "HOME",
                                                                onclick => "document.location='/cgi-mr/pwikit_login.pl?id=<%id%>&password=<%token%>'",
                                                                tabindex => -1,
                                                                type => "BUTTON",
                                                                value => " HOME ",
                                                              },
                                                          BACK2 => { name => "BACK2", type => "hidden" },
                                                        },
                                            "values" => { "" => [" HOME ", " GO BACK "] },
                                          },
                        _label         => "NODATA",
                        _opt           => { external => "nodata.htm", instr => "", scale => 0 },
                        _prompt        => "See external page \"nodata.htm\"",
                        _qnum          => 10,
                        _qtype         => 7,
                        _scores        => [],
                        _setvalues     => [],
                        _skips         => [],
                        _vars          => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _dataInfo   => [],
                        _label      => "BREAK",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "",
                        _qnum       => 11,
                        _qtype      => 8,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames    => [],
                        _attributes    => [],
                        _dataInfo      => [
                                            {
                                              "pos" => 0,
                                              rkey => "ext_finish",
                                              type => "hidden",
                                              var => "finish",
                                              var_label => "This is implemented as an external",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_q_labs",
                                              var => "q_labs",
                                              var_label => "This is implemented as an external",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_BACK2",
                                              type => "hidden",
                                              var => "BACK2",
                                              var_label => "This is implemented as an external",
                                            },
                                          ],
                        _external_info => {
                                            names    => ["finish", "q_labs", undef, "BACK2"],
                                            options  => {
                                                          "" => {
                                                                onclick => "document.q.finish.value='';",
                                                                type    => "SUBMIT",
                                                                value   => " SUBMIT ",
                                                              },
                                                          BACK2 => { name => "BACK2", type => "hidden" },
                                                          finish => { name => "finish", type => "hidden" },
                                                          q_labs => {},
                                                        },
                                            "values" => { "" => [" SUBMIT ", "NOT YET", " GO BACK "] },
                                          },
                        _label         => "LAST",
                        _opt           => { external => "last.htm", instr => "", scale => 0 },
                        _prompt        => "This is implemented as an external",
                        _qnum          => 12,
                        _qtype         => 7,
                        _scores        => [],
                        _setvalues     => [],
                        _skips         => [],
                        _vars          => [],
                      }, "TPerl::Survey::Question"),
                    ],
}, "TPerl::Survey")