#!/usr/bin/perl
# generated by TPerl::Parser because it does not exist 
# Mon May  7 04:02:14 2007
# config2.pl should be hand edited for future quick hacks and overwrites etc.
@jump_index = (
                'A.A',
                'q1.q1',
                'q2.q2',
                'q3.q3',
                'LAST.LAST',
                );

1;
