do {
  my $a = bless({
    _SID           => "MAP018",
    _TritonRoot    => "/home/vhosts/pwidev/triton",
    _config_subdir => "config",
    _data_subdir   => "web",
    _doc_root      => undef,
    _doc_subdir    => "doc",
    _final_subdir  => "final",
    _html_subdir   => "html",
    _masks         => {},
    _options       => {
                        allow_leading_0  => 1,
                        allow_restart    => 1,
                        block_size       => 5,
                        custom_footer    => "<center><img src=\"/themes/ekit/ekit.daa.png\" alt=\"Discipline, Accountability, Achievement\" ></center>",
                        dive_in          => 1,
                        do_footer        => 0,
                        focus_off        => 1,
                        mailto           => "ctwebb\@mapconsulting.com",
                        no_copy          => 1,
                        no_progress_bar  => 1,
                        no_validation    => 1,
                        one_at_a_time    => 1,
                        optional_written => 0,
                        qbanner          => "<table border=0 cellpadding=0 cellspacing=0 class=\"bannertable\"><tr><TD class=\"bannerlogo\">&nbsp;<TD width=\"50px\" >&nbsp;<tr><TD class=\"bluebar\"> &nbsp;&nbsp; Hotel Reservation<TH class=\"bluebarq\">Q18</table>",
                        qscale           => "<P><%q_label%>",
                        survey_name      => "Hotel Reservation",
                        thankyou_url     => "thanks.htm",
                        theme            => "ekit2",
                        window_title     => "Q18 - Hotel Reservation Form",
                        written_cols     => 80,
                        written_rows     => 10,
                      },
    _questions     => [
                        bless({
                          _a_varnames => [],
                          _attributes => [],
                          _code       => [
                                           "duedate=duedate",
                                           "id=id",
                                           "token=token",
                                           "login_page=login_page",
                                           "warning=warning",
                                           "ws_details=ws_details",
                                           "fullname=fullname",
                                           "firstname=firstname",
                                           "workshopdate=workshopdate",
                                           "location=location",
                                           "locationaddress=locationaddress",
                                           "locationcity=locationcity",
                                           "hotelrate=hotelrate",
                                           "day1=day1",
                                           "maplink=maplink",
                                           "qbanner=qbanner",
                                           "qscale=qscale",
                                         ],
                          _dataInfo   => [],
                          _label      => "AA",
                          _opt        => { instr => "", scale => 0 },
                          _prompt     => "",
                          _qnum       => 1,
                          _qtype      => 20,
                          _scores     => [],
                          _setvalues  => [],
                          _skips      => [],
                          _vars       => [],
                        }, "TPerl::Survey::Question"),
                        bless({
                          _a_varnames => [],
                          _attributes => [],
                          _code       => [
                                           "my \$when = \$resp{startdate};",
                                           "\$resp{vday1} = \"Wednesday\";",
                                           "\$resp{vday2} = \"Thursday\";",
                                           "my \$url = qq{http://www.mapquest.com/maps/map.adp?country=US&searchtype=address&address=\$resp{locationaddress}&city=\$resp{locationcity}&state=\$resp{locationstate}};",
                                           "\$url =~ s/\\s+/\\+/g;",
                                           "\$resp{maplink} = qq{<A HREF=\"\$url\" target=\"_blank\">Here is a map</A>};",
                                         ],
                          _dataInfo   => [],
                          _label      => "AB",
                          _opt        => { instr => "", scale => 0 },
                          _prompt     => "perl code to calculate some things",
                          _qnum       => 2,
                          _qtype      => 27,
                          _scores     => [],
                          _setvalues  => [],
                          _skips      => [],
                          _vars       => [],
                        }, "TPerl::Survey::Question"),
                        bless({
                          _a_varnames    => [],
                          _attributes    => [],
                          _dataInfo      => [
                                              {
                                                "pos" => 0,
                                                rkey => "ext_q_labs",
                                                var => "q_labs",
                                                var_label => "First page is external, so we bring in HTTPS now...",
                                              },
                                            ],
                          _external_info => { names => ["q_labs"], options => { q_labs => {} }, "values" => {} },
                          _label         => "A",
                          _opt           => { external => "intro.htm", instr => "", scale => 0 },
                          _prompt        => "First page is external, so we bring in HTTPS now...",
                          _qnum          => 3,
                          _qtype         => 7,
                          _scores        => [],
                          _setvalues     => [],
                          _skips         => [],
                          _vars          => [],
                        }, "TPerl::Survey::Question"),
                        bless({
                          _a_varnames    => [],
                          _attributes    => [],
                          _dataInfo      => [
                                              {
                                                "pos" => 0,
                                                rkey => "ext_occupancy",
                                                type => "radio",
                                                val_label => {
                                                      "Meals Only"  => "Meals Only",
                                                      "One Person"  => "One Person",
                                                      "Two (1 bed)" => "Two (1 bed)",
                                                      "Two (2 bed)" => "Two (2 bed)",
                                                    },
                                                var => "occupancy",
                                                var_label => "Room occupancy-Reservation form",
                                              },
                                              {
                                                "pos" => 0,
                                                rkey => "ext_early",
                                                type => "radio",
                                                val_label => { No => "No", Yes => "Yes" },
                                                var => "early",
                                                var_label => "Early arrival ?-Reservation form",
                                              },
                                              {
                                                "pos" => 0,
                                                rkey => "ext_arrivaltime",
                                                type => "option",
                                                val_label => {
                                                      "01:00 am" => " 1 am",
                                                      "01:00 pm" => " 1 pm",
                                                      "02:00 am" => " 2 am",
                                                      "02:00 pm" => " 2 pm",
                                                      "03:00 am" => " 3 am",
                                                      "03:00 pm" => " 3 pm",
                                                      "04:00 am" => " 4 am",
                                                      "04:00 pm" => " 4 pm",
                                                      "05:00 am" => " 5 am",
                                                      "05:00 pm" => " 5 pm",
                                                      "06:00 am" => " 6 am",
                                                      "06:00 pm" => " 6 pm",
                                                      "07:00 am" => " 7 am",
                                                      "07:00 pm" => " 7 pm",
                                                      "08:00 am" => " 8 am",
                                                      "08:00 pm" => " 8 pm",
                                                      "09:00 am" => " 9 am",
                                                      "09:00 pm" => " 9 pm",
                                                      "10:00 am" => "10 am",
                                                      "10:00 pm" => "10 pm",
                                                      "11:00 am" => "11 am",
                                                      "11:00 pm" => "11 pm",
                                                      "12:00 am" => "12 am",
                                                      "12:00 pm" => "12 pm",
                                                    },
                                                var => "arrivaltime",
                                                var_label => "Arrival time-Reservation form",
                                              },
                                              {
                                                "pos" => 0,
                                                rkey => "ext_guest",
                                                type => "radio",
                                                val_label => { No => "No", Yes => "Yes" },
                                                var => "guest",
                                                var_label => "Will you bring a guest for dinner?-Reservation form",
                                              },
                                              {
                                                "pos" => 0,
                                                rkey => "ext_day1guest",
                                                type => "radio",
                                                val_label => { No => "No", Yes => "Yes" },
                                                var => "day1guest",
                                                var_label => "<%day1%> dinner guest?-Reservation form",
                                              },
                                              {
                                                "pos" => 0,
                                                rkey => "ext_day2guest",
                                                type => "radio",
                                                val_label => { No => "No", Yes => "Yes" },
                                                var => "day2guest",
                                                var_label => "<%day2%> dinner guest?-Reservation form",
                                              },
                                              {
                                                "pos" => 0,
                                                rkey => "ext_dietnotes",
                                                type => "textarea",
                                                var => "dietnotes",
                                                var_label => "Comments-Reservation form",
                                              },
                                              {
                                                "length" => 30,
                                                "pos" => 0,
                                                rkey => "ext_cardname",
                                                type => "text",
                                                var => "cardname",
                                                var_label => "Name on credit card-Reservation form",
                                              },
                                              {
                                                "pos" => 0,
                                                rkey => "ext_cardtype",
                                                type => "radio",
                                                val_label => {
                                                      Amex => "Amex",
                                                      Diners => "Diners",
                                                      Discover => "Discover",
                                                      Mastercard => "Mastercard",
                                                      Visa => "Visa",
                                                    },
                                                var => "cardtype",
                                                var_label => "Credit Card type-Reservation form",
                                              },
                                              {
                                                "pos" => 0,
                                                rkey => "ext_fax_ccno",
                                                type => "radio",
                                                val_label => { "0" => 0, 1 => 1 },
                                                var => "fax_ccno",
                                                var_label => "Fax credit card no ?-Reservation form",
                                              },
                                              {
                                                "length" => 20,
                                                "pos" => 0,
                                                rkey => "ext_cardno",
                                                type => "text",
                                                var => "cardno",
                                                var_label => "Credit Card number-Reservation form",
                                              },
                                              {
                                                "pos" => 0,
                                                rkey => "ext_cardno_obscure",
                                                var => "cardno_obscure",
                                                var_label => "Reservation form",
                                              },
                                              {
                                                "length" => 10,
                                                "pos" => 0,
                                                rkey => "ext_cardexpiry",
                                                type => "text",
                                                var => "cardexpiry",
                                                var_label => "Credit Card expiry date-Reservation form",
                                              },
                                              {
                                                "length" => 60,
                                                "pos" => 0,
                                                rkey => "ext_revisedfullname",
                                                type => "text",
                                                val_label => {
                                                      "<%salutation%> <%fullname%>, <%title%>" => "<%salutation%> <%fullname%>, <%title%>",
                                                    },
                                                var => "revisedfullname",
                                                var_label => "Reservation form",
                                              },
                                              {
                                                "pos" => 0,
                                                rkey => "ext_q_labs",
                                                var => "q_labs",
                                                var_label => "Reservation form",
                                              },
                                              {
                                                "pos" => 0,
                                                rkey => "ext_session",
                                                type => "hidden",
                                                var => "session",
                                                var_label => "Reservation form",
                                              },
                                            ],
                          _external_info => {
                                              labels   => { arrivaltime => 'fix' },
                                              names    => [
                                                            "occupancy",
                                                            "early",
                                                            "arrivaltime",
                                                            "guest",
                                                            "day1guest",
                                                            "day2guest",
                                                            "dietnotes",
                                                            "cardname",
                                                            "cardtype",
                                                            "fax_ccno",
                                                            "cardno",
                                                            "cardno_obscure",
                                                            "cardexpiry",
                                                            "revisedfullname",
                                                            "q_labs",
                                                            "session",
                                                          ],
                                              options  => {
                                                            arrivaltime     => {
                                                                                 label    => "\n\t\t\t\t",
                                                                                 name     => "arrivaltime",
                                                                                 onchange => "yuk(this)",
                                                                                 title    => "Arrival time",
                                                                                 type     => "option",
                                                                                 value    => "",
                                                                               },
                                                            cardexpiry      => {
                                                                                 name     => "cardexpiry",
                                                                                 onchange => "yuk(this)",
                                                                                 size     => 10,
                                                                                 title    => "Credit Card expiry date",
                                                                                 type     => "text",
                                                                               },
                                                            cardname        => {
                                                                                 name     => "cardname",
                                                                                 onchange => "yuk(this)",
                                                                                 size     => 30,
                                                                                 title    => "Name on credit card",
                                                                                 type     => "text",
                                                                               },
                                                            cardno          => {
                                                                                 name     => "cardno",
                                                                                 onchange => "yuk(this)",
                                                                                 size     => 20,
                                                                                 title    => "Credit Card number",
                                                                                 type     => "text",
                                                                               },
                                                            cardno_obscure  => {},
                                                            cardtype        => {
                                                                                 id       => "cardtype_1",
                                                                                 name     => "cardtype",
                                                                                 onchange => "yuk(this)",
                                                                                 title    => "Credit Card type",
                                                                                 type     => "radio",
                                                                                 value    => "Mastercard",
                                                                               },
                                                            day1guest       => {
                                                                                 id       => "day1guest_1",
                                                                                 name     => "day1guest",
                                                                                 onchange => "yuk(this)",
                                                                                 title    => "<%day1%> dinner guest?",
                                                                                 type     => "radio",
                                                                                 value    => "Yes",
                                                                               },
                                                            day2guest       => {
                                                                                 id       => "day2guest_1",
                                                                                 name     => "day2guest",
                                                                                 onchange => "yuk(this)",
                                                                                 title    => "<%day2%> dinner guest?",
                                                                                 type     => "radio",
                                                                                 value    => "Yes",
                                                                               },
                                                            dietnotes       => {
                                                                                 cols     => 40,
                                                                                 name     => "dietnotes",
                                                                                 onchange => "yuk(this)",
                                                                                 rows     => 5,
                                                                                 title    => "Comments",
                                                                                 type     => "textarea",
                                                                               },
                                                            early           => {
                                                                                 id       => "early_1",
                                                                                 name     => "early",
                                                                                 onchange => "yuk(this)",
                                                                                 title    => "Early arrival ?",
                                                                                 type     => "radio",
                                                                                 value    => "Yes",
                                                                               },
                                                            fax_ccno        => {
                                                                                 id       => "fax_ccno_1",
                                                                                 name     => "fax_ccno",
                                                                                 onchange => "yuk(this)",
                                                                                 title    => "Fax credit card no ?",
                                                                                 type     => "radio",
                                                                                 value    => 1,
                                                                               },
                                                            guest           => {
                                                                                 id       => "guest_1",
                                                                                 name     => "guest",
                                                                                 onchange => "yuk(this)",
                                                                                 title    => "Will you bring a guest for dinner?",
                                                                                 type     => "radio",
                                                                                 value    => "Yes",
                                                                               },
                                                            occupancy       => {
                                                                                 id       => "occupancy_1",
                                                                                 name     => "occupancy",
                                                                                 onchange => "yuk(this)",
                                                                                 title    => "Room occupancy",
                                                                                 type     => "radio",
                                                                                 value    => "One Person",
                                                                               },
                                                            q_labs          => {},
                                                            revisedfullname => {
                                                                                 name     => "revisedfullname",
                                                                                 onchange => "yuk(this)",
                                                                                 size     => 60,
                                                                                 type     => "text",
                                                                                 value    => "<%salutation%> <%fullname%>, <%title%>",
                                                                               },
                                                            session         => { name => "session", type => "hidden", value => "" },
                                                          },
                                              "values" => {
                                                            arrivaltime     => [
                                                                                 "01:00 am",
                                                                                 "02:00 am",
                                                                                 "03:00 am",
                                                                                 "04:00 am",
                                                                                 "05:00 am",
                                                                                 "06:00 am",
                                                                                 "07:00 am",
                                                                                 "08:00 am",
                                                                                 "09:00 am",
                                                                                 "10:00 am",
                                                                                 "11:00 am",
                                                                                 "12:00 am",
                                                                                 "01:00 pm",
                                                                                 "02:00 pm",
                                                                                 "03:00 pm",
                                                                                 "04:00 pm",
                                                                                 "05:00 pm",
                                                                                 "06:00 pm",
                                                                                 "07:00 pm",
                                                                                 "08:00 pm",
                                                                                 "09:00 pm",
                                                                                 "10:00 pm",
                                                                                 "11:00 pm",
                                                                                 "12:00 pm",
                                                                               ],
                                                            cardtype        => ["Mastercard", "Visa", "Amex", "Diners", "Discover"],
                                                            day1guest       => ["Yes", "No"],
                                                            day2guest       => ["Yes", "No"],
                                                            early           => ["Yes", "No"],
                                                            fax_ccno        => [1, 0],
                                                            guest           => ["Yes", "No"],
                                                            occupancy       => ["One Person", "Two (1 bed)", "Two (2 bed)", "Meals Only"],
                                                            revisedfullname => ["<%salutation%> <%fullname%>, <%title%>"],
                                                          },
                                            },
                          _label         => 1,
                          _opt           => { external => "hotel_form.htm", instr => "", required => "all", scale => 0 },
                          _prompt        => "Reservation form",
                          _qnum          => 4,
                          _qtype         => 7,
                          _scores        => [],
                          _setvalues     => [],
                          _skips         => [],
                          _vars          => [],
                        }, "TPerl::Survey::Question"),
                        bless({
                          _a_varnames => [],
                          _attributes => [],
                          _code       => [
                                           "if (\$resp{ext_cardno} ne '')",
                                           "{",
                                           "\$resp{ext_cardno_obscure} = \$resp{ext_cardno};",
                                           "use TPerl::MAP;",
                                           "my \$m = new TPerl::MAP;",
                                           "\$resp{ext_cardno_enc} = \$m->map_enc(\$resp{ext_cardno});",
                                           "\$resp{ext_cardno} = '';\t\t\t# Make sure we DON'T save the credit card number in the normal place !!!",
                                           "\$resp{ext_cardno_obscure} =~ s/\\s+//g;",
                                           "\$resp{ext_cardno_obscure} =~ s/.*(....)\$/XXXX XXXX XXXX \$1/i;\t# Be defensive here in case of dirty data",
                                           "}",
                                           "if (!\$resp{ext_fax_ccno})",
                                           "{",
                                           "\$q_no = &goto_qlab(\"3\") -1;",
                                           "}",
                                         ],
                          _dataInfo   => [],
                          _label      => "1A",
                          _opt        => { instr => "", scale => 0 },
                          _prompt     => "Did they give me data at this point ?",
                          _qnum       => 5,
                          _qtype      => 27,
                          _scores     => [],
                          _setvalues  => [],
                          _skips      => [],
                          _vars       => [],
                        }, "TPerl::Survey::Question"),
                        bless({
                          _a_varnames    => [],
                          _attributes    => [],
                          _dataInfo      => [
                                              {
                                                "pos" => 0,
                                                rkey => "ext_occupancy",
                                                type => "radio",
                                                val_label => {
                                                      "Meals Only"  => "Meals Only",
                                                      "One Person"  => "One Person",
                                                      "Two (1 bed)" => "Two (1 bed)",
                                                      "Two (2 bed)" => "Two (2 bed)",
                                                    },
                                                var => "occupancy",
                                                var_label => "Room occupancy-Printable Reservation form",
                                              },
                                              {
                                                "pos" => 0,
                                                rkey => "ext_early",
                                                type => "radio",
                                                val_label => { No => "No", Yes => "Yes" },
                                                var => "early",
                                                var_label => "Early arrival ?-Printable Reservation form",
                                              },
                                              {
                                                "pos" => 0,
                                                rkey => "ext_arrivaltime",
                                                type => "option",
                                                val_label => {
                                                      "01:00 am" => " 1 am",
                                                      "01:00 pm" => " 1 pm",
                                                      "02:00 am" => " 2 am",
                                                      "02:00 pm" => " 2 pm",
                                                      "03:00 am" => " 3 am",
                                                      "03:00 pm" => " 3 pm",
                                                      "04:00 am" => " 4 am",
                                                      "04:00 pm" => " 4 pm",
                                                      "05:00 am" => " 5 am",
                                                      "05:00 pm" => " 5 pm",
                                                      "06:00 am" => " 6 am",
                                                      "06:00 pm" => " 6 pm",
                                                      "07:00 am" => " 7 am",
                                                      "07:00 pm" => " 7 pm",
                                                      "08:00 am" => " 8 am",
                                                      "08:00 pm" => " 8 pm",
                                                      "09:00 am" => " 9 am",
                                                      "09:00 pm" => " 9 pm",
                                                      "10:00 am" => "10 am",
                                                      "10:00 pm" => "10 pm",
                                                      "11:00 am" => "11 am",
                                                      "11:00 pm" => "11 pm",
                                                      "12:00 am" => "12 am",
                                                      "12:00 pm" => "12 pm",
                                                    },
                                                var => "arrivaltime",
                                                var_label => "Arrival time-Printable Reservation form",
                                              },
                                              {
                                                "pos" => 0,
                                                rkey => "ext_guest",
                                                type => "radio",
                                                val_label => { No => "No", Yes => "Yes" },
                                                var => "guest",
                                                var_label => "Will you bring a guest for dinner?-Printable Reservation form",
                                              },
                                              {
                                                "pos" => 0,
                                                rkey => "ext_day1guest",
                                                type => "radio",
                                                val_label => { No => "No", Yes => "Yes" },
                                                var => "day1guest",
                                                var_label => "<%day1%> dinner guest?-Printable Reservation form",
                                              },
                                              {
                                                "pos" => 0,
                                                rkey => "ext_day2guest",
                                                type => "radio",
                                                val_label => { No => "No", Yes => "Yes" },
                                                var => "day2guest",
                                                var_label => "<%day2%> dinner guest?-Printable Reservation form",
                                              },
                                              {
                                                "pos" => 0,
                                                rkey => "ext_dietnotes",
                                                type => "textarea",
                                                var => "dietnotes",
                                                var_label => "Comments-Printable Reservation form",
                                              },
                                              {
                                                "length" => 30,
                                                "pos" => 0,
                                                rkey => "ext_cardname",
                                                type => "text",
                                                var => "cardname",
                                                var_label => "Name on credit card-Printable Reservation form",
                                              },
                                              {
                                                "pos" => 0,
                                                rkey => "ext_cardtype",
                                                type => "radio",
                                                val_label => {
                                                      Amex => "Amex",
                                                      Diners => "Diners",
                                                      Discover => "Discover",
                                                      Mastercard => "Mastercard",
                                                      Visa => "Visa",
                                                    },
                                                var => "cardtype",
                                                var_label => "Credit Card type-Printable Reservation form",
                                              },
                                              {
                                                "length" => 20,
                                                "pos" => 0,
                                                rkey => "ext_cardno",
                                                type => "text",
                                                var => "cardno",
                                                var_label => "Printable Reservation form",
                                              },
                                              {
                                                "length" => 10,
                                                "pos" => 0,
                                                rkey => "ext_cardexpiry",
                                                type => "text",
                                                var => "cardexpiry",
                                                var_label => "Credit Card expiry date-Printable Reservation form",
                                              },
                                              {
                                                "length" => 60,
                                                "pos" => 0,
                                                rkey => "ext_revisedfullname",
                                                type => "text",
                                                val_label => {
                                                      "<%salutation%> <%fullname%>, <%title%>" => "<%salutation%> <%fullname%>, <%title%>",
                                                    },
                                                var => "revisedfullname",
                                                var_label => "Printable Reservation form",
                                              },
                                              {
                                                "pos" => 0,
                                                rkey => "ext_q_labs",
                                                var => "q_labs",
                                                var_label => "Printable Reservation form",
                                              },
                                              {
                                                "pos" => 0,
                                                rkey => "ext_session",
                                                type => "hidden",
                                                var => "session",
                                                var_label => "Printable Reservation form",
                                              },
                                            ],
                          _external_info => {
                                              labels   => { arrivaltime => 'fix' },
                                              names    => [
                                                            "occupancy",
                                                            "early",
                                                            "arrivaltime",
                                                            "guest",
                                                            "day1guest",
                                                            "day2guest",
                                                            "dietnotes",
                                                            "cardname",
                                                            "cardtype",
                                                            "cardno",
                                                            "cardexpiry",
                                                            "revisedfullname",
                                                            "q_labs",
                                                            "session",
                                                          ],
                                              options  => {
                                                            arrivaltime     => {
                                                                                 label    => "\n\t\t\t\t",
                                                                                 name     => "arrivaltime",
                                                                                 onchange => "yuk(this)",
                                                                                 title    => "Arrival time",
                                                                                 type     => "option",
                                                                                 value    => "",
                                                                               },
                                                            cardexpiry      => {
                                                                                 name     => "cardexpiry",
                                                                                 onchange => "yuk(this)",
                                                                                 size     => 10,
                                                                                 title    => "Credit Card expiry date",
                                                                                 type     => "text",
                                                                               },
                                                            cardname        => {
                                                                                 name     => "cardname",
                                                                                 onchange => "yuk(this)",
                                                                                 size     => 30,
                                                                                 title    => "Name on credit card",
                                                                                 type     => "text",
                                                                               },
                                                            cardno          => {
                                                                                 desc     => "Credit Card number",
                                                                                 name     => "cardno",
                                                                                 onchange => "yuk(this)",
                                                                                 size     => 20,
                                                                                 type     => "text",
                                                                               },
                                                            cardtype        => {
                                                                                 id       => "cardtype_1",
                                                                                 name     => "cardtype",
                                                                                 onchange => "yuk(this)",
                                                                                 title    => "Credit Card type",
                                                                                 type     => "radio",
                                                                                 value    => "Mastercard",
                                                                               },
                                                            day1guest       => {
                                                                                 id       => "day1guest_1",
                                                                                 name     => "day1guest",
                                                                                 onchange => "yuk(this)",
                                                                                 title    => "<%day1%> dinner guest?",
                                                                                 type     => "radio",
                                                                                 value    => "Yes",
                                                                               },
                                                            day2guest       => {
                                                                                 id       => "day2guest_1",
                                                                                 name     => "day2guest",
                                                                                 onchange => "yuk(this)",
                                                                                 title    => "<%day2%> dinner guest?",
                                                                                 type     => "radio",
                                                                                 value    => "Yes",
                                                                               },
                                                            dietnotes       => {
                                                                                 cols     => 40,
                                                                                 name     => "dietnotes",
                                                                                 onchange => "yuk(this)",
                                                                                 rows     => 5,
                                                                                 title    => "Comments",
                                                                                 type     => "textarea",
                                                                               },
                                                            early           => {
                                                                                 id       => "early_1",
                                                                                 name     => "early",
                                                                                 onchange => "yuk(this)",
                                                                                 title    => "Early arrival ?",
                                                                                 type     => "radio",
                                                                                 value    => "Yes",
                                                                               },
                                                            guest           => {
                                                                                 id       => "guest_1",
                                                                                 name     => "guest",
                                                                                 onchange => "yuk(this)",
                                                                                 title    => "Will you bring a guest for dinner?",
                                                                                 type     => "radio",
                                                                                 value    => "Yes",
                                                                               },
                                                            occupancy       => {
                                                                                 id       => "occupancy_1",
                                                                                 name     => "occupancy",
                                                                                 onchange => "yuk(this)",
                                                                                 title    => "Room occupancy",
                                                                                 type     => "radio",
                                                                                 value    => "One Person",
                                                                               },
                                                            q_labs          => {},
                                                            revisedfullname => {
                                                                                 name     => "revisedfullname",
                                                                                 onchange => "yuk(this)",
                                                                                 size     => 60,
                                                                                 type     => "text",
                                                                                 value    => "<%salutation%> <%fullname%>, <%title%>",
                                                                               },
                                                            session         => { name => "session", type => "hidden", value => "" },
                                                          },
                                              "values" => {
                                                            arrivaltime     => [
                                                                                 "01:00 am",
                                                                                 "02:00 am",
                                                                                 "03:00 am",
                                                                                 "04:00 am",
                                                                                 "05:00 am",
                                                                                 "06:00 am",
                                                                                 "07:00 am",
                                                                                 "08:00 am",
                                                                                 "09:00 am",
                                                                                 "10:00 am",
                                                                                 "11:00 am",
                                                                                 "12:00 am",
                                                                                 "01:00 pm",
                                                                                 "02:00 pm",
                                                                                 "03:00 pm",
                                                                                 "04:00 pm",
                                                                                 "05:00 pm",
                                                                                 "06:00 pm",
                                                                                 "07:00 pm",
                                                                                 "08:00 pm",
                                                                                 "09:00 pm",
                                                                                 "10:00 pm",
                                                                                 "11:00 pm",
                                                                                 "12:00 pm",
                                                                               ],
                                                            cardtype        => ["Mastercard", "Visa", "Amex", "Diners", "Discover"],
                                                            day1guest       => ["Yes", "No"],
                                                            day2guest       => ["Yes", "No"],
                                                            early           => ["Yes", "No"],
                                                            guest           => ["Yes", "No"],
                                                            occupancy       => ["One Person", "Two (1 bed)", "Two (2 bed)", "Meals Only"],
                                                            revisedfullname => ["<%salutation%> <%fullname%>, <%title%>"],
                                                          },
                                            },
                          _label         => 2,
                          _opt           => { external => "hotel_printable.htm", instr => "", scale => 0 },
                          _prompt        => "Printable Reservation form",
                          _qnum          => 6,
                          _qtype         => 7,
                          _scores        => [],
                          _setvalues     => [],
                          _skips         => [],
                          _vars          => [],
                        }, "TPerl::Survey::Question"),
                        bless({
                          _a_varnames    => [],
                          _attributes    => [],
                          _dataInfo      => [
                                              {
                                                "pos" => 0,
                                                rkey => "ext_q_labs",
                                                var => "q_labs",
                                                var_label => "Last page is external, so we turn off HTTPS now...",
                                              },
                                            ],
                          _external_info => { names => ["q_labs"], options => { q_labs => {} }, "values" => {} },
                          _label         => 3,
                          _opt           => { external => "schedule.htm", instr => "", scale => 0 },
                          _prompt        => "Last page is external, so we turn off HTTPS now...",
                          _qnum          => 7,
                          _qtype         => 7,
                          _scores        => [],
                          _setvalues     => [],
                          _skips         => [],
                          _vars          => [],
                        }, "TPerl::Survey::Question"),
                        bless({
                          _a_varnames => [],
                          _attributes => [],
                          _code       => [
                                           "my \$dcount = &count_data;",
                                           "&debug(\"Datacount = \$dcount\");",
                                           "if (\$dcount>0) {\$q_no = goto_qlab(\"LAST\") - 1;}",
                                           "if (\$dcount==0) {&db_conn;&db_set_status(\$survey_id,\$resp{id},\$resp{token},0,0)};",
                                         ],
                          _dataInfo   => [],
                          _label      => "CHECK",
                          _opt        => { instr => "", scale => 0 },
                          _prompt     => "Check if we have enough data to allow submission of form",
                          _qnum       => 8,
                          _qtype      => 27,
                          _scores     => [],
                          _setvalues  => [],
                          _skips      => [],
                          _vars       => [],
                        }, "TPerl::Survey::Question"),
                        bless({
                          _a_varnames    => [],
                          _attributes    => [],
                          _dataInfo      => [
                                              {
                                                "pos" => 0,
                                                rkey => "ext_BACK2",
                                                type => "hidden",
                                                var => "BACK2",
                                                var_label => "See external page \"nodata.htm\"",
                                              },
                                            ],
                          _external_info => {
                                              names    => [undef, "BACK2"],
                                              options  => {
                                                            "" => {
                                                                  alt => "HOME",
                                                                  onclick => "document.location='/cgi-mr/pwikit_login.pl?id=<%id%>&password=<%token%>'",
                                                                  tabindex => -1,
                                                                  type => "BUTTON",
                                                                  value => " HOME ",
                                                                },
                                                            BACK2 => { name => "BACK2", type => "hidden" },
                                                          },
                                              "values" => { "" => [" HOME ", " GO BACK "] },
                                            },
                          _label         => "NODATA",
                          _opt           => { external => "nodata.htm", instr => "", scale => 0 },
                          _prompt        => "See external page \"nodata.htm\"",
                          _qnum          => 9,
                          _qtype         => 7,
                          _scores        => [],
                          _setvalues     => [],
                          _skips         => [],
                          _vars          => [],
                        }, "TPerl::Survey::Question"),
                        bless({
                          _a_varnames    => [],
                          _attributes    => [],
                          _dataInfo      => [
                                              {
                                                "pos" => 0,
                                                rkey => "ext_finish",
                                                type => "hidden",
                                                var => "finish",
                                                var_label => "This is implemented as an external",
                                              },
                                              {
                                                "pos" => 0,
                                                rkey => "ext_q_labs",
                                                var => "q_labs",
                                                var_label => "This is implemented as an external",
                                              },
                                              {
                                                "pos" => 0,
                                                rkey => "ext_BACK2",
                                                type => "hidden",
                                                var => "BACK2",
                                                var_label => "This is implemented as an external",
                                              },
                                            ],
                          _external_info => {
                                              names    => ["finish", "q_labs", undef, "BACK2"],
                                              options  => {
                                                            "" => {
                                                                  onclick => "document.q.finish.value='';",
                                                                  type    => "SUBMIT",
                                                                  value   => " SUBMIT ",
                                                                },
                                                            BACK2 => { name => "BACK2", type => "hidden" },
                                                            finish => { name => "finish", type => "hidden" },
                                                            q_labs => {},
                                                          },
                                              "values" => { "" => [" SUBMIT ", "NOT YET", " GO BACK "] },
                                            },
                          _label         => "LAST",
                          _opt           => { external => "last.htm", instr => "", scale => 0 },
                          _prompt        => "This is implemented as an external",
                          _qnum          => 10,
                          _qtype         => 7,
                          _scores        => [],
                          _setvalues     => [],
                          _skips         => [],
                          _vars          => [],
                        }, "TPerl::Survey::Question"),
                      ],
  }, "TPerl::Survey");
  $a->{_questions}[3]{_external_info}{labels}{arrivaltime} = $a->{_questions}[3]{_dataInfo}[2]{val_label};
  $a->{_questions}[5]{_external_info}{labels}{arrivaltime} = $a->{_questions}[5]{_dataInfo}[2]{val_label};
  $a;
}