#!/usr/bin/perl
# generated by TPerl::Parser::_config_file 
# Sat Dec 29 11:02:56 2012
$numq = 14;
$do_footer = '0';
$survey_name = 'Professional Career Summary';
$one_at_a_time = '0';
$qscale = '';
$block_size = '3';
$custom_footer = '<center><img src="/themes/ekit/ekit.daa.png" alt="Discipline, Accountability, Achievement" ></center>';
$focus_off = '1';
$no_copy = '1';
$plain = '1';
$mike = '1';
$no_progress_bar = '1';
$qbanner = '<table border=0 cellpadding=0 cellspacing=0 class="bannertable"><tr><TD class="bannerlogo">&nbsp;<TD width="50px" >&nbsp;<tr><TD class="bluebar"> &nbsp;&nbsp; Professional Career Summary<TH class="bluebarq">Q4</table>';
$textcolor = '#000000';
$theme = 'ekit';
$no_methods = '1';
$mailto = 'ctwebb@mapconsulting.com';
$style = 'plain';
$background = '';
$window_title = 'Q4 - Professional Career Summary';
$do_body = '1';
$optional_written = '0';
$thankyou_url = 'thanks.htm';
$bg_color = '#FFFFFF';
$banner_top = '0';
1;
