bless({
  _SID           => "MAP004",
  _TritonRoot    => "/home/vhosts/pwidev/triton",
  _config_subdir => "config",
  _data_subdir   => "web",
  _doc_root      => undef,
  _doc_subdir    => "doc",
  _final_subdir  => "final",
  _html_subdir   => "html",
  _masks         => {},
  _options       => {
                      block_size       => 3,
                      custom_footer    => "<center><img src=\"/themes/ekit/ekit.daa.png\" alt=\"Discipline, Accountability, Achievement\" ></center>",
                      focus_off        => 1,
                      mailto           => "ctwebb\@mapconsulting.com",
                      mike             => 1,
                      no_copy          => 1,
                      no_progress_bar  => 1,
                      one_at_a_time    => 0,
                      optional_written => 0,
                      qbanner          => "<table border=0 cellpadding=0 cellspacing=0 class=\"bannertable\"><tr><TD class=\"bannerlogo\">&nbsp;<TD width=\"50px\" >&nbsp;<tr><TD class=\"bluebar\"> &nbsp;&nbsp; Professional Career Summary<TH class=\"bluebarq\">Q4</table>",
                      qscale           => "",
                      survey_name      => "Professional Career Summary",
                      thankyou_url     => "thanks.htm",
                      theme            => "ekit",
                      window_title     => "Q4 - Professional Career Summary",
                    },
  _questions     => [
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _code       => [
                                         "duedate=duedate",
                                         "id=id",
                                         "token=token",
                                         "login_page=login_page",
                                         "warning=warning",
                                         "ws_details=ws_details",
                                         "qbanner=qbanner",
                                         "qscale=qscale",
                                       ],
                        _dataInfo   => [],
                        _label      => "AA",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "",
                        _qnum       => 1,
                        _qtype      => 20,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames    => [],
                        _attributes    => [],
                        _dataInfo      => [
                                            {
                                              "pos" => 0,
                                              rkey => "ext_q_labs",
                                              var => "q_labs",
                                              var_label => "Personal Details:",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_session",
                                              type => "hidden",
                                              var => "session",
                                              var_label => "Personal Details:",
                                            },
                                            {
                                              "length" => 100,
                                              "pos" => 0,
                                              rkey => "ext_address",
                                              type => "text",
                                              var => "address",
                                              var_label => "Personal Details:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_dob",
                                              type => "text",
                                              var => "dob",
                                              var_label => "Personal Details:",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_phone",
                                              type => "text",
                                              var => "phone",
                                              var_label => "Personal Details:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_city",
                                              type => "text",
                                              var => "city",
                                              var_label => "Personal Details:",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_married",
                                              type => "radio",
                                              val_label => { "0" => 0, 1 => 1 },
                                              var => "married",
                                              var_label => "Personal Details:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_state",
                                              type => "text",
                                              var => "state",
                                              var_label => "Personal Details:",
                                            },
                                            {
                                              "length" => 10,
                                              "pos" => 0,
                                              rkey => "ext_children",
                                              type => "text",
                                              var => "children",
                                              var_label => "Personal Details:",
                                            },
                                            {
                                              "length" => 10,
                                              "pos" => 0,
                                              rkey => "ext_zip",
                                              type => "text",
                                              var => "zip",
                                              var_label => "Personal Details:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_age",
                                              type => "text",
                                              var => "age",
                                              var_label => "Personal Details:",
                                            },
                                            {
                                              "length" => 60,
                                              "pos" => 0,
                                              rkey => "ext_personalemail",
                                              type => "text",
                                              var => "personalemail",
                                              var_label => "Personal Details:",
                                            },
                                            {
                                              "length" => 60,
                                              "pos" => 0,
                                              rkey => "ext_linkedin",
                                              type => "text",
                                              var => "linkedin",
                                              var_label => "Personal Details:",
                                            },
                                            {
                                              "length" => 60,
                                              "pos" => 0,
                                              rkey => "ext_facebook",
                                              type => "text",
                                              var => "facebook",
                                              var_label => "Personal Details:",
                                            },
                                          ],
                        _external_info => {
                                            names    => [
                                                          "q_labs",
                                                          "session",
                                                          "address",
                                                          "dob",
                                                          "phone",
                                                          "city",
                                                          "married",
                                                          "state",
                                                          "children",
                                                          "zip",
                                                          "age",
                                                          "personalemail",
                                                          "linkedin",
                                                          "facebook",
                                                        ],
                                            options  => {
                                                          address       => {
                                                                             class => "input",
                                                                             maxlength => 100,
                                                                             name => "address",
                                                                             onchange => "yuk(this)",
                                                                             size => 30,
                                                                             type => "text",
                                                                           },
                                                          age           => {
                                                                             class    => "input",
                                                                             name     => "age",
                                                                             onchange => "yuk(this)",
                                                                             size     => 20,
                                                                             type     => "text",
                                                                           },
                                                          children      => {
                                                                             class    => "input",
                                                                             name     => "children",
                                                                             onchange => "yuk(this)",
                                                                             size     => 10,
                                                                             type     => "text",
                                                                           },
                                                          city          => {
                                                                             class => "input",
                                                                             maxlength => 20,
                                                                             name => "city",
                                                                             onchange => "yuk(this)",
                                                                             size => 20,
                                                                             type => "text",
                                                                           },
                                                          dob           => {
                                                                             class    => "input",
                                                                             name     => "dob",
                                                                             onchange => "yuk(this)",
                                                                             size     => 20,
                                                                             type     => "text",
                                                                           },
                                                          facebook      => {
                                                                             class    => "input",
                                                                             name     => "facebook",
                                                                             onchange => "yuk(this)",
                                                                             size     => 60,
                                                                             type     => "text",
                                                                           },
                                                          linkedin      => {
                                                                             class    => "input",
                                                                             name     => "linkedin",
                                                                             onchange => "yuk(this)",
                                                                             size     => 60,
                                                                             type     => "text",
                                                                           },
                                                          married       => { name => "married", onchange => "yuk(this)", type => "radio", value => 0 },
                                                          personalemail => {
                                                                             class    => "input",
                                                                             name     => "personalemail",
                                                                             onchange => "yuk(this)",
                                                                             size     => 60,
                                                                             type     => "text",
                                                                           },
                                                          phone         => {
                                                                             class    => "input",
                                                                             name     => "phone",
                                                                             onchange => "yuk(this)",
                                                                             size     => 15,
                                                                             type     => "text",
                                                                           },
                                                          q_labs        => {},
                                                          session       => { name => "session", type => "hidden", value => "" },
                                                          state         => {
                                                                             class    => "input",
                                                                             name     => "state",
                                                                             onchange => "yuk(this)",
                                                                             size     => 20,
                                                                             type     => "text",
                                                                           },
                                                          zip           => {
                                                                             class    => "input",
                                                                             name     => "zip",
                                                                             onchange => "yuk(this)",
                                                                             size     => 10,
                                                                             type     => "text",
                                                                           },
                                                        },
                                            "values" => { married => [0, 1] },
                                          },
                        _label         => 1,
                        _opt           => { external => "address.htm", instr => "", required => "all", scale => 0 },
                        _prompt        => "Personal Details:",
                        _qnum          => 2,
                        _qtype         => 7,
                        _scores        => [],
                        _setvalues     => [],
                        _skips         => [],
                        _vars          => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q2",
                                           var => "Q2",
                                           var_label => "-<%qbanner%> <P><%q_label%> Avocational interests and hobbies:",
                                         },
                                       ],
                        _label      => 2,
                        _opt        => { dk => undef, instr => "", required => "all", scale => 0 },
                        _prompt     => "<%qbanner%> <P><%q_label%> Avocational interests and hobbies:",
                        _qnum       => 3,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q3",
                                           var => "Q3",
                                           var_label => "-Organizations (social, service, business, or professional) to which you belong:",
                                         },
                                       ],
                        _label      => 3,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "Organizations (social, service, business, or professional) to which you belong:",
                        _qnum       => 4,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q4",
                                           var => "Q4",
                                           var_label => "-Periodicals you read:",
                                         },
                                       ],
                        _label      => 4,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "Periodicals you read:",
                        _qnum       => 5,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q5",
                                           var => "Q5",
                                           var_label => "-<%qbanner%> <P><%q_label%> Educational background:",
                                         },
                                       ],
                        _label      => 5,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "<%qbanner%> <P><%q_label%> Educational background:",
                        _qnum       => 6,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q6",
                                           var => "Q6",
                                           var_label => "-Business or professional seminars taken:",
                                         },
                                       ],
                        _label      => 6,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "Business or professional seminars taken:",
                        _qnum       => 7,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => ["x"],
                        _dataInfo   => [
                                         { "pos" => 0, rkey => "_Q7", var => "Q7", var_label => "x-Key advisors:" },
                                       ],
                        _label      => 7,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "Key advisors:",
                        _qnum       => 8,
                        _qtype      => 5,
                        _scores     => [0],
                        _setvalues  => [undef],
                        _skips      => [undef],
                        _vars       => [undef],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _dataInfo   => [],
                        _label      => "7A",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "BREAK1",
                        _qnum       => 9,
                        _qtype      => 8,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames    => [],
                        _attributes    => [],
                        _dataInfo      => [
                                            {
                                              "pos" => 0,
                                              rkey => "ext_q_labs",
                                              var => "q_labs",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_session",
                                              type => "hidden",
                                              var => "session",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_employer1",
                                              type => "text",
                                              var => "employer1",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_from1",
                                              type => "text",
                                              var => "from1",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_to1",
                                              type => "text",
                                              var => "to1",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_title1",
                                              type => "text",
                                              var => "title1",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_begsalary1",
                                              type => "text",
                                              var => "begsalary1",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_endsalary1",
                                              type => "text",
                                              var => "endsalary1",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_employer2",
                                              type => "text",
                                              var => "employer2",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_from2",
                                              type => "text",
                                              var => "from2",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_to2",
                                              type => "text",
                                              var => "to2",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_title2",
                                              type => "text",
                                              var => "title2",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_begsalary2",
                                              type => "text",
                                              var => "begsalary2",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_endsalary2",
                                              type => "text",
                                              var => "endsalary2",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_employer3",
                                              type => "text",
                                              var => "employer3",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_from3",
                                              type => "text",
                                              var => "from3",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_to3",
                                              type => "text",
                                              var => "to3",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_title3",
                                              type => "text",
                                              var => "title3",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_begsalary3",
                                              type => "text",
                                              var => "begsalary3",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_endsalary3",
                                              type => "text",
                                              var => "endsalary3",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_employer4",
                                              type => "text",
                                              var => "employer4",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_from4",
                                              type => "text",
                                              var => "from4",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_to4",
                                              type => "text",
                                              var => "to4",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_title4",
                                              type => "text",
                                              var => "title4",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_begsalary4",
                                              type => "text",
                                              var => "begsalary4",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_endsalary4",
                                              type => "text",
                                              var => "endsalary4",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_employer5",
                                              type => "text",
                                              var => "employer5",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_from5",
                                              type => "text",
                                              var => "from5",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_to5",
                                              type => "text",
                                              var => "to5",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 20,
                                              "pos" => 0,
                                              rkey => "ext_title5",
                                              type => "text",
                                              var => "title5",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_begsalary5",
                                              type => "text",
                                              var => "begsalary5",
                                              var_label => "Employment:",
                                            },
                                            {
                                              "length" => 15,
                                              "pos" => 0,
                                              rkey => "ext_endsalary5",
                                              type => "text",
                                              var => "endsalary5",
                                              var_label => "Employment:",
                                            },
                                          ],
                        _external_info => {
                                            names    => [
                                                          "q_labs",
                                                          "session",
                                                          "employer1",
                                                          "from1",
                                                          "to1",
                                                          "title1",
                                                          "begsalary1",
                                                          "endsalary1",
                                                          "employer2",
                                                          "from2",
                                                          "to2",
                                                          "title2",
                                                          "begsalary2",
                                                          "endsalary2",
                                                          "employer3",
                                                          "from3",
                                                          "to3",
                                                          "title3",
                                                          "begsalary3",
                                                          "endsalary3",
                                                          "employer4",
                                                          "from4",
                                                          "to4",
                                                          "title4",
                                                          "begsalary4",
                                                          "endsalary4",
                                                          "employer5",
                                                          "from5",
                                                          "to5",
                                                          "title5",
                                                          "begsalary5",
                                                          "endsalary5",
                                                        ],
                                            options  => {
                                                          begsalary1 => {
                                                                class    => "input",
                                                                name     => "begsalary1",
                                                                onchange => "yuk()",
                                                                size     => 15,
                                                                type     => "text",
                                                              },
                                                          begsalary2 => {
                                                                class    => "input",
                                                                name     => "begsalary2",
                                                                onchange => "yuk()",
                                                                size     => 15,
                                                                type     => "text",
                                                              },
                                                          begsalary3 => {
                                                                class    => "input",
                                                                name     => "begsalary3",
                                                                onchange => "yuk()",
                                                                size     => 15,
                                                                type     => "text",
                                                              },
                                                          begsalary4 => {
                                                                class    => "input",
                                                                name     => "begsalary4",
                                                                onchange => "yuk()",
                                                                size     => 15,
                                                                type     => "text",
                                                              },
                                                          begsalary5 => {
                                                                class    => "input",
                                                                name     => "begsalary5",
                                                                onchange => "yuk()",
                                                                size     => 15,
                                                                type     => "text",
                                                              },
                                                          employer1 => {
                                                                class    => "input",
                                                                name     => "employer1",
                                                                onchange => "yuk()",
                                                                size     => 20,
                                                                type     => "text",
                                                              },
                                                          employer2 => {
                                                                class    => "input",
                                                                name     => "employer2",
                                                                onchange => "yuk()",
                                                                size     => 20,
                                                                type     => "text",
                                                              },
                                                          employer3 => {
                                                                class    => "input",
                                                                name     => "employer3",
                                                                onchange => "yuk()",
                                                                size     => 20,
                                                                type     => "text",
                                                              },
                                                          employer4 => {
                                                                class    => "input",
                                                                name     => "employer4",
                                                                onchange => "yuk()",
                                                                size     => 20,
                                                                type     => "text",
                                                              },
                                                          employer5 => {
                                                                class    => "input",
                                                                name     => "employer5",
                                                                onchange => "yuk()",
                                                                size     => 20,
                                                                type     => "text",
                                                              },
                                                          endsalary1 => {
                                                                class    => "input",
                                                                name     => "endsalary1",
                                                                onchange => "yuk()",
                                                                size     => 15,
                                                                type     => "text",
                                                              },
                                                          endsalary2 => {
                                                                class    => "input",
                                                                name     => "endsalary2",
                                                                onchange => "yuk()",
                                                                size     => 15,
                                                                type     => "text",
                                                              },
                                                          endsalary3 => {
                                                                class    => "input",
                                                                name     => "endsalary3",
                                                                onchange => "yuk()",
                                                                size     => 15,
                                                                type     => "text",
                                                              },
                                                          endsalary4 => {
                                                                class    => "input",
                                                                name     => "endsalary4",
                                                                onchange => "yuk()",
                                                                size     => 15,
                                                                type     => "text",
                                                              },
                                                          endsalary5 => {
                                                                class    => "input",
                                                                name     => "endsalary5",
                                                                onchange => "yuk()",
                                                                size     => 15,
                                                                type     => "text",
                                                              },
                                                          from1 => {
                                                                class    => "input",
                                                                name     => "from1",
                                                                onchange => "yuk()",
                                                                size     => 15,
                                                                type     => "text",
                                                              },
                                                          from2 => {
                                                                class    => "input",
                                                                name     => "from2",
                                                                onchange => "yuk()",
                                                                size     => 15,
                                                                type     => "text",
                                                              },
                                                          from3 => {
                                                                class    => "input",
                                                                name     => "from3",
                                                                onchange => "yuk()",
                                                                size     => 15,
                                                                type     => "text",
                                                              },
                                                          from4 => {
                                                                class    => "input",
                                                                name     => "from4",
                                                                onchange => "yuk()",
                                                                size     => 15,
                                                                type     => "text",
                                                              },
                                                          from5 => {
                                                                class    => "input",
                                                                name     => "from5",
                                                                onchange => "yuk()",
                                                                size     => 15,
                                                                type     => "text",
                                                              },
                                                          q_labs => {},
                                                          session => { name => "session", type => "hidden", value => "" },
                                                          title1 => {
                                                                class    => "input",
                                                                name     => "title1",
                                                                onchange => "yuk()",
                                                                size     => 20,
                                                                type     => "text",
                                                              },
                                                          title2 => {
                                                                class    => "input",
                                                                name     => "title2",
                                                                onchange => "yuk()",
                                                                size     => 20,
                                                                type     => "text",
                                                              },
                                                          title3 => {
                                                                class    => "input",
                                                                name     => "title3",
                                                                onchange => "yuk()",
                                                                size     => 20,
                                                                type     => "text",
                                                              },
                                                          title4 => {
                                                                class    => "input",
                                                                name     => "title4",
                                                                onchange => "yuk()",
                                                                size     => 20,
                                                                type     => "text",
                                                              },
                                                          title5 => {
                                                                class    => "input",
                                                                name     => "title5",
                                                                onchange => "yuk()",
                                                                size     => 20,
                                                                type     => "text",
                                                              },
                                                          to1 => {
                                                                class    => "input",
                                                                name     => "to1",
                                                                onchange => "yuk()",
                                                                size     => 15,
                                                                type     => "text",
                                                              },
                                                          to2 => {
                                                                class    => "input",
                                                                name     => "to2",
                                                                onchange => "yuk()",
                                                                size     => 15,
                                                                type     => "text",
                                                              },
                                                          to3 => {
                                                                class    => "input",
                                                                name     => "to3",
                                                                onchange => "yuk()",
                                                                size     => 15,
                                                                type     => "text",
                                                              },
                                                          to4 => {
                                                                class    => "input",
                                                                name     => "to4",
                                                                onchange => "yuk()",
                                                                size     => 15,
                                                                type     => "text",
                                                              },
                                                          to5 => {
                                                                class    => "input",
                                                                name     => "to5",
                                                                onchange => "yuk()",
                                                                size     => 15,
                                                                type     => "text",
                                                              },
                                                        },
                                            "values" => {},
                                          },
                        _label         => 8,
                        _opt           => { external => "employ.htm", instr => "", required => "all", scale => 0 },
                        _prompt        => "Employment:",
                        _qnum          => 10,
                        _qtype         => 7,
                        _scores        => [],
                        _setvalues     => [],
                        _skips         => [],
                        _vars          => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _code       => [
                                         "my \$dcount = &count_data;",
                                         "&debug(\"Datacount = \$dcount\");",
                                         "if (\$dcount>0) {\$q_no = goto_qlab(\"LAST\") - 1;}",
                                         "if (\$dcount==0) {&db_conn;&db_set_status(\$survey_id,\$resp{id},\$resp{token},0,0)}",
                                       ],
                        _dataInfo   => [],
                        _label      => "CHECK",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "Check if we have enough data to allow submission of form",
                        _qnum       => 11,
                        _qtype      => 27,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames    => [],
                        _attributes    => [],
                        _dataInfo      => [
                                            {
                                              "pos" => 0,
                                              rkey => "ext_BACK2",
                                              type => "hidden",
                                              var => "BACK2",
                                              var_label => "See external page \"nodata.htm\"",
                                            },
                                          ],
                        _external_info => {
                                            names    => [undef, "BACK2"],
                                            options  => {
                                                          "" => {
                                                                alt => "HOME",
                                                                onclick => "document.location='/cgi-mr/pwikit_login.pl?id=<%id%>&password=<%token%>'",
                                                                tabindex => -1,
                                                                type => "BUTTON",
                                                                value => " HOME ",
                                                              },
                                                          BACK2 => { name => "BACK2", type => "hidden" },
                                                        },
                                            "values" => { "" => [" HOME ", " GO BACK "] },
                                          },
                        _label         => "NODATA",
                        _opt           => { external => "nodata.htm", instr => "", scale => 0 },
                        _prompt        => "See external page \"nodata.htm\"",
                        _qnum          => 12,
                        _qtype         => 7,
                        _scores        => [],
                        _setvalues     => [],
                        _skips         => [],
                        _vars          => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _code       => ["duedate=duedate", "id=id", "token=token"],
                        _dataInfo   => [],
                        _label      => "BREAK",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "",
                        _qnum       => 13,
                        _qtype      => 20,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames    => [],
                        _attributes    => [],
                        _dataInfo      => [
                                            {
                                              "pos" => 0,
                                              rkey => "ext_finish",
                                              type => "hidden",
                                              var => "finish",
                                              var_label => "This is implemented as an external",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_q_labs",
                                              var => "q_labs",
                                              var_label => "This is implemented as an external",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_BACK2",
                                              type => "hidden",
                                              var => "BACK2",
                                              var_label => "This is implemented as an external",
                                            },
                                          ],
                        _external_info => {
                                            names    => ["finish", "q_labs", undef, "BACK2"],
                                            options  => {
                                                          "" => {
                                                                onclick => "document.q.finish.value='';",
                                                                type    => "SUBMIT",
                                                                value   => " SUBMIT ",
                                                              },
                                                          BACK2 => { name => "BACK2", type => "hidden" },
                                                          finish => { name => "finish", type => "hidden" },
                                                          q_labs => {},
                                                        },
                                            "values" => { "" => [" SUBMIT ", "NOT YET", " GO BACK "] },
                                          },
                        _label         => "LAST",
                        _opt           => { external => "last.htm", instr => "", scale => 0 },
                        _prompt        => "This is implemented as an external",
                        _qnum          => 14,
                        _qtype         => 7,
                        _scores        => [],
                        _setvalues     => [],
                        _skips         => [],
                        _vars          => [],
                      }, "TPerl::Survey::Question"),
                    ],
}, "TPerl::Survey")