#!/usr/bin/perl
# generated by TPerl::Parser::_config_file 
# Sat Dec 29 11:02:57 2012
$numq = 17;
$do_footer = '0';
$survey_name = 'Key Personnel Questionnaire';
$one_at_a_time = '0';
$qscale = '<P><%q_label%>';
$block_size = '5';
$custom_footer = '<center><img src="/themes/ekit/ekit.daa.png" alt="Discipline, Accountability, Achievement" ></center>';
$focus_off = '1';
$no_copy = '1';
$plain = '1';
$no_progress_bar = '1';
$qbanner = '<table border=0 cellpadding=0 cellspacing=0 class="bannertable"><tr><TD class="bannerlogo">&nbsp;<TD width="50px" >&nbsp;<tr><TD class="bluebar"> &nbsp;&nbsp; Key Personnel Questionnaire<TH class="bluebarq">Q10</table>';
$textcolor = '#000000';
$theme = 'ekit';
$no_methods = '1';
$mailto = 'ctwebb@mapconsulting.com';
$style = 'plain';
$background = '';
$window_title = 'Q10 - Key Personnel Questionnaire';
$do_body = '1';
$no_validation = '1';
$written_rows = '10';
$optional_written = '0';
$dive_in = '1';
$thankyou_url = 'thanks.htm';
$bg_color = '#FFFFFF';
$written_cols = '80';
$banner_top = '0';
1;
