bless({
  _SID           => "MAP010",
  _TritonRoot    => "/home/vhosts/pwidev/triton",
  _config_subdir => "config",
  _data_subdir   => "web",
  _doc_root      => undef,
  _doc_subdir    => "doc",
  _final_subdir  => "final",
  _html_subdir   => "html",
  _masks         => {},
  _options       => {
                      block_size       => 5,
                      custom_footer    => "<center><img src=\"/themes/ekit/ekit.daa.png\" alt=\"Discipline, Accountability, Achievement\" ></center>",
                      dive_in          => 1,
                      focus_off        => 1,
                      mailto           => "ctwebb\@mapconsulting.com",
                      no_copy          => 1,
                      no_progress_bar  => 1,
                      no_validation    => 1,
                      one_at_a_time    => 0,
                      optional_written => 0,
                      qbanner          => "<table border=0 cellpadding=0 cellspacing=0 class=\"bannertable\"><tr><TD class=\"bannerlogo\">&nbsp;<TD width=\"50px\" >&nbsp;<tr><TD class=\"bluebar\"> &nbsp;&nbsp; Key Personnel Questionnaire<TH class=\"bluebarq\">Q10</table>",
                      qscale           => "<P><%q_label%>",
                      survey_name      => "Key Personnel Questionnaire",
                      thankyou_url     => "thanks.htm",
                      theme            => "ekit",
                      window_title     => "Q10 - Key Personnel Questionnaire",
                      written_cols     => 80,
                      written_rows     => 10,
                    },
  _questions     => [
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _code       => [
                                         "abouthimher=abouthimher",
                                         "hisher=hisher",
                                         "fullname=fullname",
                                         "firstname=firstname",
                                         "duedate=duedate",
                                         "id=id",
                                         "token=token",
                                         "ws_details=ws_details",
                                         "warning=warning",
                                         "q_label=q_label",
                                         "login_page=login_page",
                                         "qbanner=qbanner",
                                         "qscale=qscale",
                                       ],
                        _dataInfo   => [],
                        _label      => "AA",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "",
                        _qnum       => 1,
                        _qtype      => 20,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _dataInfo   => [],
                        _label      => "A",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "<%qbanner%><TABLE width=\"600\"><TR><TD class=\"prompt\">As a key person in this organization, your candid and thoughtful answers to the following questions about <%fullname%> will be helpful in guiding us to help <%abouthimher%> achieve the goals of this management program: increased productivity and overall management effectiveness.<BR><BR>Please be candid.  You need not identify yourself.  Your answers will be summarized along with the replies of other anonymous respondents.</TD></TR></TABLE>",
                        _qnum       => 2,
                        _qtype      => 7,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q1",
                                           var => "Q1",
                                           var_label => "-Please describe the leadership/management strengths of <%fullname%>.",
                                         },
                                       ],
                        _label      => 1,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "Please describe the leadership/management strengths of <%fullname%>.",
                        _qnum       => 3,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q2",
                                           var => "Q2",
                                           var_label => "-Every leader/manager has opportunities for growth and improvement. What are the management <BR>and/or leadership skills in which <%fullname%> could improve?",
                                         },
                                       ],
                        _label      => 2,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "Every leader/manager has opportunities for growth and improvement. What are the management <BR>and/or leadership skills in which <%fullname%> could improve?",
                        _qnum       => 4,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q3",
                                           var => "Q3",
                                           var_label => "-What are the main COMMUNICATING challenges that <%fullname%> faces (e.g., style, effectiveness, <br>frequency, internal, external, etc.)?   Please make specific comments.",
                                         },
                                       ],
                        _label      => 3,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "What are the main COMMUNICATING challenges that <%fullname%> faces (e.g., style, effectiveness, <br>frequency, internal, external, etc.)?   Please make specific comments.",
                        _qnum       => 5,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q4",
                                           var => "Q4",
                                           var_label => "-What are the main PLANNING challenges that <%fullname%> faces (e.g., no formal planning, unclear <br>goals, projects, etc.)?  Please make specific comments.",
                                         },
                                       ],
                        _label      => 4,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "What are the main PLANNING challenges that <%fullname%> faces (e.g., no formal planning, unclear <br>goals, projects, etc.)?  Please make specific comments.",
                        _qnum       => 6,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q5",
                                           var => "Q5",
                                           var_label => "-<%qbanner%><P><%q_label%> What are the main ORGANIZING challenges that <%fullname%> faces (e.g., personal organization, <br>availability of supplies, equipment, financial resources, time, organizational structure, etc.)?  <br>Please make specific comments.",
                                         },
                                       ],
                        _label      => 5,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "<%qbanner%><P><%q_label%> What are the main ORGANIZING challenges that <%fullname%> faces (e.g., personal organization, <br>availability of supplies, equipment, financial resources, time, organizational structure, etc.)?  <br>Please make specific comments.",
                        _qnum       => 7,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q6",
                                           var => "Q6",
                                           var_label => "-What are the main STAFFING challenges that <%fullname%> faces (e.g., recruiting, selecting right <br>people, training, development, retaining, etc.)?  <br>Please make specific comments.",
                                         },
                                       ],
                        _label      => 6,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "What are the main STAFFING challenges that <%fullname%> faces (e.g., recruiting, selecting right <br>people, training, development, retaining, etc.)?  <br>Please make specific comments.",
                        _qnum       => 8,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q7",
                                           var => "Q7",
                                           var_label => "-What are the main CONTROLLING challenges that <%fullname%> faces (e.g., accountability, <br>follow-through, taking corrective action, cost and inventory control, productivity, quality, etc.)?  <br>Please make specific comments.",
                                         },
                                       ],
                        _label      => 7,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "What are the main CONTROLLING challenges that <%fullname%> faces (e.g., accountability, <br>follow-through, taking corrective action, cost and inventory control, productivity, quality, etc.)?  <br>Please make specific comments.",
                        _qnum       => 9,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q8",
                                           var => "Q8",
                                           var_label => "-What are the main LEADING challenges that <%fullname%> faces (e.g., clear vision, motivation, <br>teamwork, initiating action, innovation, commitment to team goals, etc.)?  <br>Please make specific comments.",
                                         },
                                       ],
                        _label      => 8,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "What are the main LEADING challenges that <%fullname%> faces (e.g., clear vision, motivation, <br>teamwork, initiating action, innovation, commitment to team goals, etc.)?  <br>Please make specific comments.",
                        _qnum       => 10,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [""],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q9",
                                           var => "Q9",
                                           var_label => "-If you could be <%fullname%>'s consultant, what specific suggestions would you give to solve any of the <br>above issues?",
                                         },
                                       ],
                        _label      => 9,
                        _opt        => { dk => undef, instr => "", scale => 0 },
                        _prompt     => "If you could be <%fullname%>'s consultant, what specific suggestions would you give to solve any of the <br>above issues?",
                        _qnum       => 11,
                        _qtype      => 5,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [
                                         "Clearly communicates vision and values",
                                         "Demonstrates determination and relentless resolve",
                                         "Demonstrates integrity",
                                         "Shows confidence",
                                         "Develops trust",
                                         "Is an excellent coach and mentor",
                                         "Inspires continuous improvement",
                                         "Demonstrates personal humility",
                                         "Demonstrates passion and commitment",
                                         "Confronts difficult issues and finds resolution",
                                         "Attracts strong people to the organization",
                                         "Maintains the focus of the organization",
                                         "Each team member has clear, quantifiable goals",
                                         "Demonstrates empathy",
                                         "Encourages excellence",
                                         "Job duties of the team are aligned with the organization's direction",
                                         "Discovers and develops the strengths of others",
                                         "Embraces and implements change",
                                       ],
                        _dataInfo   => [
                                         {
                                           "pos" => 0,
                                           rkey => "_Q10",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q10x1",
                                           var_label => "Clearly communicates vision and values-<%qbanner%><P><%q_label%> Leading Abilities (<%fullname%>'s ability to inspire people to achieve goals)<BR><BR> <SPAN class=\"body\">Please select the numbers which best describe <%fullname%>'s management and leadership abilities, 1 being poor, 9 being excellent.  <BR><%fullname%> and <%hisher%> manager or partner will complete the same form and the comparative results will be used as a coaching tool. <BR>Please be candid.</span>",
                                         },
                                         {
                                           "pos" => 1,
                                           rkey => "_Q10",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q10x2",
                                           var_label => "Demonstrates determination and relentless resolve-<%qbanner%><P><%q_label%> Leading Abilities (<%fullname%>'s ability to inspire people to achieve goals)<BR><BR> <SPAN class=\"body\">Please select the numbers which best describe <%fullname%>'s management and leadership abilities, 1 being poor, 9 being excellent.  <BR><%fullname%> and <%hisher%> manager or partner will complete the same form and the comparative results will be used as a coaching tool. <BR>Please be candid.</span>",
                                         },
                                         {
                                           "pos" => 2,
                                           rkey => "_Q10",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q10x3",
                                           var_label => "Demonstrates integrity-<%qbanner%><P><%q_label%> Leading Abilities (<%fullname%>'s ability to inspire people to achieve goals)<BR><BR> <SPAN class=\"body\">Please select the numbers which best describe <%fullname%>'s management and leadership abilities, 1 being poor, 9 being excellent.  <BR><%fullname%> and <%hisher%> manager or partner will complete the same form and the comparative results will be used as a coaching tool. <BR>Please be candid.</span>",
                                         },
                                         {
                                           "pos" => 3,
                                           rkey => "_Q10",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q10x4",
                                           var_label => "Shows confidence-<%qbanner%><P><%q_label%> Leading Abilities (<%fullname%>'s ability to inspire people to achieve goals)<BR><BR> <SPAN class=\"body\">Please select the numbers which best describe <%fullname%>'s management and leadership abilities, 1 being poor, 9 being excellent.  <BR><%fullname%> and <%hisher%> manager or partner will complete the same form and the comparative results will be used as a coaching tool. <BR>Please be candid.</span>",
                                         },
                                         {
                                           "pos" => 4,
                                           rkey => "_Q10",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q10x5",
                                           var_label => "Develops trust-<%qbanner%><P><%q_label%> Leading Abilities (<%fullname%>'s ability to inspire people to achieve goals)<BR><BR> <SPAN class=\"body\">Please select the numbers which best describe <%fullname%>'s management and leadership abilities, 1 being poor, 9 being excellent.  <BR><%fullname%> and <%hisher%> manager or partner will complete the same form and the comparative results will be used as a coaching tool. <BR>Please be candid.</span>",
                                         },
                                         {
                                           "pos" => 5,
                                           rkey => "_Q10",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q10x6",
                                           var_label => "Is an excellent coach and mentor-<%qbanner%><P><%q_label%> Leading Abilities (<%fullname%>'s ability to inspire people to achieve goals)<BR><BR> <SPAN class=\"body\">Please select the numbers which best describe <%fullname%>'s management and leadership abilities, 1 being poor, 9 being excellent.  <BR><%fullname%> and <%hisher%> manager or partner will complete the same form and the comparative results will be used as a coaching tool. <BR>Please be candid.</span>",
                                         },
                                         {
                                           "pos" => 6,
                                           rkey => "_Q10",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q10x7",
                                           var_label => "Inspires continuous improvement-<%qbanner%><P><%q_label%> Leading Abilities (<%fullname%>'s ability to inspire people to achieve goals)<BR><BR> <SPAN class=\"body\">Please select the numbers which best describe <%fullname%>'s management and leadership abilities, 1 being poor, 9 being excellent.  <BR><%fullname%> and <%hisher%> manager or partner will complete the same form and the comparative results will be used as a coaching tool. <BR>Please be candid.</span>",
                                         },
                                         {
                                           "pos" => 7,
                                           rkey => "_Q10",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q10x8",
                                           var_label => "Demonstrates personal humility-<%qbanner%><P><%q_label%> Leading Abilities (<%fullname%>'s ability to inspire people to achieve goals)<BR><BR> <SPAN class=\"body\">Please select the numbers which best describe <%fullname%>'s management and leadership abilities, 1 being poor, 9 being excellent.  <BR><%fullname%> and <%hisher%> manager or partner will complete the same form and the comparative results will be used as a coaching tool. <BR>Please be candid.</span>",
                                         },
                                         {
                                           "pos" => 8,
                                           rkey => "_Q10",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q10x9",
                                           var_label => "Demonstrates passion and commitment-<%qbanner%><P><%q_label%> Leading Abilities (<%fullname%>'s ability to inspire people to achieve goals)<BR><BR> <SPAN class=\"body\">Please select the numbers which best describe <%fullname%>'s management and leadership abilities, 1 being poor, 9 being excellent.  <BR><%fullname%> and <%hisher%> manager or partner will complete the same form and the comparative results will be used as a coaching tool. <BR>Please be candid.</span>",
                                         },
                                         {
                                           "pos" => 9,
                                           rkey => "_Q10",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q10x10",
                                           var_label => "Confronts difficult issues and finds resolution-<%qbanner%><P><%q_label%> Leading Abilities (<%fullname%>'s ability to inspire people to achieve goals)<BR><BR> <SPAN class=\"body\">Please select the numbers which best describe <%fullname%>'s management and leadership abilities, 1 being poor, 9 being excellent.  <BR><%fullname%> and <%hisher%> manager or partner will complete the same form and the comparative results will be used as a coaching tool. <BR>Please be candid.</span>",
                                         },
                                         {
                                           "pos" => 10,
                                           rkey => "_Q10",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q10x11",
                                           var_label => "Attracts strong people to the organization-<%qbanner%><P><%q_label%> Leading Abilities (<%fullname%>'s ability to inspire people to achieve goals)<BR><BR> <SPAN class=\"body\">Please select the numbers which best describe <%fullname%>'s management and leadership abilities, 1 being poor, 9 being excellent.  <BR><%fullname%> and <%hisher%> manager or partner will complete the same form and the comparative results will be used as a coaching tool. <BR>Please be candid.</span>",
                                         },
                                         {
                                           "pos" => 11,
                                           rkey => "_Q10",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q10x12",
                                           var_label => "Maintains the focus of the organization-<%qbanner%><P><%q_label%> Leading Abilities (<%fullname%>'s ability to inspire people to achieve goals)<BR><BR> <SPAN class=\"body\">Please select the numbers which best describe <%fullname%>'s management and leadership abilities, 1 being poor, 9 being excellent.  <BR><%fullname%> and <%hisher%> manager or partner will complete the same form and the comparative results will be used as a coaching tool. <BR>Please be candid.</span>",
                                         },
                                         {
                                           "pos" => 12,
                                           rkey => "_Q10",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q10x13",
                                           var_label => "Each team member has clear, quantifiable goals-<%qbanner%><P><%q_label%> Leading Abilities (<%fullname%>'s ability to inspire people to achieve goals)<BR><BR> <SPAN class=\"body\">Please select the numbers which best describe <%fullname%>'s management and leadership abilities, 1 being poor, 9 being excellent.  <BR><%fullname%> and <%hisher%> manager or partner will complete the same form and the comparative results will be used as a coaching tool. <BR>Please be candid.</span>",
                                         },
                                         {
                                           "pos" => 13,
                                           rkey => "_Q10",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q10x14",
                                           var_label => "Demonstrates empathy-<%qbanner%><P><%q_label%> Leading Abilities (<%fullname%>'s ability to inspire people to achieve goals)<BR><BR> <SPAN class=\"body\">Please select the numbers which best describe <%fullname%>'s management and leadership abilities, 1 being poor, 9 being excellent.  <BR><%fullname%> and <%hisher%> manager or partner will complete the same form and the comparative results will be used as a coaching tool. <BR>Please be candid.</span>",
                                         },
                                         {
                                           "pos" => 14,
                                           rkey => "_Q10",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q10x15",
                                           var_label => "Encourages excellence-<%qbanner%><P><%q_label%> Leading Abilities (<%fullname%>'s ability to inspire people to achieve goals)<BR><BR> <SPAN class=\"body\">Please select the numbers which best describe <%fullname%>'s management and leadership abilities, 1 being poor, 9 being excellent.  <BR><%fullname%> and <%hisher%> manager or partner will complete the same form and the comparative results will be used as a coaching tool. <BR>Please be candid.</span>",
                                         },
                                         {
                                           "pos" => 15,
                                           rkey => "_Q10",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q10x16",
                                           var_label => "Job duties of the team are aligned with the organization's direction-<%qbanner%><P><%q_label%> Leading Abilities (<%fullname%>'s ability to inspire people to achieve goals)<BR><BR> <SPAN class=\"body\">Please select the numbers which best describe <%fullname%>'s management and leadership abilities, 1 being poor, 9 being excellent.  <BR><%fullname%> and <%hisher%> manager or partner will complete the same form and the comparative results will be used as a coaching tool. <BR>Please be candid.</span>",
                                         },
                                         {
                                           "pos" => 16,
                                           rkey => "_Q10",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q10x17",
                                           var_label => "Discovers and develops the strengths of others-<%qbanner%><P><%q_label%> Leading Abilities (<%fullname%>'s ability to inspire people to achieve goals)<BR><BR> <SPAN class=\"body\">Please select the numbers which best describe <%fullname%>'s management and leadership abilities, 1 being poor, 9 being excellent.  <BR><%fullname%> and <%hisher%> manager or partner will complete the same form and the comparative results will be used as a coaching tool. <BR>Please be candid.</span>",
                                         },
                                         {
                                           "pos" => 17,
                                           rkey => "_Q10",
                                           val_if_true => "+1",
                                           val_label => { 1 => "1 Poor ", 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, 8 => 8, 9 => "9 Excellent " },
                                           var => "Q10x18",
                                           var_label => "Embraces and implements change-<%qbanner%><P><%q_label%> Leading Abilities (<%fullname%>'s ability to inspire people to achieve goals)<BR><BR> <SPAN class=\"body\">Please select the numbers which best describe <%fullname%>'s management and leadership abilities, 1 being poor, 9 being excellent.  <BR><%fullname%> and <%hisher%> manager or partner will complete the same form and the comparative results will be used as a coaching tool. <BR>Please be candid.</span>",
                                         },
                                       ],
                        _label      => 10,
                        _opt        => {
                                         dk => undef,
                                         instr => "",
                                         left_word => "Poor",
                                         middle => undef,
                                         right_word => "Excellent",
                                         scale => 9,
                                       },
                        _prompt     => "<%qbanner%><P><%q_label%> Leading Abilities (<%fullname%>'s ability to inspire people to achieve goals)<BR><BR> <SPAN class=\"body\">Please select the numbers which best describe <%fullname%>'s management and leadership abilities, 1 being poor, 9 being excellent.  <BR><%fullname%> and <%hisher%> manager or partner will complete the same form and the comparative results will be used as a coaching tool. <BR>Please be candid.</span>",
                        _qnum       => 12,
                        _qtype      => 14,
                        _scores     => [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                        _setvalues  => [
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                       ],
                        _skips      => [
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                       ],
                        _vars       => [
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                         undef,
                                       ],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _code       => [
                                         "my \$dcount = &count_data;",
                                         "&debug(\"Datacount = \$dcount\");",
                                         "if (\$dcount>0) {\$q_no = goto_qlab(\"LAST\") - 1;}",
                                         "if (\$dcount==0) {&db_conn;&db_set_status(\$survey_id,\$resp{id},\$resp{token},0,0)}",
                                       ],
                        _dataInfo   => [],
                        _label      => "CHECK",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "Check if we have enough data to allow submission of form",
                        _qnum       => 13,
                        _qtype      => 27,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames    => [],
                        _attributes    => [],
                        _dataInfo      => [
                                            {
                                              "pos" => 0,
                                              rkey => "ext_BACK2",
                                              type => "hidden",
                                              var => "BACK2",
                                              var_label => "See external page \"nodata.htm\"",
                                            },
                                          ],
                        _external_info => {
                                            names    => [undef, "BACK2"],
                                            options  => {
                                                          "" => {
                                                                alt => "HOME",
                                                                onclick => "document.location='/cgi-mr/pwikit_login.pl?id=<%id%>&password=<%token%>'",
                                                                tabindex => -1,
                                                                type => "BUTTON",
                                                                value => " HOME ",
                                                              },
                                                          BACK2 => { name => "BACK2", type => "hidden" },
                                                        },
                                            "values" => { "" => [" HOME ", " GO BACK "] },
                                          },
                        _label         => "NODATA",
                        _opt           => { external => "nodata.htm", instr => "", scale => 0 },
                        _prompt        => "See external page \"nodata.htm\"",
                        _qnum          => 14,
                        _qtype         => 7,
                        _scores        => [],
                        _setvalues     => [],
                        _skips         => [],
                        _vars          => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _code       => ["duedate=duedate", "id=id", "token=token"],
                        _dataInfo   => [],
                        _label      => "BREAK",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "",
                        _qnum       => 15,
                        _qtype      => 20,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames    => [],
                        _attributes    => [],
                        _dataInfo      => [
                                            {
                                              "pos" => 0,
                                              rkey => "ext_finish",
                                              type => "hidden",
                                              var => "finish",
                                              var_label => "This is implemented as an external",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_q_labs",
                                              var => "q_labs",
                                              var_label => "This is implemented as an external",
                                            },
                                            {
                                              "pos" => 0,
                                              rkey => "ext_BACK2",
                                              type => "hidden",
                                              var => "BACK2",
                                              var_label => "This is implemented as an external",
                                            },
                                          ],
                        _external_info => {
                                            names    => ["finish", "q_labs", undef, "BACK2"],
                                            options  => {
                                                          "" => {
                                                                onclick => "document.q.finish.value='';",
                                                                type    => "SUBMIT",
                                                                value   => " SUBMIT ",
                                                              },
                                                          BACK2 => { name => "BACK2", type => "hidden" },
                                                          finish => { name => "finish", type => "hidden" },
                                                          q_labs => {},
                                                        },
                                            "values" => { "" => [" SUBMIT ", "NOT YET", " GO BACK "] },
                                          },
                        _label         => "LAST",
                        _opt           => { external => "last.htm", instr => "", scale => 0 },
                        _prompt        => "This is implemented as an external",
                        _qnum          => 16,
                        _qtype         => 7,
                        _scores        => [],
                        _setvalues     => [],
                        _skips         => [],
                        _vars          => [],
                      }, "TPerl::Survey::Question"),
                      bless({
                        _a_varnames => [],
                        _attributes => [],
                        _code       => [
                                         "&db_conn;&db_do(\"UPDATE MAP010 set APPROVED=0 where PWD='\$resp{token}'\");",
                                       ],
                        _dataInfo   => [],
                        _label      => "LAST1",
                        _opt        => { instr => "", scale => 0 },
                        _prompt     => "Final reset of APPROVED flag",
                        _qnum       => 17,
                        _qtype      => 27,
                        _scores     => [],
                        _setvalues  => [],
                        _skips      => [],
                        _vars       => [],
                      }, "TPerl::Survey::Question"),
                    ],
}, "TPerl::Survey")
