#!/usr/bin/perl
# generated by TPerl::Parser::_config_file 
# Wed May 16 23:09:54 2007
$numq = 1;
$do_footer = '0';
$survey_name = 'Under construction';
$one_at_a_time = '1';
$block_size = '999';
$plain = '1';
$textcolor = '#000000';
$no_methods = '1';
$from_email = 'support@mappwi.com';
$mailto = 'info@market-research.com';
$style = 'plain';
$background = '';
$window_title = 'XXX101 - Under construction';
$do_body = '1';
$thankyou_url = '/MAP101/thanks.htm';
$from_name = 'info@market-research.com';
$bg_color = '#FFFFFF';
$banner_top = '0';
1;
